import type { LegacyCapabilityRow } from './composio-capability-catalog.types'

export const CALENDLY_LEGACY_CAPABILITIES: LegacyCapabilityRow[] = [
  {
    integration_id: 'calendly',
    action_slug: 'list_event_types',
    execution_mode: 'legacy',
    display_name: 'List Event Types',
    description: 'Get all Calendly event types for the user.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'calendly',
    action_slug: 'get_event_type',
    execution_mode: 'legacy',
    display_name: 'Get Event Type',
    description: 'Get details of a specific event type.',
    parameters: { uuid: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'calendly',
    action_slug: 'create_event_type',
    execution_mode: 'legacy',
    display_name: 'Create Event Type',
    description: 'Create a new Calendly event type.',
    parameters: {
      name: { type: 'string', required: true },
      slug: { type: 'string' },
      duration_minutes: { type: 'number', required: true },
      description_plain: { type: 'string' },
      color: { type: 'string' },
      type: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'calendly',
    action_slug: 'update_event_type',
    execution_mode: 'legacy',
    display_name: 'Update Event Type',
    description: 'Update an existing event type.',
    parameters: {
      uuid: { type: 'string', required: true },
      name: { type: 'string' },
      description_plain: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'calendly',
    action_slug: 'create_one_off_event_type',
    execution_mode: 'legacy',
    display_name: 'Create One-Off Event',
    description: 'Create a single-use event type with a date range.',
    parameters: {
      name: { type: 'string', required: true },
      duration_minutes: { type: 'number', required: true },
      date_setting: { type: 'object' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'calendly',
    action_slug: 'list_scheduled_events',
    execution_mode: 'legacy',
    display_name: 'List Scheduled Events',
    description: 'List upcoming scheduled events. Filter by date range or status.',
    parameters: {
      min_start_time: { type: 'string' },
      max_start_time: { type: 'string' },
      status: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'calendly',
    action_slug: 'cancel_scheduled_event',
    execution_mode: 'legacy',
    display_name: 'Cancel Scheduled Event',
    description: 'Cancel a scheduled Calendly event.',
    parameters: { uuid: { type: 'string', required: true }, reason: { type: 'string' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'calendly',
    action_slug: 'list_available_times',
    execution_mode: 'legacy',
    display_name: 'List Available Times',
    description: 'Check available time slots for an event type.',
    parameters: {
      event_type_uri: { type: 'string', required: true },
      start_time: { type: 'string', required: true },
      end_time: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  }
]
