import type { LegacyCapabilityRow } from './composio-capability-catalog.types'

export const DROPBOX_LEGACY_CAPABILITIES: LegacyCapabilityRow[] = [
  {
    integration_id: 'dropbox',
    action_slug: 'list_files',
    execution_mode: 'legacy',
    display_name: 'List Files',
    description: 'Browse Dropbox files. Filter by path.',
    parameters: { path: { type: 'string' }, cursor: { type: 'string' }, limit: { type: 'number' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'dropbox',
    action_slug: 'search_files',
    execution_mode: 'legacy',
    display_name: 'Search Files',
    description: 'Search Dropbox files by keyword.',
    parameters: { query: { type: 'string', required: true }, path: { type: 'string' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'dropbox',
    action_slug: 'get_file_metadata',
    execution_mode: 'legacy',
    display_name: 'Get File Metadata',
    description: 'Get file details from Dropbox.',
    parameters: { path: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'dropbox',
    action_slug: 'download_file',
    execution_mode: 'legacy',
    display_name: 'Download File',
    description: 'Download a file from Dropbox.',
    parameters: { path: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'dropbox',
    action_slug: 'upload_file',
    execution_mode: 'legacy',
    display_name: 'Upload File',
    description: 'Upload a file to Dropbox. Mode: add or overwrite.',
    parameters: {
      path: { type: 'string', required: true },
      content: { type: 'string', required: true },
      mode: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'dropbox',
    action_slug: 'delete_file',
    execution_mode: 'legacy',
    display_name: 'Delete File',
    description: 'Delete a file from Dropbox.',
    parameters: { path: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'dropbox',
    action_slug: 'create_shared_link',
    execution_mode: 'legacy',
    display_name: 'Create Shared Link',
    description: 'Create a share link for a Dropbox file.',
    parameters: { path: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'dropbox',
    action_slug: 'move_file',
    execution_mode: 'legacy',
    display_name: 'Move File',
    description: 'Move a file within Dropbox.',
    parameters: {
      fromPath: { type: 'string', required: true },
      toPath: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  }
]
