import type { LegacyCapabilityRow } from './composio-capability-catalog.types'

export const FANBASIS_LEGACY_CAPABILITIES: LegacyCapabilityRow[] = [
  {
    integration_id: 'fanbasis',
    action_slug: 'list_products',
    execution_mode: 'legacy',
    display_name: 'List Products',
    description: 'List all products for a creator on FanBasis.',
    parameters: { page: { type: 'number' }, per_page: { type: 'number' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'create_checkout_session',
    execution_mode: 'legacy',
    display_name: 'Create Checkout Session',
    description: 'Create a new checkout session with product, pricing, and subscription details.',
    parameters: {
      'product.title': { type: 'string', required: true },
      amount_cents: { type: 'number', required: true },
      type: {
        type: 'string',
        required: true,
        description: 'subscription | onetime_reusable | onetime_non_reusable',
      },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_checkout_session',
    execution_mode: 'legacy',
    display_name: 'Get Checkout Session',
    description: 'Retrieve a checkout session by ID.',
    parameters: { id: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'delete_checkout_session',
    execution_mode: 'legacy',
    display_name: 'Delete Checkout Session',
    description: 'Delete a checkout session by ID.',
    parameters: { id: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'create_embedded_checkout_session',
    execution_mode: 'legacy',
    display_name: 'Create Embedded Checkout',
    description: 'Create an embedded checkout session with metadata.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_transactions',
    execution_mode: 'legacy',
    display_name: 'Get Transactions',
    description: 'Get all transactions for a creator with optional product filter.',
    parameters: {
      page: { type: 'number' },
      per_page: { type: 'number' },
      product_id: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_transaction',
    execution_mode: 'legacy',
    display_name: 'Get Transaction',
    description: 'Get a single transaction by ID.',
    parameters: { transactionId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'refund_transaction',
    execution_mode: 'legacy',
    display_name: 'Refund Transaction',
    description: 'Refund a transaction by transaction ID.',
    parameters: { transactionId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_product_subscriptions',
    execution_mode: 'legacy',
    display_name: 'Get Product Subscriptions',
    description: 'Get subscriptions for a specific product.',
    parameters: {
      productId: { type: 'string', required: true },
      page: { type: 'number' },
      per_page: { type: 'number' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_checkout_session_subscriptions',
    execution_mode: 'legacy',
    display_name: 'Get Session Subscriptions',
    description: 'Get subscriptions for a specific checkout session.',
    parameters: {
      id: { type: 'string', required: true },
      page: { type: 'number' },
      per_page: { type: 'number' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'cancel_subscription',
    execution_mode: 'legacy',
    display_name: 'Cancel Subscription',
    description: 'Cancel a specific subscription for a checkout session.',
    parameters: {
      sessionId: { type: 'string', required: true },
      subscriptionId: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'extend_subscription',
    execution_mode: 'legacy',
    display_name: 'Extend Subscription',
    description: 'Extend a subscription for a user and product by a number of days.',
    parameters: {
      sessionId: { type: 'string', required: true },
      user_id: { type: 'string', required: true },
      duration_days: { type: 'number', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_customers',
    execution_mode: 'legacy',
    display_name: 'Get Customers',
    description: 'Get unique customers for a creator.',
    parameters: { page: { type: 'number' }, per_page: { type: 'number' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'charge_customer',
    execution_mode: 'legacy',
    display_name: 'Charge Customer',
    description: 'Charge a customer using a specific payment method.',
    parameters: { customerId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_customer_payment_methods',
    execution_mode: 'legacy',
    display_name: 'Get Payment Methods',
    description: 'Get saved payment methods for a customer.',
    parameters: { customerId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_subscribers',
    execution_mode: 'legacy',
    display_name: 'Get Subscribers',
    description: 'Get all subscribers for a creator with optional filtering.',
    parameters: {
      page: { type: 'number' },
      per_page: { type: 'number' },
      status: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'list_discount_codes',
    execution_mode: 'legacy',
    display_name: 'List Discount Codes',
    description: 'List discount codes with pagination and search.',
    parameters: {
      page: { type: 'number' },
      per_page: { type: 'number' },
      search: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'create_discount_code',
    execution_mode: 'legacy',
    display_name: 'Create Discount Code',
    description: 'Create a new discount code.',
    parameters: { code: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_discount_code',
    execution_mode: 'legacy',
    display_name: 'Get Discount Code',
    description: 'Get a specific discount code by ID.',
    parameters: { id: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'update_discount_code',
    execution_mode: 'legacy',
    display_name: 'Update Discount Code',
    description: 'Update an existing discount code.',
    parameters: { id: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'delete_discount_code',
    execution_mode: 'legacy',
    display_name: 'Delete Discount Code',
    description: 'Delete a discount code by ID.',
    parameters: { id: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'create_webhook_subscription',
    execution_mode: 'legacy',
    display_name: 'Create Webhook Subscription',
    description: 'Create a new webhook subscription.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_webhook_subscriptions',
    execution_mode: 'legacy',
    display_name: 'Get Webhook Subscriptions',
    description: 'Get all webhook subscriptions.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'delete_webhook_subscription',
    execution_mode: 'legacy',
    display_name: 'Delete Webhook Subscription',
    description: 'Delete a webhook subscription by ID.',
    parameters: { id: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'test_webhook_subscription',
    execution_mode: 'legacy',
    display_name: 'Test Webhook Subscription',
    description: 'Send a test event to a webhook subscription.',
    parameters: { id: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fanbasis',
    action_slug: 'get_checkout_session_transactions',
    execution_mode: 'legacy',
    display_name: 'Get Session Transactions',
    description: 'Get transactions for a specific checkout session.',
    parameters: {
      id: { type: 'string', required: true },
      page: { type: 'number' },
      per_page: { type: 'number' },
    },
    examples: [],
    metadata: {},
    domains: [],
  }
]
