import type { LegacyCapabilityRow } from './composio-capability-catalog.types'

export const FIREFLIES_LEGACY_CAPABILITIES: LegacyCapabilityRow[] = [
  {
    integration_id: 'fireflies',
    action_slug: 'list_transcripts',
    execution_mode: 'legacy',
    display_name: 'List Transcripts',
    description: 'Retrieve recent Fireflies meeting transcripts.',
    parameters: { limit: { type: 'number' }, skip: { type: 'number' }, title: { type: 'string' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fireflies',
    action_slug: 'get_transcript',
    execution_mode: 'legacy',
    display_name: 'Get Transcript',
    description: 'Get a single transcript by ID.',
    parameters: { transcriptId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fireflies',
    action_slug: 'get_transcript_sentences',
    execution_mode: 'legacy',
    display_name: 'Get Transcript Sentences',
    description: 'Get transcript with sentence-level speaker data.',
    parameters: { transcriptId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fireflies',
    action_slug: 'get_user',
    execution_mode: 'legacy',
    display_name: 'Get User',
    description: 'Get Fireflies account info.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'fireflies',
    action_slug: 'sync',
    execution_mode: 'legacy',
    display_name: 'Sync to Brain',
    description: 'Sync recent transcripts into Brain for long-term memory.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  }
]
