import type { LegacyCapabilityRow } from './composio-capability-catalog.types'

export const SLACK_LEGACY_CAPABILITIES: LegacyCapabilityRow[] = [
  {
    integration_id: 'slack',
    action_slug: 'SLACK_SEARCH_MESSAGES',
    execution_mode: 'legacy',
    display_name: 'Search Slack Messages',
    description:
      'Search for messages across the Slack workspace. Results are scoped to channels the Vibey bot can see.',
    parameters: {
      query: { type: 'string', required: true },
      count: { type: 'number' },
      sort: { type: 'string' },
      sort_dir: { type: 'string' },
      cursor: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_SEARCH_FILES',
    execution_mode: 'legacy',
    display_name: 'Search Slack Files',
    description:
      'Search for files uploaded in the Slack workspace. Results are scoped to files the Vibey bot can see.',
    parameters: {
      query: { type: 'string', required: true },
      count: { type: 'number' },
      sort: { type: 'string' },
      sort_dir: { type: 'string' },
      cursor: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_LIST_CHANNELS',
    execution_mode: 'legacy',
    display_name: 'List Slack Channels',
    description: 'List public, private, group-DM, and DM conversations visible to the Vibey bot.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_LIST_USERS',
    execution_mode: 'legacy',
    display_name: 'List Slack Users',
    description: 'List all members of the Slack workspace.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_GET_USER_INFO',
    execution_mode: 'legacy',
    display_name: 'Get Slack User Info',
    description: 'Fetch detailed profile for a single Slack user.',
    parameters: {
      slack_user_id: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_FIND_USER_BY_EMAIL',
    execution_mode: 'legacy',
    display_name: 'Find Slack User by Email',
    description: 'Resolve a Slack user by their email address.',
    parameters: {
      email: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_SEND_MESSAGE',
    execution_mode: 'legacy',
    display_name: 'Send Slack Message',
    description:
      'Post a message to a Slack channel or DM. Pass thread_ts to reply in an existing thread.',
    parameters: {
      channel_id: { type: 'string', required: true },
      text: { type: 'string', required: true },
      thread_ts: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_UPDATE_MESSAGE',
    execution_mode: 'legacy',
    display_name: 'Update Slack Message',
    description: 'Edit a previously posted Slack message (must have been posted by the Vibey bot).',
    parameters: {
      channel_id: { type: 'string', required: true },
      ts: { type: 'string', required: true },
      text: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_DELETE_MESSAGE',
    execution_mode: 'legacy',
    display_name: 'Delete Slack Message',
    description:
      'Delete a previously posted Slack message (must have been posted by the Vibey bot).',
    parameters: {
      channel_id: { type: 'string', required: true },
      ts: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_GET_CHANNEL_HISTORY',
    execution_mode: 'legacy',
    display_name: 'Get Slack Channel History',
    description: 'Fetch recent messages from a Slack channel or DM.',
    parameters: {
      channel_id: { type: 'string', required: true },
      limit: { type: 'number' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_GET_THREAD_REPLIES',
    execution_mode: 'legacy',
    display_name: 'Get Slack Thread Replies',
    description: 'Fetch all replies to a message thread in a channel.',
    parameters: {
      channel_id: { type: 'string', required: true },
      thread_ts: { type: 'string', required: true },
      limit: { type: 'number' },
      cursor: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_ADD_REACTION',
    execution_mode: 'legacy',
    display_name: 'Add Slack Reaction',
    description: 'Add an emoji reaction to a message.',
    parameters: {
      channel_id: { type: 'string', required: true },
      ts: { type: 'string', required: true },
      name: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_REMOVE_REACTION',
    execution_mode: 'legacy',
    display_name: 'Remove Slack Reaction',
    description: 'Remove an emoji reaction from a message.',
    parameters: {
      channel_id: { type: 'string', required: true },
      ts: { type: 'string', required: true },
      name: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_OPEN_DM',
    execution_mode: 'legacy',
    display_name: 'Open Slack DM',
    description: 'Open (or reuse) a direct-message channel with a Slack user. Returns channel_id.',
    parameters: {
      slack_user_id: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_UPLOAD_FILE',
    execution_mode: 'legacy',
    display_name: 'Upload File to Slack',
    description:
      'Upload a file to a Slack channel by providing a public URL. Vibey downloads the URL server-side and uploads to Slack.',
    parameters: {
      channel_id: { type: 'string', required: true },
      file_url: { type: 'string', required: true },
      filename: { type: 'string', required: true },
      thread_ts: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'slack',
    action_slug: 'SLACK_GET_FILE_INFO',
    execution_mode: 'legacy',
    display_name: 'Get Slack File Info',
    description: 'Fetch metadata for a file uploaded to Slack by file_id.',
    parameters: {
      file_id: { type: 'string', required: true },
    },
    examples: [],
    metadata: {},
    domains: [],
  }
]
