import type { LegacyCapabilityRow } from './composio-capability-catalog.types'

export const STRIPE_LEGACY_CAPABILITIES: LegacyCapabilityRow[] = [
  {
    integration_id: 'stripe',
    action_slug: 'list_charges',
    execution_mode: 'legacy',
    display_name: 'List Charges',
    description:
      'List Stripe charges (payments). Returns amount, currency, status, customer, refund info, and timestamps. Supports filtering by date range (created_gte/created_lte as Unix timestamps) and customer ID. Use for revenue analysis, payment history, and financial reporting.',
    parameters: {
      limit: { type: 'number' },
      starting_after: { type: 'string' },
      created_gte: { type: 'number' },
      created_lte: { type: 'number' },
      customer: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'list_customers',
    execution_mode: 'legacy',
    display_name: 'List Customers',
    description:
      'List Stripe customers. Returns name, email, currency, creation date, and metadata. Supports filtering by email and date range. Use for customer analysis, user counts, and CRM data.',
    parameters: {
      limit: { type: 'number' },
      starting_after: { type: 'string' },
      email: { type: 'string' },
      created_gte: { type: 'number' },
      created_lte: { type: 'number' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'list_subscriptions',
    execution_mode: 'legacy',
    display_name: 'List Subscriptions',
    description:
      'List Stripe subscriptions. Returns status (active, canceled, past_due, etc.), billing periods, cancel dates, and plan details. Supports filtering by status, customer, and date range. CRITICAL for churn analysis — compare active vs canceled subscriptions over time.',
    parameters: {
      limit: { type: 'number' },
      starting_after: { type: 'string' },
      status: { type: 'string' },
      customer: { type: 'string' },
      created_gte: { type: 'number' },
      created_lte: { type: 'number' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'list_invoices',
    execution_mode: 'legacy',
    display_name: 'List Invoices',
    description:
      'List Stripe invoices. Returns amount due/paid/remaining, status (paid, open, void, uncollectible), billing period, and subscription link. Supports filtering by status, customer, subscription, and date range. Use for billing analysis and revenue reconciliation.',
    parameters: {
      limit: { type: 'number' },
      starting_after: { type: 'string' },
      status: { type: 'string' },
      customer: { type: 'string' },
      subscription: { type: 'string' },
      created_gte: { type: 'number' },
      created_lte: { type: 'number' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'list_products',
    execution_mode: 'legacy',
    display_name: 'List Products',
    description: 'List all Stripe products.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'create_product',
    execution_mode: 'legacy',
    display_name: 'Create Product',
    description: 'Create a Stripe product.',
    parameters: {
      name: { type: 'string', required: true },
      description: { type: 'string' },
      campaign_id: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'update_product',
    execution_mode: 'legacy',
    display_name: 'Update Product',
    description: 'Update a Stripe product.',
    parameters: {
      productId: { type: 'string', required: true },
      name: { type: 'string' },
      description: { type: 'string' },
      active: { type: 'boolean' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'delete_product',
    execution_mode: 'legacy',
    display_name: 'Delete Product',
    description: 'Delete a Stripe product.',
    parameters: { productId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'list_prices',
    execution_mode: 'legacy',
    display_name: 'List Prices',
    description: 'List all Stripe prices.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'create_price',
    execution_mode: 'legacy',
    display_name: 'Create Price',
    description: 'Create a price for a product.',
    parameters: {
      product_id: { type: 'string', required: true },
      unit_amount: { type: 'number', required: true },
      currency: { type: 'string', required: true },
      recurring: { type: 'object' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'list_payment_links',
    execution_mode: 'legacy',
    display_name: 'List Payment Links',
    description: 'List Stripe payment links.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'create_payment_link',
    execution_mode: 'legacy',
    display_name: 'Create Payment Link',
    description: 'Create a Stripe payment link for a price.',
    parameters: { price_id: { type: 'string', required: true }, campaign_id: { type: 'string' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'create_coupon',
    execution_mode: 'legacy',
    display_name: 'Create Coupon',
    description: 'Create a discount coupon.',
    parameters: {
      percent_off: { type: 'number' },
      duration: { type: 'string', required: true },
      name: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'create_refund',
    execution_mode: 'legacy',
    display_name: 'Create Refund',
    description: 'Process a refund for a charge.',
    parameters: {
      charge: { type: 'string', required: true },
      amount: { type: 'number' },
      reason: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'get_overview',
    execution_mode: 'legacy',
    display_name: 'Revenue Overview',
    description: 'Get overall revenue analytics. Optional date range.',
    parameters: { fromUnix: { type: 'number' }, toUnix: { type: 'number' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'get_campaign_overview',
    execution_mode: 'legacy',
    display_name: 'Campaign Revenue',
    description: 'Get revenue for a specific campaign.',
    parameters: { campaignId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'get_campaign_products',
    execution_mode: 'legacy',
    display_name: 'Campaign Products',
    description: 'List products tied to a campaign.',
    parameters: { campaignId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'get_campaign_payment_links',
    execution_mode: 'legacy',
    display_name: 'Campaign Payment Links',
    description: 'List payment links tied to a campaign.',
    parameters: { campaignId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'get_campaign_coupons',
    execution_mode: 'legacy',
    display_name: 'Campaign Coupons',
    description: 'List coupons tied to a campaign.',
    parameters: { campaignId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'stripe',
    action_slug: 'get_product_prices',
    execution_mode: 'legacy',
    display_name: 'Product Prices',
    description: 'List prices for a specific product.',
    parameters: { productId: { type: 'string', required: true } },
    examples: [],
    metadata: {},
    domains: [],
  }
]
