import type { LegacyCapabilityRow } from './composio-capability-catalog.types'

export const WORDPRESS_LEGACY_CAPABILITIES: LegacyCapabilityRow[] = [
  {
    integration_id: 'wordpress',
    action_slug: 'list_posts',
    execution_mode: 'legacy',
    display_name: 'List WordPress Posts',
    description:
      'List WordPress posts from the connected WordPress.com, Jetpack, or self-hosted WordPress site. Supports pagination, status, and search filters.',
    parameters: {
      page: { type: 'number' },
      per_page: { type: 'number' },
      search: { type: 'string' },
      status: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'create_post',
    execution_mode: 'legacy',
    display_name: 'Create WordPress Post',
    description:
      'Create a WordPress post with title, HTML content, excerpt, slug, category IDs, tag IDs, featured media, and draft or publish status.',
    parameters: {
      title: { type: 'string' },
      content: { type: 'string' },
      excerpt: { type: 'string' },
      slug: { type: 'string' },
      status: { type: 'string' },
      categories: { type: 'array' },
      tags: { type: 'array' },
      featured_media: { type: 'number' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'update_post',
    execution_mode: 'legacy',
    display_name: 'Update WordPress Post',
    description:
      'Update an existing WordPress post by post ID without creating a duplicate. Use this for editing drafts or republishing changed content.',
    parameters: {
      postId: { type: 'string', required: true },
      title: { type: 'string' },
      content: { type: 'string' },
      excerpt: { type: 'string' },
      slug: { type: 'string' },
      status: { type: 'string' },
      categories: { type: 'array' },
      tags: { type: 'array' },
      featured_media: { type: 'number' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'publish_blog_post',
    execution_mode: 'legacy',
    display_name: 'Publish Vibey Blog Post to WordPress',
    description:
      'Publish a Vibey blog_posts row to the connected WordPress site, then write wordpress_post_id, wordpress_post_url, and wordpress_synced_at back to blog_posts.metadata.',
    parameters: {
      blog_post_id: { type: 'string', required: true },
      status: { type: 'string' },
      update_existing: { type: 'boolean' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'list_pages',
    execution_mode: 'legacy',
    display_name: 'List WordPress Pages',
    description: 'List WordPress pages from the connected site with pagination and search filters.',
    parameters: {
      page: { type: 'number' },
      per_page: { type: 'number' },
      search: { type: 'string' },
      status: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'create_page',
    execution_mode: 'legacy',
    display_name: 'Create WordPress Page',
    description: 'Create a WordPress page on the connected site with title, HTML content, slug, and status.',
    parameters: {
      title: { type: 'string' },
      content: { type: 'string' },
      slug: { type: 'string' },
      status: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'update_page',
    execution_mode: 'legacy',
    display_name: 'Update WordPress Page',
    description: 'Update an existing WordPress page by page ID.',
    parameters: {
      pageId: { type: 'string', required: true },
      title: { type: 'string' },
      content: { type: 'string' },
      slug: { type: 'string' },
      status: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'upload_media',
    execution_mode: 'legacy',
    display_name: 'Upload WordPress Media',
    description:
      'Upload media to the connected WordPress site from an HTTPS URL or base64 payload, returning the WordPress media item for use as featured media.',
    parameters: {
      url: { type: 'string' },
      content_base64: { type: 'string' },
      filename: { type: 'string' },
      mime_type: { type: 'string' },
      title: { type: 'string' },
      alt_text: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'list_categories',
    execution_mode: 'legacy',
    display_name: 'List WordPress Categories',
    description: 'List post categories from the connected WordPress site.',
    parameters: { page: { type: 'number' }, per_page: { type: 'number' }, search: { type: 'string' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'create_category',
    execution_mode: 'legacy',
    display_name: 'Create WordPress Category',
    description: 'Create a WordPress post category with name, slug, and description.',
    parameters: {
      name: { type: 'string', required: true },
      slug: { type: 'string' },
      description: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'list_tags',
    execution_mode: 'legacy',
    display_name: 'List WordPress Tags',
    description: 'List post tags from the connected WordPress site.',
    parameters: { page: { type: 'number' }, per_page: { type: 'number' }, search: { type: 'string' } },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'create_tag',
    execution_mode: 'legacy',
    display_name: 'Create WordPress Tag',
    description: 'Create a WordPress post tag with name, slug, and description.',
    parameters: {
      name: { type: 'string', required: true },
      slug: { type: 'string' },
      description: { type: 'string' },
    },
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'wordpress',
    action_slug: 'get_site_info',
    execution_mode: 'legacy',
    display_name: 'Get WordPress Site Info',
    description:
      'Get metadata for the connected WordPress site, including name, description, URL, and REST API details when available.',
    parameters: {},
    examples: [],
    metadata: {},
    domains: [],
  }
]
