/**
 * The 6 fictional Foundry Creative clients.
 *
 * Filled in Wave 2 by the same subagent that authors agency.ts + team.ts so
 * voice + naming patterns stay consistent. Anchors slugs (acme/beta/gamma/
 * delta/epsilon/zeta) are stable; everything downstream keys off them.
 */
import type { ClientPersona } from './_types'
import { dateInWeek } from './timeline'

export const CLIENTS: readonly ClientPersona[] = [
  {
    slug: 'acme',
    name: 'Plinthworks',
    vertical: 'saas',
    voice: {
      tone: ['pragmatic', 'engineer-direct', 'low-ego', 'specific', 'wry'],
      keywords: [
        'workflow',
        'pipeline',
        'incident',
        'on-call',
        'self-serve',
        'PR',
        'shipped',
        'staging',
        'rollback',
        'observability',
        'latency',
        'edge case',
        'docs',
        'opt-in',
        'API',
      ],
      avoid: [
        'world-class',
        'best-in-class',
        'enterprise-grade',
        'seamless',
        'unleash',
        'empower',
        'revolutionary',
      ],
    },
    namingPattern: 'Plinthworks — {{kind}} v{{n}}',
    brand: {
      primary: '#0F1B2D',
      secondary: '#E6E9EE',
      accent: '#3B82F6',
    },
    onboardedAt: dateInWeek(1, 2, 14, 0),
    retainerScope:
      "Foundry owns Plinthworks' positioning, marketing site copy, and the developer-facing top-of-funnel: docs voice, launch posts, and one paid experiment per quarter against the on-call ICP.",
  },
  {
    slug: 'beta',
    name: 'Saltline & Co',
    vertical: 'dtc',
    voice: {
      tone: ['sensory', 'unhurried', 'lived-in', 'warm', 'evocative'],
      keywords: [
        'pantry',
        'kitchen counter',
        'small batch',
        'salt-cured',
        'weekday dinner',
        'glassware',
        'flicker',
        'low light',
        'hand-tied',
        'slow morning',
        'olive oil',
        'linen',
        'shoulder season',
        'shared table',
        'crumb',
      ],
      avoid: ['curated', 'artisanal', 'luxurious', 'indulge', 'elevate', 'experience', 'lifestyle'],
    },
    namingPattern: 'Saltline — {{kind}} v{{n}}',
    brand: {
      primary: '#2C2A26',
      secondary: '#EFE7D8',
      accent: '#B8623F',
    },
    onboardedAt: dateInWeek(1, 4, 11, 0),
    retainerScope:
      'End-to-end brand voice, photography direction, and lifecycle copy across email + paid social. Foundry runs the Q4 launch calendar and one new product story per month.',
  },
  {
    slug: 'gamma',
    name: 'Helmsmark',
    vertical: 'fintech',
    voice: {
      tone: ['precise', 'sober', 'plainspoken', 'trust-coded', 'unflashy'],
      keywords: [
        'reconciliation',
        'cash position',
        'runway',
        'controls',
        'audit trail',
        'sub-ledger',
        'wire',
        'underwriting',
        'compliance',
        'monthly close',
        'CFO',
        'controller',
        'SOC 2',
        'reporting line',
        'variance',
      ],
      avoid: [
        'disrupting',
        'reimagining',
        'frictionless',
        'next-gen',
        'cutting-edge',
        'magical',
        'effortless',
      ],
    },
    namingPattern: 'Helmsmark — {{kind}} v{{n}}',
    brand: {
      primary: '#0B2A3F',
      secondary: '#F4F1EA',
      accent: '#1D7A6B',
    },
    onboardedAt: dateInWeek(6, 2, 14, 0),
    retainerScope:
      'Repositioning Helmsmark from "small-business banking app" to a controllers-and-CFO product. Foundry owns the new site, the case-study program, and the post-Series-A launch arc.',
  },
  {
    slug: 'delta',
    name: 'Cloverkin Health',
    vertical: 'healthtech',
    voice: {
      tone: ['warm', 'clinical', 'careful', 'human-first', 'plainspoken'],
      keywords: [
        'patient',
        'visit',
        'care plan',
        'follow-up',
        'in-network',
        'consent',
        'record',
        'PCP',
        'navigator',
        'member',
        'eligibility',
        'symptom check',
        'after-hours',
        'continuity',
        'family',
      ],
      avoid: [
        'revolutionary',
        'disruptive',
        'consumer',
        'magical',
        'frictionless',
        'unlock',
        'wellness journey',
      ],
    },
    namingPattern: 'Cloverkin — {{kind}} v{{n}}',
    brand: {
      primary: '#1F3B2D',
      secondary: '#F2EFE6',
      accent: '#D8A37C',
    },
    onboardedAt: dateInWeek(6, 3, 10, 0),
    retainerScope:
      "Brand system, member-facing copy, and the new-patient onboarding sequence for Cloverkin's clinic + virtual care launch in three Northeast metros.",
  },
  {
    slug: 'epsilon',
    name: 'Throughput Group',
    vertical: 'b2b-services',
    voice: {
      tone: ['operator-direct', 'P&L-fluent', 'no-fluff', 'confident', 'measured'],
      keywords: [
        'gross margin',
        'utilization',
        'bench',
        'SOW',
        'change order',
        'account expansion',
        'gross-to-net',
        'pipeline coverage',
        'ramp',
        'attrition',
        'pod',
        'practice lead',
        'billable',
        'pass-through',
        'renewal',
      ],
      avoid: [
        'thought leadership',
        'transform your business',
        'unlock value',
        'world-class',
        'partnership-driven',
        'synergy',
      ],
    },
    namingPattern: 'Throughput — {{kind}} v{{n}}',
    brand: {
      primary: '#1A1A1A',
      secondary: '#E8E5DE',
      accent: '#C2410C',
    },
    onboardedAt: dateInWeek(10, 1, 14, 0),
    retainerScope:
      "Repackage Throughput's six service lines into a clear hierarchy, rewrite the proposal kit, and stand up an outbound program targeting COOs at 200-1000 person services firms.",
  },
  {
    slug: 'zeta',
    name: 'Almanac Learning',
    vertical: 'education',
    voice: {
      tone: ['curious', 'generous', 'plain', 'unpatronizing', 'specific'],
      keywords: [
        'cohort',
        'syllabus',
        'office hours',
        'learner',
        'practice',
        'mentor',
        'feedback',
        'rubric',
        'project',
        'reading list',
        'transcript',
        'live session',
        'Sunday review',
        'study group',
        'first principles',
      ],
      avoid: [
        'gamified',
        'bite-sized',
        'unlock your potential',
        'revolutionize learning',
        'edutainment',
        'next-gen learner',
        'transformative',
      ],
    },
    namingPattern: 'Almanac — {{kind}} v{{n}}',
    brand: {
      primary: '#1F2937',
      secondary: '#F8F4EB',
      accent: '#9F7AEA',
    },
    onboardedAt: dateInWeek(10, 4, 10, 0),
    retainerScope:
      "Brand voice, course-page copy system, and lifecycle nurture for Almanac's adult-learner cohorts in writing, product, and applied AI — including the public reading list as an inbound asset.",
  },
]
