/**
 * Customer-brain anchor content.
 *
 * Wave 3 target: 18 contacts (8 primary + 10 secondary across the 6
 * clients), ~85 anchor memories tagged with contact_slug + speaker, 7
 * avatar narratives clustering contacts. P3b1 expands memories to ~350,
 * builds ns_belief_patterns + ns_perspectives from clusters, and inserts
 * customer_avatars rows. P7.5c derives marketing `avatars` from these.
 *
 * Authoring rules (Wave 3, Subagent B):
 *   - Every `firstSeenAt` / `capturedAt` / `emergedAt` uses `dateInWeek(...)`.
 *   - `firstSeenAt` aligns to each client's `onboardedAt` (acme/beta Week 1,
 *     gamma/delta Week 6, epsilon/zeta Week 10) + 0-3 days.
 *   - Quote memories: `speaker` = contact.displayName. Pure observations:
 *     `speaker` = the Foundry person who took the note (Garry / Nico / Maya /
 *     Sara / Casey / Leo / Riley).
 *   - Voice tracks AGENCY.voice + each client's voice keywords from
 *     content/clients.ts. No "world-class", no "we believe", no fluff.
 *   - Tags pull from the vocabulary the plan locks: client slug + at least one
 *     of pain-point / pricing / competitor-mention / decision-trigger /
 *     objection / success-marker / expansion-signal / risk-signal.
 */
import type { AvatarNarrative, ContactPersona, MemoryAnchor } from './_types'
import { dateInWeek } from './timeline'

// ─── CONTACTS (18 = 8 primary + 10 secondary) ──────────────────────────

export const CONTACTS: readonly ContactPersona[] = [
  // ─── Plinthworks (acme, SaaS) — 1 primary + 2 secondary ─────────────
  {
    slug: 'plinthworks-platform-lead',
    displayName: 'Devi Ramanathan',
    email: 'devi@plinthworks.dev',
    company: 'Plinthworks',
    title: 'Head of Platform',
    tier: 'primary',
    clientSlug: 'acme',
    firstSeenAt: dateInWeek(1, 2, 14, 0),
    contactType: 'customer',
  },
  {
    slug: 'plinthworks-eng-manager',
    displayName: 'Marcus Holloway',
    email: 'marcus@plinthworks.dev',
    company: 'Plinthworks',
    title: 'Engineering Manager, Core Platform',
    tier: 'secondary',
    clientSlug: 'acme',
    firstSeenAt: dateInWeek(1, 3, 10, 30),
    contactType: 'customer',
  },
  {
    slug: 'plinthworks-devrel',
    displayName: 'Priya Chen',
    email: 'priya@plinthworks.dev',
    company: 'Plinthworks',
    title: 'Developer Relations Lead',
    tier: 'secondary',
    clientSlug: 'acme',
    firstSeenAt: dateInWeek(1, 4, 9, 0),
    contactType: 'customer',
  },

  // ─── Saltline & Co (beta, DTC) — 2 primary + 1 secondary ────────────
  {
    slug: 'saltline-founder',
    displayName: 'Eliza Marchetti',
    email: 'eliza@saltlineco.com',
    company: 'Saltline & Co',
    title: 'Founder & Creative Director',
    tier: 'primary',
    clientSlug: 'beta',
    firstSeenAt: dateInWeek(1, 4, 11, 0),
    contactType: 'customer',
  },
  {
    slug: 'saltline-brand-lead',
    displayName: 'June Kowalski',
    email: 'june@saltlineco.com',
    company: 'Saltline & Co',
    title: 'Head of Brand & Story',
    tier: 'primary',
    clientSlug: 'beta',
    firstSeenAt: dateInWeek(1, 5, 9, 30),
    contactType: 'customer',
  },
  {
    slug: 'saltline-ops-lead',
    displayName: 'Theo Nakashima',
    email: 'theo@saltlineco.com',
    company: 'Saltline & Co',
    title: 'Director of Operations',
    tier: 'secondary',
    clientSlug: 'beta',
    firstSeenAt: dateInWeek(1, 6, 14, 0),
    contactType: 'customer',
  },

  // ─── Helmsmark (gamma, fintech) — 2 primary + 1 secondary ───────────
  {
    slug: 'helmsmark-marketing-head',
    displayName: 'Adaeze Okonkwo',
    email: 'adaeze@helmsmark.io',
    company: 'Helmsmark',
    title: 'Head of Marketing',
    tier: 'primary',
    clientSlug: 'gamma',
    firstSeenAt: dateInWeek(6, 2, 14, 0),
    contactType: 'customer',
  },
  {
    slug: 'helmsmark-cfo',
    displayName: 'Wendell Brockman',
    email: 'wendell@helmsmark.io',
    company: 'Helmsmark',
    title: 'Chief Financial Officer',
    tier: 'primary',
    clientSlug: 'gamma',
    firstSeenAt: dateInWeek(6, 2, 15, 30),
    contactType: 'customer',
  },
  {
    slug: 'helmsmark-controller',
    displayName: 'Hana Sato',
    email: 'hana@helmsmark.io',
    company: 'Helmsmark',
    title: 'Controller',
    tier: 'secondary',
    clientSlug: 'gamma',
    firstSeenAt: dateInWeek(6, 4, 10, 0),
    contactType: 'customer',
  },

  // ─── Cloverkin Health (delta, healthtech) — 1 primary + 2 secondary ─
  {
    slug: 'cloverkin-founder',
    displayName: 'Dr. Marisol Vega',
    email: 'marisol@cloverkinhealth.com',
    company: 'Cloverkin Health',
    title: 'Founder & Medical Director',
    tier: 'primary',
    clientSlug: 'delta',
    firstSeenAt: dateInWeek(6, 3, 10, 0),
    contactType: 'customer',
  },
  {
    slug: 'cloverkin-clinical-head',
    displayName: 'Dr. James Ouedraogo',
    email: 'james@cloverkinhealth.com',
    company: 'Cloverkin Health',
    title: 'Head of Clinical Operations',
    tier: 'secondary',
    clientSlug: 'delta',
    firstSeenAt: dateInWeek(6, 4, 9, 0),
    contactType: 'customer',
  },
  {
    slug: 'cloverkin-ops-lead',
    displayName: 'Rachel Pham',
    email: 'rachel@cloverkinhealth.com',
    company: 'Cloverkin Health',
    title: 'Director of Patient Operations',
    tier: 'secondary',
    clientSlug: 'delta',
    firstSeenAt: dateInWeek(6, 5, 11, 30),
    contactType: 'customer',
  },

  // ─── Throughput Group (epsilon, B2B services) — 1 primary + 2 secondary ─
  {
    slug: 'throughput-managing-partner',
    displayName: 'Dominic Ferraro',
    email: 'dominic@throughputgroup.co',
    company: 'Throughput Group',
    title: 'Managing Partner',
    tier: 'primary',
    clientSlug: 'epsilon',
    firstSeenAt: dateInWeek(10, 1, 14, 0),
    contactType: 'customer',
  },
  {
    slug: 'throughput-bizdev-head',
    displayName: 'Yuki Tanaka',
    email: 'yuki@throughputgroup.co',
    company: 'Throughput Group',
    title: 'Head of Business Development',
    tier: 'secondary',
    clientSlug: 'epsilon',
    firstSeenAt: dateInWeek(10, 2, 10, 30),
    contactType: 'customer',
  },
  {
    slug: 'throughput-coo',
    displayName: 'Aliyah Whitfield',
    email: 'aliyah@throughputgroup.co',
    company: 'Throughput Group',
    title: 'Chief Operating Officer',
    tier: 'secondary',
    clientSlug: 'epsilon',
    firstSeenAt: dateInWeek(10, 3, 9, 0),
    contactType: 'customer',
  },

  // ─── Almanac Learning (zeta, education) — 1 primary + 2 secondary ───
  {
    slug: 'almanac-founder',
    displayName: 'Tomás Reinhardt',
    email: 'tomas@almanaclearning.org',
    company: 'Almanac Learning',
    title: 'Founder & Curriculum Lead',
    tier: 'primary',
    clientSlug: 'zeta',
    firstSeenAt: dateInWeek(10, 4, 10, 0),
    contactType: 'customer',
  },
  {
    slug: 'almanac-programs-head',
    displayName: 'Imani Greer',
    email: 'imani@almanaclearning.org',
    company: 'Almanac Learning',
    title: 'Head of Programs',
    tier: 'secondary',
    clientSlug: 'zeta',
    firstSeenAt: dateInWeek(10, 5, 11, 0),
    contactType: 'customer',
  },
  {
    slug: 'almanac-instructor-lead',
    displayName: 'Sebastian Wu',
    email: 'sebastian@almanaclearning.org',
    company: 'Almanac Learning',
    title: 'Lead Instructor & Mentor Coordinator',
    tier: 'secondary',
    clientSlug: 'zeta',
    firstSeenAt: dateInWeek(10, 6, 9, 30),
    contactType: 'customer',
  },
]

// ─── MEMORIES (85 total — 64 across 8 primaries + 21 across 10 secondaries) ─

export const CUSTOMER_BRAIN_MEMORIES: readonly MemoryAnchor[] = [
  // ─── Plinthworks — Devi Ramanathan (primary, 8) ─────────────────────
  {
    slug: 'cm-plinthworks-platform-01',
    content:
      "Devi said 'observability' six times in the kickoff. Most prospects say it once and mean nothing by it. Devi means the dashboards she watches at 2am when a customer pings the on-call channel. Note this in the customer brain — she is the buyer who would not let us write 'observability' as marketing language without earning it.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Plinthworks kickoff call — Wed',
    speaker: 'Garry Tan',
    capturedAt: dateInWeek(1, 2, 14, 45),
    significance: 0.78,
    confidence: 0.9,
    tags: ['acme', 'pain-point', 'decision-trigger'],
    contactSlug: 'plinthworks-platform-lead',
  },
  {
    slug: 'cm-plinthworks-platform-02',
    content:
      "Quote, verbatim: 'I do not need another landing page that explains what an API is. I need one that explains why ours does not page the on-call.' Filed as the positioning anchor for the Plinthworks homepage rewrite — the kill criterion for every hero variant.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Plinthworks positioning workshop — session 1',
    speaker: 'Devi Ramanathan',
    capturedAt: dateInWeek(1, 4, 11, 30),
    significance: 0.92,
    confidence: 0.95,
    tags: ['acme', 'decision-trigger', 'pain-point'],
    contactSlug: 'plinthworks-platform-lead',
    emotion: { label: 'firm', valence: 0.3, intensity: 0.8 },
  },
  {
    slug: 'cm-plinthworks-platform-03',
    content:
      "On the ICP: 'We are not selling to indie devs anymore. The buyer is the head of platform at a Series B who has been paged twice this quarter for our category.' Devi corrected me twice on this in the same call — she will not let the funnel keep speaking to the previous buyer.",
    memoryType: 'fact',
    sourceType: 'meeting',
    sourceTitle: 'Plinthworks ICP review — Mon',
    speaker: 'Devi Ramanathan',
    capturedAt: dateInWeek(2, 1, 10, 0),
    significance: 0.88,
    confidence: 0.92,
    tags: ['acme', 'decision-trigger', 'pain-point'],
    contactSlug: 'plinthworks-platform-lead',
  },
  {
    slug: 'cm-plinthworks-platform-04',
    content:
      "Devi will not put a single number on the marketing site she cannot defend in a customer call. She killed three SOC 2 stats from the about page herself — 'we have three customers who passed an audit, that is not a stat'. Trust-discipline at the founder level is rare; flag this as a Foundry-shaped behavior for the avatar.",
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#plinthworks-brand — Tue thread',
    speaker: 'Maya',
    capturedAt: dateInWeek(4, 1, 16, 15),
    significance: 0.76,
    confidence: 0.88,
    tags: ['acme', 'objection', 'risk-signal'],
    contactSlug: 'plinthworks-platform-lead',
  },
  {
    slug: 'cm-plinthworks-platform-05',
    content:
      'From the Q1 retro: \'I do not want to be the company that buys ads for the word "observability". I want to be the company you find because the README is the cleanest one you read this month.\' That is the brief for the docs voice and the org content arc — captured verbatim.',
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Plinthworks Q1 retro',
    speaker: 'Devi Ramanathan',
    capturedAt: dateInWeek(6, 4, 15, 0),
    significance: 0.89,
    confidence: 0.93,
    tags: ['acme', 'decision-trigger', 'expansion-signal'],
    contactSlug: 'plinthworks-platform-lead',
  },
  {
    slug: 'cm-plinthworks-platform-06',
    content:
      "Devi pushed back on Leo's paid test plan: 'Let me see organic move first. If the post does not work without spend, the ad will not work either.' That is a Foundry-shaped operator — she pre-empted the exact pattern company-cortex object-position-before-paid encodes.",
    memoryType: 'insight',
    sourceType: 'channel',
    sourceTitle: '#plinthworks-growth — Thu',
    speaker: 'Leo',
    capturedAt: dateInWeek(8, 3, 11, 45),
    significance: 0.82,
    confidence: 0.9,
    tags: ['acme', 'success-marker', 'decision-trigger'],
    contactSlug: 'plinthworks-platform-lead',
  },
  {
    slug: 'cm-plinthworks-platform-07',
    content:
      'Devi has a rule that no marketing post ships until two engineers on her team have nodded at the technical claim. Took us three weeks to learn the rule by accident; Maya now routes copy through her senior on-call before staging. The brand-engineering loop is structural at Plinthworks, not political.',
    memoryType: 'fact',
    sourceType: 'channel',
    sourceTitle: '#plinthworks-brand — Wed',
    speaker: 'Maya',
    capturedAt: dateInWeek(9, 2, 14, 30),
    significance: 0.78,
    confidence: 0.92,
    tags: ['acme', 'pain-point', 'risk-signal'],
    contactSlug: 'plinthworks-platform-lead',
  },
  {
    slug: 'cm-plinthworks-platform-08',
    content:
      "Devi at the rebrand kickoff: 'I am not paying for a logo. I am paying for the fact that our hiring page stops sounding like a startup that has not figured out who it is yet.' Filed as the brief for the entire Q2 rebrand — the success metric is recruiting funnel quality, not the mark.",
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Plinthworks rebrand kickoff',
    speaker: 'Devi Ramanathan',
    capturedAt: dateInWeek(11, 1, 10, 0),
    significance: 0.9,
    confidence: 0.93,
    tags: ['acme', 'expansion-signal', 'decision-trigger'],
    contactSlug: 'plinthworks-platform-lead',
    emotion: { label: 'decisive', valence: 0.5, intensity: 0.75 },
  },

  // ─── Plinthworks — Marcus Holloway (secondary, 2) ───────────────────
  {
    slug: 'cm-plinthworks-eng-01',
    content:
      "Marcus quietly closed the Slack thread about 'thought-leadership posts' with one line: 'If we are writing posts our own engineers would not read, we are wasting Devi's time.' Devi reacted with a single check-mark emoji. That was the editorial policy decision — undocumented, but binding.",
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#plinthworks-brand — Tue',
    speaker: 'Sara',
    capturedAt: dateInWeek(5, 1, 13, 20),
    significance: 0.7,
    confidence: 0.85,
    tags: ['acme', 'decision-trigger', 'objection'],
    contactSlug: 'plinthworks-eng-manager',
  },
  {
    slug: 'cm-plinthworks-eng-02',
    content:
      'Marcus showed up to the docs voice review without an agenda and walked us through the three GitHub issues that landed in his team that month because of unclear docs. He treats docs as a product surface, not a marketing surface — the docs voice doc should mirror his framing back to him.',
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Plinthworks docs voice review',
    speaker: 'Maya',
    capturedAt: dateInWeek(9, 3, 10, 30),
    significance: 0.72,
    confidence: 0.88,
    tags: ['acme', 'pain-point', 'expansion-signal'],
    contactSlug: 'plinthworks-eng-manager',
  },

  // ─── Plinthworks — Priya Chen (secondary, 2) ────────────────────────
  {
    slug: 'cm-plinthworks-devrel-01',
    content:
      "Priya keeps pulling the conversation back to 'engagement on the launch post' even when Devi is asking about pipeline. The metric she wants to be measured on is reach; the metric Devi wants the brand to move is on-call buyer pipeline. Worth flagging in the customer brain — internal stakeholder misalignment at Plinthworks.",
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#plinthworks-growth — Fri',
    speaker: 'Leo',
    capturedAt: dateInWeek(7, 4, 15, 30),
    significance: 0.65,
    confidence: 0.82,
    tags: ['acme', 'risk-signal', 'objection'],
    contactSlug: 'plinthworks-devrel',
  },
  {
    slug: 'cm-plinthworks-devrel-02',
    content:
      "Priya said it twice on the same call: 'we just need more launch content.' The number she is chasing is reach, not the on-call buyer Devi defined as the ICP. Pattern to track for the disqualified-leads avatar — short-horizon, function-loyal, tactic-first.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Plinthworks growth sync — Wed',
    speaker: 'Priya Chen',
    capturedAt: dateInWeek(10, 2, 11, 0),
    significance: 0.7,
    confidence: 0.85,
    tags: ['acme', 'risk-signal', 'pain-point'],
    contactSlug: 'plinthworks-devrel',
  },

  // ─── Saltline — Eliza Marchetti (primary, 8) ────────────────────────
  {
    slug: 'cm-saltline-founder-01',
    content:
      "Eliza on the first call: 'I would rather miss a launch window than ship a campaign that smells like everyone else's brand.' Said it without flinching, twelve minutes into the kickoff. Filed under: this founder will defend voice over deadline. The retainer scope has to honor that.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Saltline kickoff call — Fri',
    speaker: 'Eliza Marchetti',
    capturedAt: dateInWeek(1, 4, 11, 15),
    significance: 0.92,
    confidence: 0.95,
    tags: ['beta', 'decision-trigger', 'objection'],
    contactSlug: 'saltline-founder',
    emotion: { label: 'protective-of-voice', valence: 0.6, intensity: 0.85 },
  },
  {
    slug: 'cm-saltline-founder-02',
    content:
      "She talks about products the way a chef talks about a dish — 'the new oil is for the second pour, not the salad'. That is the language for the PDP, not 'premium pantry essentials'. Sara has been pulling phrases from Eliza's voice memos into the product copy bank since Week 2.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Saltline product naming session',
    speaker: 'Sara',
    capturedAt: dateInWeek(2, 2, 14, 0),
    significance: 0.82,
    confidence: 0.9,
    tags: ['beta', 'success-marker', 'decision-trigger'],
    contactSlug: 'saltline-founder',
  },
  {
    slug: 'cm-saltline-founder-03',
    content:
      "Quote: 'Pinterest does not pay our rent. The third email after the welcome does.' Eliza named the lifecycle slot that was leaking revenue before I did. She knows her funnel — most founders in DTC at her stage do not.",
    memoryType: 'fact',
    sourceType: 'meeting',
    sourceTitle: 'Saltline lifecycle audit',
    speaker: 'Eliza Marchetti',
    capturedAt: dateInWeek(3, 1, 10, 30),
    significance: 0.86,
    confidence: 0.92,
    tags: ['beta', 'decision-trigger', 'expansion-signal'],
    contactSlug: 'saltline-founder',
  },
  {
    slug: 'cm-saltline-founder-04',
    content:
      "Eliza killed the influencer line item the moment Leo presented the seven-day cohort. 'They post once, our cohort does not move, we have spent rent on a story we did not own.' No defense, no debate — that decision took ninety seconds. Filed as the spend-discipline anchor.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Saltline media plan review',
    speaker: 'Eliza Marchetti',
    capturedAt: dateInWeek(4, 3, 11, 45),
    significance: 0.88,
    confidence: 0.94,
    tags: ['beta', 'pricing', 'decision-trigger'],
    contactSlug: 'saltline-founder',
    emotion: { label: 'decisive', valence: 0.5, intensity: 0.8 },
  },
  {
    slug: 'cm-saltline-founder-05',
    content:
      'She has a quiet rule that no copy ships until she has read it aloud in her kitchen on a Thursday afternoon. We now send drafts on Thursday morning. The cadence is the only reason approvals are clearing inside a 24-hour window — discovered by accident, locked in by SOP.',
    memoryType: 'observation',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Saltline brand brief',
    speaker: 'Sara',
    capturedAt: dateInWeek(6, 2, 9, 30),
    significance: 0.72,
    confidence: 0.9,
    tags: ['beta', 'pain-point', 'success-marker'],
    contactSlug: 'saltline-founder',
  },
  {
    slug: 'cm-saltline-founder-06',
    content:
      "From the brand book review: 'Our customer is the woman who is annoyed that olive oil is now a personality. We are the brand that takes the personality back out and gives her the bottle.' That is the entire positioning in one sentence — Maya has been quoting it inside the studio for two weeks.",
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Saltline brand book review v3',
    speaker: 'Eliza Marchetti',
    capturedAt: dateInWeek(7, 3, 13, 0),
    significance: 0.94,
    confidence: 0.95,
    tags: ['beta', 'competitor-mention', 'decision-trigger'],
    contactSlug: 'saltline-founder',
  },
  {
    slug: 'cm-saltline-founder-07',
    content:
      'Eliza will absolutely not let us run paid against the holiday gift guide. \'If our brand has to bid on the word "gift" in December, we did the first ten months wrong.\' This is now the constraint on the Q4 media plan — Leo budgeted accordingly.',
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Saltline Q4 plan review',
    speaker: 'Eliza Marchetti',
    capturedAt: dateInWeek(9, 1, 14, 30),
    significance: 0.85,
    confidence: 0.93,
    tags: ['beta', 'objection', 'decision-trigger'],
    contactSlug: 'saltline-founder',
  },
  {
    slug: 'cm-saltline-founder-08',
    content:
      "Eliza forwarded a competitor's email this morning with one line: 'this is what we are not.' The competitor uses 'curated' four times in the subject line. Added 'curated' to the Saltline avoid-list and to the avatar-level avoid pattern for sensory DTC operators.",
    memoryType: 'observation',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Saltline competitor scan',
    speaker: 'Eliza Marchetti',
    capturedAt: dateInWeek(11, 2, 9, 0),
    significance: 0.78,
    confidence: 0.92,
    tags: ['beta', 'competitor-mention', 'risk-signal'],
    contactSlug: 'saltline-founder',
  },

  // ─── Saltline — June Kowalski (primary, 8) ──────────────────────────
  {
    slug: 'cm-saltline-brand-01',
    content:
      "June in the first working session: 'I am tired of arguing with our agency about whether a recipe card is a brand asset. It is the whole brand. Tell me you understand that.' Sara and I both nodded a little too hard. The retainer was sold in that exchange, not in the proposal.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Saltline brand intensive — Mon',
    speaker: 'June Kowalski',
    capturedAt: dateInWeek(2, 1, 10, 0),
    significance: 0.9,
    confidence: 0.94,
    tags: ['beta', 'decision-trigger', 'pain-point'],
    contactSlug: 'saltline-brand-lead',
  },
  {
    slug: 'cm-saltline-brand-02',
    content:
      "She has the entire content calendar mapped to seasonal cooking moments, not product launches. 'Shoulder season is the calendar. Black Friday is not.' That framing rewrote the Q4 plan and gave Leo the air cover to kill the BFCM creative sprint.",
    memoryType: 'observation',
    sourceType: 'doc',
    sourceTitle: 'Saltline content calendar v2',
    speaker: 'June Kowalski',
    capturedAt: dateInWeek(3, 2, 14, 30),
    significance: 0.82,
    confidence: 0.9,
    tags: ['beta', 'decision-trigger', 'success-marker'],
    contactSlug: 'saltline-brand-lead',
  },
  {
    slug: 'cm-saltline-brand-03',
    content:
      "June rewrote three of Sara's headlines on Friday and her version was always shorter. She is the kind of brand lead who hates 'storytelling' as a verb and ships story as a noun. The voice doc should cite her edits, not a style guide.",
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#saltline-brand — Fri',
    speaker: 'Sara',
    capturedAt: dateInWeek(4, 4, 17, 0),
    significance: 0.78,
    confidence: 0.92,
    tags: ['beta', 'success-marker', 'expansion-signal'],
    contactSlug: 'saltline-brand-lead',
  },
  {
    slug: 'cm-saltline-brand-04',
    content:
      "Quote: 'If the email could be sent by Williams Sonoma, it is not ours. Write it again with less polish.' Going on the wall in the copy room — that single line resolved a forty-minute argument about whether the welcome series was 'too quiet'.",
    memoryType: 'reflection',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Saltline welcome series v4',
    speaker: 'June Kowalski',
    capturedAt: dateInWeek(5, 3, 9, 45),
    significance: 0.85,
    confidence: 0.93,
    tags: ['beta', 'competitor-mention', 'decision-trigger'],
    contactSlug: 'saltline-brand-lead',
  },
  {
    slug: 'cm-saltline-brand-05',
    content:
      "June killed a beautiful editorial photo because 'the linen is staged, the kitchen is not'. Casey learned more in that fifteen-minute review than from any moodboard. We now shoot in real kitchens with real morning light — locked into the photography direction.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Saltline photo direction review',
    speaker: 'June Kowalski',
    capturedAt: dateInWeek(7, 2, 13, 30),
    significance: 0.84,
    confidence: 0.92,
    tags: ['beta', 'decision-trigger', 'success-marker'],
    contactSlug: 'saltline-brand-lead',
  },
  {
    slug: 'cm-saltline-brand-06',
    content:
      "June asked, point-blank: 'Why do all the other DTC brands sound like a wellness app now?' Then she answered herself: 'because they hired the same five people'. Useful framing for the positioning doc and for the dtc-operators-with-taste avatar narrative.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Saltline positioning sync',
    speaker: 'June Kowalski',
    capturedAt: dateInWeek(8, 1, 11, 0),
    significance: 0.86,
    confidence: 0.9,
    tags: ['beta', 'competitor-mention', 'pain-point'],
    contactSlug: 'saltline-brand-lead',
  },
  {
    slug: 'cm-saltline-brand-07',
    content:
      "On the loyalty program: 'I do not want a tier system. I want the third order to feel like the second one, just warmer.' She is right — the retention copy we had was lazy. We rewrote the post-purchase series the same week.",
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Saltline retention strategy session',
    speaker: 'June Kowalski',
    capturedAt: dateInWeek(10, 2, 15, 0),
    significance: 0.8,
    confidence: 0.9,
    tags: ['beta', 'decision-trigger', 'expansion-signal'],
    contactSlug: 'saltline-brand-lead',
  },
  {
    slug: 'cm-saltline-brand-08',
    content:
      'June reads every customer support ticket on Monday morning and re-uses the actual customer phrasing in Wednesday emails. The voice document writes itself if you watch what she does. Sara has started shadowing the ticket review as part of the weekly cadence.',
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#saltline-brand — Mon',
    speaker: 'Sara',
    capturedAt: dateInWeek(12, 0, 9, 30),
    significance: 0.78,
    confidence: 0.93,
    tags: ['beta', 'success-marker', 'expansion-signal'],
    contactSlug: 'saltline-brand-lead',
  },

  // ─── Saltline — Theo Nakashima (secondary, 2) ───────────────────────
  {
    slug: 'cm-saltline-ops-01',
    content:
      "Theo cares about one thing in every brand conversation: whether the warehouse can pack what marketing is promising in week three. He killed the 'kitchen kit' bundle SKU in one sentence — 'three SKUs, three pickers, no.' Operations as a brand-safety function.",
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#saltline-ops — Tue',
    speaker: 'Theo Nakashima',
    capturedAt: dateInWeek(5, 1, 16, 0),
    significance: 0.7,
    confidence: 0.88,
    tags: ['beta', 'objection', 'risk-signal'],
    contactSlug: 'saltline-ops-lead',
  },
  {
    slug: 'cm-saltline-ops-02',
    content:
      "Theo flagged the launch date conflict before anyone else saw it: 'the email goes out Tuesday, the new bottle clears customs Wednesday'. The cadence between brand and ops is one of the reasons Saltline ships on time — Foundry should build a launch-date-check step into the SOP.",
    memoryType: 'fact',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Saltline Q4 launch dates',
    speaker: 'Theo Nakashima',
    capturedAt: dateInWeek(9, 2, 10, 15),
    significance: 0.74,
    confidence: 0.92,
    tags: ['beta', 'risk-signal', 'success-marker'],
    contactSlug: 'saltline-ops-lead',
  },

  // ─── Helmsmark — Adaeze Okonkwo (primary, 8) ────────────────────────
  {
    slug: 'cm-helmsmark-mkt-01',
    content:
      "Adaeze opened the kickoff with: 'Our site still talks to bookkeepers. Our actual buyer is the controller at a Series B fintech. We have been writing copy to a customer we no longer want.' That is the entire repositioning brief in one paragraph.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark kickoff call — Wed',
    speaker: 'Adaeze Okonkwo',
    capturedAt: dateInWeek(6, 2, 14, 15),
    significance: 0.94,
    confidence: 0.95,
    tags: ['gamma', 'decision-trigger', 'pain-point'],
    contactSlug: 'helmsmark-marketing-head',
  },
  {
    slug: 'cm-helmsmark-mkt-02',
    content:
      "Adaeze knows her funnel cold. Quoted MQL-to-controller-meeting conversion off the top of her head — 3.2%, said it was 'embarrassing for the category'. Confidence plus exact numbers in the first meeting equals Foundry-shaped buyer. Note for the fintech-marketing-controllers avatar.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark kickoff call — Wed',
    speaker: 'Garry Tan',
    capturedAt: dateInWeek(6, 2, 14, 45),
    significance: 0.84,
    confidence: 0.92,
    tags: ['gamma', 'success-marker', 'decision-trigger'],
    contactSlug: 'helmsmark-marketing-head',
  },
  {
    slug: 'cm-helmsmark-mkt-03',
    content:
      "Quote: 'I do not want a brand refresh. I want our homepage to stop apologizing for being a finance tool.' That is the positioning brief in one sentence — Maya has been quoting it back in every Helmsmark working session since.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark positioning intensive',
    speaker: 'Adaeze Okonkwo',
    capturedAt: dateInWeek(7, 1, 10, 30),
    significance: 0.92,
    confidence: 0.94,
    tags: ['gamma', 'decision-trigger', 'pain-point'],
    contactSlug: 'helmsmark-marketing-head',
  },
  {
    slug: 'cm-helmsmark-mkt-04',
    content:
      "Adaeze pushed back on Maya's first positioning draft: 'controllers do not buy on aspiration. They buy because the close took eleven days last quarter and they want it to take six.' We rewrote the value prop after that call — the number became the headline anchor.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark positioning review v1',
    speaker: 'Adaeze Okonkwo',
    capturedAt: dateInWeek(8, 3, 13, 0),
    significance: 0.88,
    confidence: 0.93,
    tags: ['gamma', 'decision-trigger', 'objection'],
    contactSlug: 'helmsmark-marketing-head',
  },
  {
    slug: 'cm-helmsmark-mkt-05',
    content:
      'Adaeze has standing 1:1s with three friendly customer CFOs. She has done more customer research in a month than most marketing leads do in a year. The case-study program should plug straight into that cadence — she already has access we would otherwise have to earn.',
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#helmsmark-brand — Mon',
    speaker: 'Maya',
    capturedAt: dateInWeek(9, 0, 15, 30),
    significance: 0.8,
    confidence: 0.9,
    tags: ['gamma', 'success-marker', 'expansion-signal'],
    contactSlug: 'helmsmark-marketing-head',
  },
  {
    slug: 'cm-helmsmark-mkt-06',
    content:
      "On the case-study program: 'I do not need ten testimonials. I need three that another CFO will believe.' She cut our planned cadence in half — correctly. Three named CFO case studies, not ten unnamed quotes. The case study count is a quality metric, not a volume one.",
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark case-study planning',
    speaker: 'Adaeze Okonkwo',
    capturedAt: dateInWeek(10, 1, 11, 0),
    significance: 0.84,
    confidence: 0.92,
    tags: ['gamma', 'decision-trigger', 'pricing'],
    contactSlug: 'helmsmark-marketing-head',
  },
  {
    slug: 'cm-helmsmark-mkt-07',
    content:
      "Adaeze called out our own draft: 'this paragraph says nothing a controller would underline.' She is the customer for the customer copy — rare and useful. Sara now sends drafts to her with the line 'circle what a controller would underline' as the only ask.",
    memoryType: 'insight',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Helmsmark controller page v2',
    speaker: 'Adaeze Okonkwo',
    capturedAt: dateInWeek(11, 3, 9, 15),
    significance: 0.82,
    confidence: 0.93,
    tags: ['gamma', 'objection', 'success-marker'],
    contactSlug: 'helmsmark-marketing-head',
  },
  {
    slug: 'cm-helmsmark-mkt-08',
    content:
      'Adaeze sent Wendell into the brand approval meeting unprompted. The CFO defended the new positioning to his board the next week. Marketing-finance alignment at Helmsmark is structural, not political — that is rare in fintech and central to the avatar.',
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#helmsmark-brand — Thu',
    speaker: 'Riley',
    capturedAt: dateInWeek(12, 3, 16, 0),
    significance: 0.86,
    confidence: 0.92,
    tags: ['gamma', 'success-marker', 'expansion-signal'],
    contactSlug: 'helmsmark-marketing-head',
  },

  // ─── Helmsmark — Wendell Brockman (primary, 8) ──────────────────────
  {
    slug: 'cm-helmsmark-cfo-01',
    content:
      "Wendell on the first joint call: 'I am here because the wrong website costs us six months of pipeline. That is a number I can defend on my board, which is why I am paying attention.' Most CFOs do not sit in on the brand call. He did — every week since.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark CFO sync — slide 12',
    speaker: 'Wendell Brockman',
    capturedAt: dateInWeek(6, 2, 15, 45),
    significance: 0.94,
    confidence: 0.95,
    tags: ['gamma', 'decision-trigger', 'expansion-signal'],
    contactSlug: 'helmsmark-cfo',
  },
  {
    slug: 'cm-helmsmark-cfo-02',
    content:
      "He said the word 'controller' six times in 40 minutes. They are not selling to SMB anymore even if their site still says so. The word frequency is the buyer-intent signal — Wendell is the second-loudest voice in the room on the repositioning, after Adaeze.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark CFO sync — slide 12',
    speaker: 'Garry Tan',
    capturedAt: dateInWeek(6, 2, 15, 50),
    significance: 0.88,
    confidence: 0.92,
    tags: ['gamma', 'decision-trigger', 'pain-point'],
    contactSlug: 'helmsmark-cfo',
  },
  {
    slug: 'cm-helmsmark-cfo-03',
    content:
      "Quote: 'If your headline survives a Bloomberg headline cycle, it is ours. If it sounds like a Series A press release, it is not.' Filed as the headline-survival rule on the Helmsmark site — Sara cites it in every copy review.",
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark hero variants review',
    speaker: 'Wendell Brockman',
    capturedAt: dateInWeek(7, 4, 14, 30),
    significance: 0.86,
    confidence: 0.93,
    tags: ['gamma', 'competitor-mention', 'decision-trigger'],
    contactSlug: 'helmsmark-cfo',
  },
  {
    slug: 'cm-helmsmark-cfo-04',
    content:
      "Wendell killed the 'AI-powered' line in the hero himself. 'No CFO has ever wired more money because something was AI-powered. They wire money because the variance report is shorter.' The line that replaced it cites the variance number — his suggestion.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark site review v2',
    speaker: 'Wendell Brockman',
    capturedAt: dateInWeek(8, 1, 11, 30),
    significance: 0.9,
    confidence: 0.94,
    tags: ['gamma', 'decision-trigger', 'objection'],
    contactSlug: 'helmsmark-cfo',
    emotion: { label: 'firm', valence: 0.4, intensity: 0.85 },
  },
  {
    slug: 'cm-helmsmark-cfo-05',
    content:
      'He treats the marketing site as a sales artifact. Asked us for the conversion rate from controller-page visits to demo-requested before he approved the IA. Numbers-fluent operator — the brand review is a board-prep exercise to him.',
    memoryType: 'fact',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark IA approval',
    speaker: 'Devon',
    capturedAt: dateInWeek(9, 2, 16, 0),
    significance: 0.82,
    confidence: 0.92,
    tags: ['gamma', 'decision-trigger', 'expansion-signal'],
    contactSlug: 'helmsmark-cfo',
  },
  {
    slug: 'cm-helmsmark-cfo-06',
    content:
      "Said in passing: 'I would rather lose the deal than discount the SOW.' That is the kind of operator who will renew. Not said about our retainer — about their own pricing. Wendell runs Helmsmark the same way. Margin discipline in the buyer is correlated with renewal probability.",
    memoryType: 'insight',
    sourceType: 'channel',
    sourceTitle: '#helmsmark-strategy — Tue',
    speaker: 'Wendell Brockman',
    capturedAt: dateInWeek(10, 1, 13, 45),
    significance: 0.92,
    confidence: 0.93,
    tags: ['gamma', 'pricing', 'success-marker', 'expansion-signal'],
    contactSlug: 'helmsmark-cfo',
  },
  {
    slug: 'cm-helmsmark-cfo-07',
    content:
      "Wendell sent the post-launch traffic report to the partner Slack on his own, with one line: 'controller-page time-on-page up 71%, brief working as designed.' He measures brand the way a CFO measures anything — by the number, with no narration.",
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#helmsmark-launch — Mon',
    speaker: 'Riley',
    capturedAt: dateInWeek(12, 0, 8, 30),
    significance: 0.86,
    confidence: 0.94,
    tags: ['gamma', 'success-marker', 'expansion-signal'],
    contactSlug: 'helmsmark-cfo',
    emotion: { label: 'aligned', valence: 0.7, intensity: 0.7 },
  },
  {
    slug: 'cm-helmsmark-cfo-08',
    content:
      "He told the board the brand refresh paid for itself in a single enterprise deal that closed because the prospect's controller forwarded the homepage internally. That is the case study we cannot write but he will tell forever. Renewal-class signal — flag.",
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark board prep — debrief',
    speaker: 'Wendell Brockman',
    capturedAt: dateInWeek(13, 1, 10, 30),
    significance: 0.95,
    confidence: 0.94,
    tags: ['gamma', 'success-marker', 'expansion-signal'],
    contactSlug: 'helmsmark-cfo',
  },

  // ─── Helmsmark — Hana Sato (secondary, 2) ───────────────────────────
  {
    slug: 'cm-helmsmark-controller-01',
    content:
      "Hana joined the controller-page review and corrected one word: 'sub-ledger', not 'general ledger'. The detail unlocked the headline. Subject-matter accuracy is brand accuracy in this category — flag for the keyword bank.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Helmsmark controller page review',
    speaker: 'Sara',
    capturedAt: dateInWeek(8, 3, 11, 0),
    significance: 0.74,
    confidence: 0.93,
    tags: ['gamma', 'decision-trigger', 'success-marker'],
    contactSlug: 'helmsmark-controller',
  },
  {
    slug: 'cm-helmsmark-controller-02',
    content:
      "Hana forwarded the launch email to the controllers' Slack community she runs without being asked. Adaeze said that was worth more than the paid amplification budget. Word-of-mouth inside the buyer persona is the unlock the brand has been earning.",
    memoryType: 'fact',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Helmsmark launch — controller community',
    speaker: 'Adaeze Okonkwo',
    capturedAt: dateInWeek(12, 1, 14, 30),
    significance: 0.82,
    confidence: 0.92,
    tags: ['gamma', 'success-marker', 'expansion-signal'],
    contactSlug: 'helmsmark-controller',
  },

  // ─── Cloverkin — Dr. Marisol Vega (primary, 8) ──────────────────────
  {
    slug: 'cm-cloverkin-founder-01',
    content:
      "Marisol opened the kickoff with: 'Our patients are not consumers. The minute the brand starts treating them that way, the trust we have built in three cities is gone.' Said it the way a doctor says 'do not stop the antibiotic early'. Filed as the trust constraint.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Cloverkin onboarding call',
    speaker: 'Dr. Marisol Vega',
    capturedAt: dateInWeek(6, 3, 10, 15),
    significance: 0.95,
    confidence: 0.96,
    tags: ['delta', 'decision-trigger', 'risk-signal'],
    contactSlug: 'cloverkin-founder',
    emotion: { label: 'protective-of-patient', valence: 0.5, intensity: 0.9 },
  },
  {
    slug: 'cm-cloverkin-founder-02',
    content:
      "Marisol circled back to 'continuity' four times in the first hour. The Cloverkin product is not the app — it is the same care team showing up week three, week six, week twenty. The brand has to make continuity the proof, not the feature list.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Cloverkin onboarding call',
    speaker: 'Maya',
    capturedAt: dateInWeek(6, 3, 11, 0),
    significance: 0.86,
    confidence: 0.93,
    tags: ['delta', 'decision-trigger', 'pain-point'],
    contactSlug: 'cloverkin-founder',
  },
  {
    slug: 'cm-cloverkin-founder-03',
    content:
      "Quote: 'I would rather lose the visit than send a marketing email a patient finds in their inbox the day after a hard appointment.' That is the bar for lifecycle copy here. Sara baked it into the send-window SOP — no marketing sends within 48 hours of any visit.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Cloverkin lifecycle planning',
    speaker: 'Dr. Marisol Vega',
    capturedAt: dateInWeek(7, 2, 14, 0),
    significance: 0.92,
    confidence: 0.95,
    tags: ['delta', 'decision-trigger', 'risk-signal'],
    contactSlug: 'cloverkin-founder',
  },
  {
    slug: 'cm-cloverkin-founder-04',
    content:
      "Marisol vetoes the word 'consumer' on sight. Also: 'wellness journey', 'magical', 'frictionless'. She has the strongest no-words list of any client we have. Added 'partner' to it after her note last week — she dislikes the asymmetry the word implies.",
    memoryType: 'fact',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Cloverkin avoid-list',
    speaker: 'Dr. Marisol Vega',
    capturedAt: dateInWeek(8, 1, 9, 30),
    significance: 0.82,
    confidence: 0.95,
    tags: ['delta', 'objection', 'decision-trigger'],
    contactSlug: 'cloverkin-founder',
  },
  {
    slug: 'cm-cloverkin-founder-05',
    content:
      'She made us sit through three patient-navigator calls before we wrote a single line of onboarding copy. The version we shipped is unrecognizable from draft one. Three calls. Three rewrites. Filed as the SOP for any healthtech retainer — listen before language.',
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Cloverkin patient navigator shadow',
    speaker: 'Sara',
    capturedAt: dateInWeek(9, 4, 13, 0),
    significance: 0.88,
    confidence: 0.93,
    tags: ['delta', 'success-marker', 'decision-trigger'],
    contactSlug: 'cloverkin-founder',
  },
  {
    slug: 'cm-cloverkin-founder-06',
    content:
      "Said on the brand-system review: 'the color of the after-hours line matters more than the color of the logo'. Casey rebuilt the entire UI palette around that sentence — accent color now derived from the after-hours emergency contact pill.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Cloverkin brand system review',
    speaker: 'Dr. Marisol Vega',
    capturedAt: dateInWeek(10, 2, 15, 30),
    significance: 0.85,
    confidence: 0.92,
    tags: ['delta', 'decision-trigger', 'success-marker'],
    contactSlug: 'cloverkin-founder',
  },
  {
    slug: 'cm-cloverkin-founder-07',
    content:
      "Marisol turned down a paid acquisition pilot Leo proposed: 'we do not advertise to anyone we cannot see in a clinic. The minute we do, the brand promise breaks.' That is a position, not a preference. Locked into the Cloverkin growth constraint set.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Cloverkin growth review',
    speaker: 'Dr. Marisol Vega',
    capturedAt: dateInWeek(11, 3, 11, 0),
    significance: 0.9,
    confidence: 0.95,
    tags: ['delta', 'objection', 'risk-signal'],
    contactSlug: 'cloverkin-founder',
    emotion: { label: 'firm', valence: 0.3, intensity: 0.85 },
  },
  {
    slug: 'cm-cloverkin-founder-08',
    content:
      "She forwarded a thank-you note from a member's daughter and said one line: 'this is the marketing'. Filed in the brand book as the patient-voice anchor. The case study is the note, untouched — we are not editing it.",
    memoryType: 'reflection',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Cloverkin member story — Mrs. K',
    speaker: 'Dr. Marisol Vega',
    capturedAt: dateInWeek(12, 2, 16, 30),
    significance: 0.94,
    confidence: 0.95,
    tags: ['delta', 'success-marker', 'expansion-signal'],
    contactSlug: 'cloverkin-founder',
  },

  // ─── Cloverkin — Dr. James Ouedraogo (secondary, 2) ─────────────────
  {
    slug: 'cm-cloverkin-clinical-01',
    content:
      'James reviewed our patient-facing copy and circled four things — three were medical accuracy, one was tone. He is faster at the tone catch than most of our copywriters. Clinical lens trains brand intuition apparently — useful pattern for the healthtech avatar.',
    memoryType: 'observation',
    sourceType: 'doc',
    sourceTitle: 'Cloverkin patient copy review — round 2',
    speaker: 'Sara',
    capturedAt: dateInWeek(8, 4, 14, 0),
    significance: 0.72,
    confidence: 0.9,
    tags: ['delta', 'success-marker', 'decision-trigger'],
    contactSlug: 'cloverkin-clinical-head',
  },
  {
    slug: 'cm-cloverkin-clinical-02',
    content:
      "James said in the eligibility-page review: 'patients read this when they are scared. Cut every word that does not lower the heart rate.' That sentence is now the test in the lifecycle SOP — every send is reviewed against the heart-rate filter.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Cloverkin eligibility page review',
    speaker: 'Dr. James Ouedraogo',
    capturedAt: dateInWeek(10, 0, 10, 30),
    significance: 0.86,
    confidence: 0.94,
    tags: ['delta', 'decision-trigger', 'success-marker'],
    contactSlug: 'cloverkin-clinical-head',
  },

  // ─── Cloverkin — Rachel Pham (secondary, 2) ─────────────────────────
  {
    slug: 'cm-cloverkin-ops-01',
    content:
      "Rachel pulled up the after-hours call volume during a brand-tone debate and ended it: 'the line gets 40% of weekly calls between 8pm and midnight. Write the copy for the person on the phone at 11pm, not the person scrolling at noon.' Whole brief reframed inside ten minutes.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Cloverkin brand tone working session',
    speaker: 'Rachel Pham',
    capturedAt: dateInWeek(9, 2, 11, 0),
    significance: 0.84,
    confidence: 0.93,
    tags: ['delta', 'decision-trigger', 'pain-point'],
    contactSlug: 'cloverkin-ops-lead',
  },
  {
    slug: 'cm-cloverkin-ops-02',
    content:
      'Rachel rewrote our member-portal welcome string in one Slack message. Shorter, warmer, less branded. We shipped it as-is. The brand voice doc cites her version as the reference for the patient-facing register — operations as voice editor.',
    memoryType: 'fact',
    sourceType: 'channel',
    sourceTitle: '#cloverkin-product — Wed',
    speaker: 'Casey',
    capturedAt: dateInWeek(11, 2, 15, 45),
    significance: 0.78,
    confidence: 0.92,
    tags: ['delta', 'success-marker', 'expansion-signal'],
    contactSlug: 'cloverkin-ops-lead',
  },

  // ─── Throughput — Dominic Ferraro (primary, 8) ──────────────────────
  {
    slug: 'cm-throughput-mp-01',
    content:
      "Dominic on the first call: 'I have six service lines and a website that explains zero of them. I do not want a redesign. I want the homepage to make my COO stop apologizing for our positioning in board prep.' That is the entire repositioning brief.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Throughput kickoff call — Mon',
    speaker: 'Dominic Ferraro',
    capturedAt: dateInWeek(10, 1, 14, 30),
    significance: 0.94,
    confidence: 0.95,
    tags: ['epsilon', 'decision-trigger', 'pain-point'],
    contactSlug: 'throughput-managing-partner',
  },
  {
    slug: 'cm-throughput-mp-02',
    content:
      'He gave us the gross margin per service line on slide three of his own deck. Most prospects guard that number for three meetings. He led with it because he wanted us to price the work properly — and because he wanted us to know which practice was the loss leader.',
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Throughput kickoff call — Mon',
    speaker: 'Garry Tan',
    capturedAt: dateInWeek(10, 1, 15, 0),
    significance: 0.88,
    confidence: 0.94,
    tags: ['epsilon', 'pricing', 'decision-trigger', 'success-marker'],
    contactSlug: 'throughput-managing-partner',
  },
  {
    slug: 'cm-throughput-mp-03',
    content:
      "Quote: 'We are not McKinsey, we are not the boutique with the cool case studies. We are the firm a COO calls when the practice lead just quit and the SOW is due Friday. Sell that.' Positioning brief in one paragraph — Sara has been quoting it back inside the studio for two weeks.",
    memoryType: 'fact',
    sourceType: 'meeting',
    sourceTitle: 'Throughput positioning intensive',
    speaker: 'Dominic Ferraro',
    capturedAt: dateInWeek(10, 4, 11, 0),
    significance: 0.93,
    confidence: 0.95,
    tags: ['epsilon', 'decision-trigger', 'competitor-mention'],
    contactSlug: 'throughput-managing-partner',
  },
  {
    slug: 'cm-throughput-mp-04',
    content:
      "Dominic killed the 'thought leadership' line item the moment Leo brought it up. 'My buyers do not read white papers. They forward Loom videos to their CEO and we either show up in those Looms or we do not.' Filed as the Throughput content constraint — short-form, visible, forwardable.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Throughput media plan review',
    speaker: 'Dominic Ferraro',
    capturedAt: dateInWeek(11, 2, 13, 0),
    significance: 0.86,
    confidence: 0.94,
    tags: ['epsilon', 'objection', 'decision-trigger'],
    contactSlug: 'throughput-managing-partner',
  },
  {
    slug: 'cm-throughput-mp-05',
    content:
      'Dominic has standing breakfasts with four COOs at portfolio companies of one PE firm. The pipeline is the breakfast. Foundry is here to make the homepage worthy of the forward — the buyer journey starts at a half-eaten plate, not at a paid click.',
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#throughput-strategy — Thu',
    speaker: 'Garry Tan',
    capturedAt: dateInWeek(11, 3, 15, 30),
    significance: 0.82,
    confidence: 0.92,
    tags: ['epsilon', 'success-marker', 'expansion-signal'],
    contactSlug: 'throughput-managing-partner',
  },
  {
    slug: 'cm-throughput-mp-06',
    content:
      "On the proposal kit review: 'every page of this needs to be useful even if we lose the deal. If we lose, I want them to remember we wrote the only useful proposal they got that quarter.' That is the bar for the proposal template — utility over polish.",
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Throughput proposal kit review',
    speaker: 'Dominic Ferraro',
    capturedAt: dateInWeek(12, 1, 10, 30),
    significance: 0.88,
    confidence: 0.93,
    tags: ['epsilon', 'decision-trigger', 'success-marker'],
    contactSlug: 'throughput-managing-partner',
  },
  {
    slug: 'cm-throughput-mp-07',
    content:
      "Dominic on outbound: 'no template. If the email could have been sent to ten other COOs, do not send it. Send three a week, not three hundred.' Volume-allergic, signal-only outbound. Owen is loving this — matches the studio's own no-template stance.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Throughput outbound program kickoff',
    speaker: 'Dominic Ferraro',
    capturedAt: dateInWeek(12, 4, 14, 0),
    significance: 0.85,
    confidence: 0.94,
    tags: ['epsilon', 'objection', 'decision-trigger'],
    contactSlug: 'throughput-managing-partner',
  },
  {
    slug: 'cm-throughput-mp-08',
    content:
      "Dominic told Riley quietly that he picked Foundry over a larger shop because we were the only firm that asked which service line was the loss leader before we wrote a single line of copy. P&L-fluent buyers want P&L-fluent vendors — note this as the avatar's decision criterion.",
    memoryType: 'insight',
    sourceType: 'channel',
    sourceTitle: '#throughput-account — Mon',
    speaker: 'Riley',
    capturedAt: dateInWeek(13, 0, 9, 0),
    significance: 0.92,
    confidence: 0.94,
    tags: ['epsilon', 'success-marker', 'expansion-signal', 'pricing'],
    contactSlug: 'throughput-managing-partner',
  },

  // ─── Throughput — Yuki Tanaka (secondary, 3) ────────────────────────
  {
    slug: 'cm-throughput-bd-01',
    content:
      "Yuki keeps the conversation on lead volume even when Dominic is asking about positioning. 'We need 40 more meetings this quarter' is her line. Dominic does not want 40 more bad meetings — the metric mismatch is loud and worth flagging in the avatar diff.",
    memoryType: 'observation',
    sourceType: 'channel',
    sourceTitle: '#throughput-pipeline — Wed',
    speaker: 'Leo',
    capturedAt: dateInWeek(11, 2, 16, 0),
    significance: 0.68,
    confidence: 0.88,
    tags: ['epsilon', 'risk-signal', 'objection'],
    contactSlug: 'throughput-bizdev-head',
  },
  {
    slug: 'cm-throughput-bd-02',
    content:
      "Yuki proposed a 'top of funnel content blitz' in the kickoff. Dominic shut it down in the same call. Worth noting that biz dev's metric and the managing partner's positioning are still misaligned here — Riley flagged it in the partner Slack.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Throughput pipeline review',
    speaker: 'Riley',
    capturedAt: dateInWeek(11, 4, 11, 30),
    significance: 0.7,
    confidence: 0.87,
    tags: ['epsilon', 'risk-signal', 'objection'],
    contactSlug: 'throughput-bizdev-head',
  },
  {
    slug: 'cm-throughput-bd-03',
    content:
      'Yuki pushed for us to write SDR sequences before the positioning was locked. The minute we did, Dominic asked us to pause. The buyer pattern is clear: she wants tactics, he wants posture. File as the canonical disqualified-leads pattern — tactics-first stakeholder.',
    memoryType: 'observation',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Throughput SDR sequences draft',
    speaker: 'Sara',
    capturedAt: dateInWeek(12, 2, 10, 0),
    significance: 0.74,
    confidence: 0.9,
    tags: ['epsilon', 'risk-signal', 'pain-point'],
    contactSlug: 'throughput-bizdev-head',
  },

  // ─── Throughput — Aliyah Whitfield (secondary, 2) ───────────────────
  {
    slug: 'cm-throughput-coo-01',
    content:
      "Aliyah is the silent voice in every Throughput call. When Dominic asks 'can we promise this', he is asking her. Her nods are decisions. The actual approver, undocumented — Riley should always route deliverables past Aliyah before Dominic.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Throughput weekly status',
    speaker: 'Riley',
    capturedAt: dateInWeek(11, 3, 11, 0),
    significance: 0.78,
    confidence: 0.9,
    tags: ['epsilon', 'decision-trigger', 'success-marker'],
    contactSlug: 'throughput-coo',
  },
  {
    slug: 'cm-throughput-coo-02',
    content:
      "Aliyah corrected our service-line hierarchy in three minutes: 'the order matters — the practice with the lowest attrition goes first because the others depend on staff from it.' Operations literacy hidden in a brand IA review. Devon updated the nav the same day.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Throughput IA review',
    speaker: 'Aliyah Whitfield',
    capturedAt: dateInWeek(13, 1, 14, 30),
    significance: 0.84,
    confidence: 0.93,
    tags: ['epsilon', 'decision-trigger', 'success-marker'],
    contactSlug: 'throughput-coo',
  },

  // ─── Almanac — Tomás Reinhardt (primary, 8) ─────────────────────────
  {
    slug: 'cm-almanac-founder-01',
    content:
      "Tomás opened the kickoff with: 'I have run six cohorts. Two changed people. Four were nice. I want the brand to make sure the next twelve are the first kind.' That is a positioning brief written from the syllabus side, not from the marketing side.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Almanac onboarding call — Thurs',
    speaker: 'Tomás Reinhardt',
    capturedAt: dateInWeek(10, 4, 10, 15),
    significance: 0.93,
    confidence: 0.95,
    tags: ['zeta', 'decision-trigger', 'pain-point'],
    contactSlug: 'almanac-founder',
  },
  {
    slug: 'cm-almanac-founder-02',
    content:
      "He has a no-words list as long as Marisol's: 'gamified', 'bite-sized', 'unlock'. Added 'transformative' himself in the second call. Strong opinion about the difference between learning and edutainment — the brand needs to hold the line against the category's tone drift.",
    memoryType: 'fact',
    sourceType: 'email',
    sourceTitle: 'Email reply re: Almanac voice avoid-list',
    speaker: 'Tomás Reinhardt',
    capturedAt: dateInWeek(10, 6, 9, 0),
    significance: 0.8,
    confidence: 0.95,
    tags: ['zeta', 'objection', 'competitor-mention'],
    contactSlug: 'almanac-founder',
  },
  {
    slug: 'cm-almanac-founder-03',
    content:
      "Quote: 'Our cohort is twenty-eight adults who took two hours out of a Tuesday. The course page has to honor that, not impress them.' Sara has been quoting it back to us for weeks — the page voice came directly from that single line.",
    memoryType: 'reflection',
    sourceType: 'meeting',
    sourceTitle: 'Almanac course-page intensive',
    speaker: 'Tomás Reinhardt',
    capturedAt: dateInWeek(11, 2, 11, 30),
    significance: 0.9,
    confidence: 0.94,
    tags: ['zeta', 'decision-trigger', 'success-marker'],
    contactSlug: 'almanac-founder',
  },
  {
    slug: 'cm-almanac-founder-04',
    content:
      "Tomás killed the 'limited seats' urgency line on the course page. 'If they are not sure, I do not want them in the cohort. The drop-off is worse than the no-sign-up.' Funnel maturity we do not see often — the no-sale is a feature, not a defect.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Almanac course-page review',
    speaker: 'Tomás Reinhardt',
    capturedAt: dateInWeek(11, 4, 14, 0),
    significance: 0.88,
    confidence: 0.94,
    tags: ['zeta', 'objection', 'decision-trigger'],
    contactSlug: 'almanac-founder',
  },
  {
    slug: 'cm-almanac-founder-05',
    content:
      "He gives every cohort one Sunday review email he writes himself. Said: 'that email is the brand. Everything else is the trailer.' We re-architected the lifecycle around the Sunday review — every other touchpoint exists to land that one email in the inbox.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Almanac lifecycle planning',
    speaker: 'Sara',
    capturedAt: dateInWeek(12, 1, 15, 30),
    significance: 0.92,
    confidence: 0.94,
    tags: ['zeta', 'decision-trigger', 'expansion-signal'],
    contactSlug: 'almanac-founder',
  },
  {
    slug: 'cm-almanac-founder-06',
    content:
      "On the public reading list: 'a reading list is a free course. Treat it like one. If it is not the best thing on the internet for that topic, do not publish it.' Bar raised, the inbound plan rewritten. Maya is treating the reading list as the brand's flagship object now.",
    memoryType: 'insight',
    sourceType: 'meeting',
    sourceTitle: 'Almanac reading list working session',
    speaker: 'Tomás Reinhardt',
    capturedAt: dateInWeek(12, 3, 11, 0),
    significance: 0.87,
    confidence: 0.93,
    tags: ['zeta', 'decision-trigger', 'expansion-signal'],
    contactSlug: 'almanac-founder',
  },
  {
    slug: 'cm-almanac-founder-07',
    content:
      "Tomás turned down a paid social pilot from Leo: 'a paid ad cannot make a stranger trust a cohort. Word of mouth and the reading list have to do that work.' Same shape as Marisol's no, different vertical — pattern across two avatars.",
    memoryType: 'decision',
    sourceType: 'meeting',
    sourceTitle: 'Almanac growth review',
    speaker: 'Tomás Reinhardt',
    capturedAt: dateInWeek(12, 4, 16, 0),
    significance: 0.86,
    confidence: 0.93,
    tags: ['zeta', 'objection', 'risk-signal'],
    contactSlug: 'almanac-founder',
    emotion: { label: 'firm', valence: 0.3, intensity: 0.8 },
  },
  {
    slug: 'cm-almanac-founder-08',
    content:
      "He told Maya on a quiet call: 'I would rather run a cohort of twenty than fill one of fifty with the wrong twenty.' That is the constraint the brand has to hold. Renewal-class signal — Tomás is selecting the audience as carefully as the audience selects him.",
    memoryType: 'reflection',
    sourceType: 'channel',
    sourceTitle: '#almanac-strategy — Mon',
    speaker: 'Tomás Reinhardt',
    capturedAt: dateInWeek(13, 0, 14, 0),
    significance: 0.92,
    confidence: 0.94,
    tags: ['zeta', 'success-marker', 'expansion-signal', 'pricing'],
    contactSlug: 'almanac-founder',
  },

  // ─── Almanac — Imani Greer (secondary, 2) ───────────────────────────
  {
    slug: 'cm-almanac-programs-01',
    content:
      "Imani runs the mentor program. She pushed back on Casey's first instructor profile design: 'mentors are not faculty. Do not photograph them like faculty.' We dropped the institutional headshot grid the same afternoon — replaced with desk-context shots.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Almanac mentor design review',
    speaker: 'Imani Greer',
    capturedAt: dateInWeek(11, 3, 14, 30),
    significance: 0.74,
    confidence: 0.92,
    tags: ['zeta', 'decision-trigger', 'success-marker'],
    contactSlug: 'almanac-programs-head',
  },
  {
    slug: 'cm-almanac-programs-02',
    content:
      'Imani tracks one number a week: percent of cohort that posted in the mentor channel on Wednesday. Said it correlates with completion better than any pre-survey signal. Useful for the case-study copy — the engagement metric that actually matters has a name.',
    memoryType: 'insight',
    sourceType: 'channel',
    sourceTitle: '#almanac-programs — Thu',
    speaker: 'Imani Greer',
    capturedAt: dateInWeek(13, 1, 10, 0),
    significance: 0.78,
    confidence: 0.92,
    tags: ['zeta', 'success-marker', 'expansion-signal'],
    contactSlug: 'almanac-programs-head',
  },

  // ─── Almanac — Sebastian Wu (secondary, 2) ──────────────────────────
  {
    slug: 'cm-almanac-instructor-01',
    content:
      "Sebastian keeps asking for 'completion rate' to be the headline metric on the course page. Tomás disagrees. The instructor lead's metric instinct is shaped by what is easy to measure, not what matters — file as the disqualified-pattern signal.",
    memoryType: 'observation',
    sourceType: 'meeting',
    sourceTitle: 'Almanac metrics review',
    speaker: 'Maya',
    capturedAt: dateInWeek(12, 2, 13, 0),
    significance: 0.7,
    confidence: 0.88,
    tags: ['zeta', 'risk-signal', 'objection'],
    contactSlug: 'almanac-instructor-lead',
  },
  {
    slug: 'cm-almanac-instructor-02',
    content:
      "Sebastian pitched a 'study group leaderboard' for next cohort. Tomás passed. Sebastian's instinct is toward engagement mechanics; the brand needs to hold the line against them. Useful pattern for the cross-vertical-disqualified-leads avatar — tactic-loyal, mechanic-first.",
    memoryType: 'insight',
    sourceType: 'channel',
    sourceTitle: '#almanac-curriculum — Fri',
    speaker: 'Sara',
    capturedAt: dateInWeek(13, 1, 16, 30),
    significance: 0.72,
    confidence: 0.9,
    tags: ['zeta', 'risk-signal', 'pain-point'],
    contactSlug: 'almanac-instructor-lead',
  },
]

// ─── AVATARS (7 clusters) ──────────────────────────────────────────────

export const CUSTOMER_AVATARS: readonly AvatarNarrative[] = [
  {
    slug: 'saas-platform-founders',
    name: 'SaaS platform founders who are tired of marketing-speak',
    summary:
      'Engineer-founders and platform leaders at Series A-B infrastructure companies who got paged twice this quarter, are now the buyer for their own category, and refuse to let the marketing copy say anything they cannot defend in a customer call. Allergic to thought-leadership posts; trust the README more than the homepage.',
    narrativeMd: [
      'The platform-founder avatar is what shows up when an engineer-led infrastructure company hits the moment where its marketing site is no longer talking to the right buyer. The product has matured past the indie-developer audience that built the early community, and the actual buyer is now the head of platform at a Series B who has been paged twice this quarter for the category. Every line of marketing copy that still flatters the old audience costs pipeline.',
      "Devi Ramanathan is the canonical example. She will not put a single number on the marketing site that she cannot defend in a customer call. She killed three SOC 2 stats from the about page herself. Marcus Holloway, her engineering manager, closed a Slack thread about thought-leadership posts with one sentence — 'if we are writing posts our own engineers would not read, we are wasting Devi's time' — and that became the editorial policy by acclamation.",
      "What unites them: they treat the documentation as a product surface, the marketing site as a credibility surface, and any campaign that does not move the on-call buyer's hand toward the demo button as theater. They are skeptical of paid spend as a starting move, fluent enough in the numbers to know when an experiment is over, and pragmatic enough to flip back to organic the moment a paid test fails its kill criterion.",
      'Foundry is the right brain for them because we will not pitch them on a logo refresh, will refuse to write technical claims their on-call engineers have not nodded at, and will sit on a paid budget until the organic signal proves the message. The retainer either reshapes which audience the funnel speaks to or we got the work wrong.',
    ].join('\n\n'),
    memberContactSlugs: ['plinthworks-platform-lead', 'plinthworks-eng-manager'],
    dominantPainPoints: [
      'Marketing copy still speaks to the previous, smaller buyer.',
      'Internal stakeholders chasing reach metrics instead of platform-buyer pipeline.',
      'Documentation treated as marketing surface, not product surface.',
      'Founders refuse to claim numbers they cannot defend in a customer call.',
      'Thought-leadership content fatigue — the team will not read its own posts.',
    ],
    blindSpots:
      'Tendency to undersell credibility moments because the founder is allergic to claim-stacking; sometimes too patient about a paid signal that has clearly failed its kill criterion.',
    discriminatorProfile: {
      stakes: { value: 'platform revenue, on-call quality, recruiting funnel', strength: 0.85 },
      horizon: { value: 'this quarter, this year', strength: 0.8 },
      money: { value: 'ROI-confident, allergic to vanity spend', strength: 0.9 },
      reference_frame: { value: 'other engineer-led infrastructure companies', strength: 0.85 },
      identity: { value: 'I run a platform, I am an operator who codes', strength: 0.9 },
      pain: { value: 'wrong-buyer pipeline, docs friction, hiring funnel quality', strength: 0.85 },
      risk: { value: 'pragmatic — high appetite for change once data moves', strength: 0.6 },
    },
    emotionalSignature: {
      pragmatic: 0.9,
      skeptical: 0.75,
      'quiet-confidence': 0.6,
      'allergic-to-hype': 0.9,
    },
    emergedAt: dateInWeek(7, 3, 15, 0),
    status: 'active',
  },
  {
    slug: 'dtc-operators-with-taste',
    name: 'DTC founder-operators whose voice is the moat',
    summary:
      'Creator-founders running specialty consumer brands whose voice and visual register are the actual product. They will defend a tone constraint over a launch window and refuse any campaign that smells like the rest of the category. Sensory, unhurried, and operationally literate enough to kill a SKU in one sentence.',
    narrativeMd: [
      "The dtc-operators-with-taste avatar emerges when a founder-led specialty brand reaches the moment where the easiest path to growth — paid social against the obvious holiday keyword, an influencer line item, a 'curated' editorial photo shoot — would visibly collapse the thing that made the brand worth buying in the first place. The brand is the voice, the photography is the voice, the third email is the voice, and the founder knows it down to the linen choice.",
      "Eliza Marchetti is the canonical example: she would rather miss a launch window than ship a campaign that smells like everyone else's brand, and she said it without flinching twelve minutes into our kickoff. June Kowalski, her brand lead, rewrote three of Sara's headlines on the first Friday and her version was always shorter — she hates 'storytelling' as a verb and ships story as a noun. Theo Nakashima, on the ops side, is the brand-safety function — he killed a 'kitchen kit' bundle SKU with three SKUs, three pickers, no.",
      'What unites them: they read every customer support ticket on Monday morning, they will quote the actual customer phrasing back in Wednesday emails, and they will not let the brand sound like Williams Sonoma even when the metrics are quietly asking them to. They know their funnel — Eliza named the lifecycle slot that was leaking revenue before we did — and they are operationally literate enough to refuse a media plan that the warehouse cannot honor in week three.',
      'Foundry is the right brain for them because Sara will write headlines they actually shorten, Casey will shoot in real kitchens with real morning light, and Leo will kill a media line item on a single seven-day cohort. The retainer either honors the voice constraint and grows revenue inside it, or we wrote a campaign a competitor could paste under their logo and we owe a refund.',
    ].join('\n\n'),
    memberContactSlugs: ['saltline-founder', 'saltline-brand-lead', 'saltline-ops-lead'],
    dominantPainPoints: [
      'Category drift toward wellness-app sameness threatens brand distinctiveness.',
      'Pressure to bid on commodity keywords (gift, holiday) the brand should never bid on.',
      'Influencer line items that move the cohort by zero and cost rent.',
      'Editorial photography that looks staged and not lived-in.',
      'Lifecycle copy leaking revenue at the third-email slot.',
      'Operations and brand teams misaligned on what week three can ship.',
    ],
    blindSpots:
      'Defensive enough about the voice that they sometimes refuse a tactical experiment that would not actually drift the brand; can be slow to greenlight a paid test even when the organic data has already validated the line.',
    discriminatorProfile: {
      stakes: {
        value: 'revenue per customer, kitchen-table economics, brand voice integrity',
        strength: 0.9,
      },
      horizon: {
        value: 'this quarter, next launch window, shoulder-season calendar',
        strength: 0.75,
      },
      money: { value: 'ROI-confident inside strict voice constraints', strength: 0.85 },
      reference_frame: {
        value: 'other specialty brands they respect, not the category',
        strength: 0.85,
      },
      identity: { value: 'I run a brand, my voice is the moat', strength: 0.95 },
      pain: { value: 'sameness, ad fatigue, the "wellness app" tonal drift', strength: 0.85 },
      risk: { value: 'high appetite for change inside voice constraints', strength: 0.7 },
    },
    emotionalSignature: {
      sensory: 0.85,
      'protective-of-voice': 0.95,
      unhurried: 0.7,
      firm: 0.65,
    },
    emergedAt: dateInWeek(7, 4, 11, 0),
    status: 'active',
  },
  {
    slug: 'fintech-marketing-controllers',
    name: 'Fintech marketing leads and CFOs moving the brand upmarket',
    summary:
      "Marketing leaders and finance leaders at fintech companies whose product has outgrown its SMB origin story and now sells to controllers and CFOs at Series B-C fintechs. Numbers-fluent, board-defensible, allergic to 'AI-powered' headlines. The marketing site is a sales artifact and the CFO sits in on the brand call.",
    narrativeMd: [
      'The fintech-marketing-controllers avatar appears when a fintech company crosses the threshold where its marketing site is still apologizing for being a finance tool and its actual buyer is a controller at a Series B who needs the close to take six days instead of eleven. The repositioning is not optional — the wrong website is costing pipeline measurable in months, and the CFO knows the number to three decimal places.',
      "Adaeze Okonkwo and Wendell Brockman are the canonical pairing: she opened our kickoff with 'our site still talks to bookkeepers, our actual buyer is the controller at a Series B fintech, we have been writing copy to a customer we no longer want,' and he sat in on the brand call from week one because the wrong website costs him six months of pipeline that he has to defend on a board slide. Hana Sato, the actual controller on staff, joins working sessions to correct single words — 'sub-ledger, not general ledger' — and forwards the launch email to the controller community Slack she runs without being asked.",
      "What unites them: they know their funnel cold, they treat the marketing site as a sales artifact subject to the same scrutiny as a board deck, and they have done more customer research in a month than most marketing teams do in a year. The CFO is not a stakeholder — he is the co-buyer, and he will kill an 'AI-powered' line in the hero himself because no CFO has ever wired more money because something was AI-powered.",
      "Foundry is the right brain for them because Maya will write positioning that survives a Bloomberg headline cycle, Sara will hand drafts to Adaeze with the line 'circle what a controller would underline,' and Devon will treat the controller page as a conversion surface, not a brand artifact. The work either earns its place in the next board update or we wrote a deck instead of a campaign.",
    ].join('\n\n'),
    memberContactSlugs: ['helmsmark-marketing-head', 'helmsmark-cfo', 'helmsmark-controller'],
    dominantPainPoints: [
      'Marketing copy still apologizing for being a finance tool.',
      'Funnel speaking to SMB while the actual buyer is a controller at a Series B fintech.',
      "Hero language reaching for 'AI-powered' instead of variance-shrinking specifics.",
      'Case study program over-indexed on quantity instead of three named-CFO trust marks.',
      'Marketing-finance alignment fragile at peer fintechs and missing as a sales unlock.',
      'Subject-matter accuracy (sub-ledger vs general ledger) as a brand-credibility surface.',
    ],
    blindSpots:
      'So focused on board-defensibility that they occasionally undervalue the emotional register a controller would underline; can over-index on numerical proof when a single qualitative case study would close more deals.',
    discriminatorProfile: {
      stakes: {
        value: 'enterprise pipeline, board-level credibility, controller trust',
        strength: 0.95,
      },
      horizon: { value: 'this quarter, this fiscal year, post-Series-A arc', strength: 0.9 },
      money: { value: 'ROI-confident, every dollar defended on a board slide', strength: 0.95 },
      reference_frame: {
        value: 'other fintechs moving upmarket, not the SMB category',
        strength: 0.9,
      },
      identity: { value: 'I run a P&L, the brand is a sales artifact', strength: 0.9 },
      pain: { value: 'apologetic positioning, MQL-to-controller-meeting gap', strength: 0.9 },
      risk: { value: 'measured — high appetite when numbers back the move', strength: 0.7 },
    },
    emotionalSignature: {
      precise: 0.95,
      sober: 0.9,
      'allergic-to-hype': 0.95,
      'trust-coded': 0.85,
    },
    emergedAt: dateInWeek(8, 2, 10, 0),
    status: 'active',
  },
  {
    slug: 'healthtech-clinic-ops-founders',
    name: 'Healthtech clinician-founders running clinic-plus-virtual care',
    summary:
      'Clinician-founders and clinic ops leaders running multi-city care models who will lose a visit before they ship a marketing email that finds a patient on a hard day. Trust-coded, language-disciplined, and operationally honest about which line a patient calls at 11pm. The product is continuity, not the app.',
    narrativeMd: [
      'The healthtech-clinic-ops-founders avatar emerges when a clinician-founder builds a care model that combines physical clinics and virtual care, scales into multiple metros, and reaches the moment where consumer-style marketing language would visibly break the trust the clinical team has earned at the bedside. Every word the brand uses has to survive being read by a patient who is scared, on the phone at 11pm, or scheduling a follow-up after a hard appointment.',
      "Dr. Marisol Vega is the canonical example. She vetoes 'consumer' on sight, also 'wellness journey', 'magical', 'frictionless', and added 'partner' to the list after thinking about the asymmetry it implies. She made us sit through three patient-navigator calls before we wrote a single line of onboarding copy. Dr. James Ouedraogo, the clinical head, reviews patient-facing drafts faster than most of our copywriters — he circled four things in his first review, three medical-accuracy, one tone. Rachel Pham, the patient ops director, ended a brand-tone debate by pulling up after-hours call volume and saying write the copy for the person on the phone at 11pm, not the person scrolling at noon.",
      'What unites them: continuity is the product, the bedside is the brand testing ground, and any marketing send within 48 hours of a visit is a trust violation. They are slow to greenlight paid acquisition not out of skepticism about the channel but because the brand promise breaks the moment they advertise to anyone they cannot see in a clinic. The accent color on the website is derived from the after-hours emergency contact pill — because the color of the after-hours line matters more than the color of the logo.',
      'Foundry is the right brain for them because Sara will rewrite the welcome series three times after the second patient-navigator call, Casey will rebuild the UI palette around the after-hours pill, and Maya will hold the line on the no-words list even when growth pressure pushes the team to soften it. The work either lowers the heart rate of a patient reading it on a hard day or it should not ship.',
    ].join('\n\n'),
    memberContactSlugs: ['cloverkin-founder', 'cloverkin-clinical-head', 'cloverkin-ops-lead'],
    dominantPainPoints: [
      'Consumer-style marketing language that breaks the bedside trust the clinical team earned.',
      'Send-window risk — marketing emails landing in a patient inbox the day after a hard appointment.',
      'Paid acquisition that pulls in patients the clinic cannot physically see.',
      'Brand tone that does not lower the heart rate of a scared patient at 11pm.',
      'Subject-matter accuracy as a brand-trust surface (continuity, eligibility, after-hours).',
      'Stakeholder pressure to use category-fashion words like wellness, frictionless, magical.',
    ],
    blindSpots:
      'So protective of the bedside register that they occasionally under-ship the marketing surface that would attract the right new patients; sometimes treat any growth experiment as a trust risk rather than evaluating per-channel.',
    discriminatorProfile: {
      stakes: { value: 'patient trust, continuity, regulatory exposure', strength: 0.95 },
      horizon: { value: 'this year, three-year care continuity', strength: 0.85 },
      money: { value: 'careful — ROI must not break the trust', strength: 0.8 },
      reference_frame: {
        value: 'other clinical operators, not consumer health brands',
        strength: 0.95,
      },
      identity: { value: 'I run a clinic and I am also a clinician', strength: 0.95 },
      pain: {
        value: 'consumer drift, language that fails at the bedside, paid trust break',
        strength: 0.95,
      },
      risk: { value: 'low — change must be tested against patient safety first', strength: 0.4 },
    },
    emotionalSignature: {
      careful: 0.95,
      warm: 0.85,
      'protective-of-patient': 0.95,
      'trust-coded': 0.9,
    },
    emergedAt: dateInWeek(9, 1, 14, 0),
    status: 'active',
  },
  {
    slug: 'services-firm-managing-partners',
    name: 'Managing partners and COOs at 200-1000 person services firms',
    summary:
      'P&L-fluent operators running multi-service-line professional firms who lead with gross margin on slide three and refuse thought leadership in favor of forwardable Loom videos. They want a homepage their COO can stop apologizing for in board prep and a proposal kit useful even on the deals they lose.',
    narrativeMd: [
      'The services-firm-managing-partners avatar emerges when a 200-1000 person professional services firm with five to seven service lines hits the moment where the website explains zero of them, the COO is quietly apologizing for the positioning in board prep, and the practice that should anchor the hierarchy is the one nobody talks about because it has the lowest attrition. The work is repackaging six things into one story and giving the partner a homepage worthy of the breakfasts that actually drive pipeline.',
      "Dominic Ferraro is the canonical example. He gave us the gross margin per service line on slide three of his own deck — most prospects guard that number for three meetings — and he led with it because he wanted us to price the work properly and know which practice was the loss leader. Aliyah Whitfield, his COO, is the silent voice in every call; when Dominic asks 'can we promise this,' he is asking her, and her nods are decisions.",
      "What unites them: they buy from operators who treat the P&L as table stakes, they will not read white papers and refuse to publish them, and they measure brand by whether a Loom video gets forwarded to the prospect's CEO. The pipeline is a standing breakfast with four COOs at portfolio companies of one PE firm — Foundry's job is to make the homepage worthy of the forward, not to invent a top-of-funnel that does not exist.",
      'Foundry is the right brain for them because Garry will ask which service line is the loss leader before writing a single line of copy, Owen will treat the proposal kit as a P&L instrument, and Sara will write a proposal page useful even on the deals we lose. The work either makes the COO stop apologizing for the positioning or we shipped a redesign instead of a repositioning.',
    ].join('\n\n'),
    memberContactSlugs: ['throughput-managing-partner', 'throughput-coo'],
    dominantPainPoints: [
      'Marketing site explains zero of the service lines clearly.',
      'COO quietly apologizing for positioning in board prep.',
      'Practice hierarchy mis-ordered against attrition / staffing dependencies.',
      'Internal pressure for thought-leadership content that buyers do not read.',
      'SDR sequences and outbound templates that buyers immediately flag as templates.',
      'Pipeline dependent on personal forwards (Looms, breakfasts) without a worthy homepage.',
    ],
    blindSpots:
      'So allergic to thought-leadership content that they occasionally undervalue the long-form case study that would close a specific COO; the partner-led pipeline can mask gaps in inbound infrastructure that show up only when a breakfast is missed.',
    discriminatorProfile: {
      stakes: { value: 'gross margin, utilization, renewal, board credibility', strength: 0.95 },
      horizon: { value: 'this quarter, this fiscal year', strength: 0.85 },
      money: { value: 'ROI-confident, fluent in P&L vocabulary', strength: 0.95 },
      reference_frame: { value: 'other services firms at 200-1000 person scale', strength: 0.85 },
      identity: { value: 'I run a P&L, I am an operator with a deal sheet', strength: 0.95 },
      pain: { value: 'commoditization, scope creep, COO-credibility gap', strength: 0.85 },
      risk: { value: 'high appetite for change when bench utilization slips', strength: 0.7 },
    },
    emotionalSignature: {
      measured: 0.9,
      'P&L-fluent': 0.95,
      'no-fluff': 0.9,
      confident: 0.85,
    },
    emergedAt: dateInWeek(11, 2, 11, 0),
    status: 'emerging',
  },
  {
    slug: 'adult-cohort-edu-founders',
    name: 'Adult-cohort education founders who refuse edutainment',
    summary:
      'Educator-operators building cohort-based programs for adults who have run six cohorts, know which two changed people and which four were just nice, and refuse to fill a cohort of fifty with the wrong twenty. The Sunday review email is the brand; the course page has to honor a Tuesday evening, not impress it.',
    narrativeMd: [
      'The adult-cohort-edu-founders avatar emerges when an operator-educator has run enough cohorts to know which sessions actually change people and which were merely nice, and reaches the moment where the marketing language for the next cohort has to honor the seriousness of twenty-eight adults pulling two hours out of a Tuesday. The pressure to gamify, to add limited-seats urgency, to drift into edutainment is loud — and the right answer is almost always no.',
      "Tomás Reinhardt is the canonical example. He opened our kickoff with 'I have run six cohorts, two changed people, four were nice, I want the brand to make sure the next twelve are the first kind' — that is a positioning brief written from the syllabus side, not the marketing side. He killed the 'limited seats' urgency line on the course page himself: if they are not sure, he does not want them in the cohort. Imani Greer, the programs head, pushed back on Casey's instructor profile design with 'mentors are not faculty, do not photograph them like faculty' and tracks the one engagement metric (Wednesday mentor-channel posts) that actually correlates with completion.",
      'What unites them: they refuse to discount the cohort price even under fill pressure, they treat the public reading list as a flagship object (a reading list is a free course; if it is not the best on the internet for that topic, do not publish it), and they understand the long-tail economics of word-of-mouth better than paid acquisition would ever reward. The Sunday review email the founder writes by hand is the brand; everything else is the trailer.',
      'Foundry is the right brain for them because Sara will write copy that honors the seriousness of the cohort, Maya will treat the reading list as the inbound flagship and not a content marketing line item, and Leo will not push paid social against an audience that buys cohorts on trust. The work either makes the right twenty sign up or we filled the room wrong and the founder will tell us inside the first week.',
    ].join('\n\n'),
    memberContactSlugs: ['almanac-founder', 'almanac-programs-head'],
    dominantPainPoints: [
      'Category drift toward gamified, bite-sized, edutainment language.',
      'Pressure to use urgency tactics (limited seats, countdowns) on serious cohort pages.',
      'Mentor and instructor profiles photographed and copywritten like institutional faculty.',
      'Completion-rate vanity metrics over actual learning-outcome signals.',
      'Paid acquisition pressure against an audience that buys cohorts on trust.',
      'Cohort-fill pressure that would dilute the room with the wrong twenty.',
    ],
    blindSpots:
      'So protective of the cohort experience that they sometimes under-market the next round; the trust-and-word-of-mouth strategy can hide moments where a small paid experiment would have surfaced a new audience.',
    discriminatorProfile: {
      stakes: {
        value: 'learner outcomes, mentor retention, cohort completion quality',
        strength: 0.85,
      },
      horizon: { value: 'next cohort, this year, multi-cohort reputation arc', strength: 0.8 },
      money: { value: 'careful — refusal to discount the cohort price', strength: 0.75 },
      reference_frame: { value: 'other operator-educators they respect', strength: 0.85 },
      identity: { value: 'I run a learning system, not a content business', strength: 0.95 },
      pain: {
        value: 'edutainment drift, completion-rate metrics, cohort-fill pressure',
        strength: 0.85,
      },
      risk: { value: 'low — change must protect the cohort experience first', strength: 0.5 },
    },
    emotionalSignature: {
      generous: 0.85,
      unpatronizing: 0.9,
      'protective-of-craft': 0.9,
      curious: 0.75,
    },
    emergedAt: dateInWeek(11, 4, 16, 0),
    status: 'emerging',
  },
  {
    slug: 'cross-vertical-disqualified-leads',
    name: 'Function-loyal stakeholders Foundry would say no to',
    summary:
      'A cross-vertical anti-avatar made of secondary stakeholders whose metric instinct is shaped by what is easy to measure rather than what matters. Reach, completion rate, lead count, engagement leaderboards. They want a tactic; their founders want a posture. If they were the primary buyer, Foundry would walk.',
    narrativeMd: [
      'The cross-vertical-disqualified-leads avatar is the meta-pattern Atlas pieced together from secondary stakeholders inside otherwise Foundry-shaped accounts. They are not the buyer — they are the person in the room whose metric instinct keeps pulling the conversation toward the easy-to-measure number, away from the posture work that earned the retainer in the first place. If they were the primary stakeholder pitching us, we would walk.',
      "Priya Chen at Plinthworks keeps the conversation on 'engagement on the launch post' even when Devi is asking about pipeline. Yuki Tanaka at Throughput proposed a 'top of funnel content blitz' in the kickoff and pushed for SDR sequences before the positioning was locked — Dominic shut both down. Sebastian Wu at Almanac keeps asking for 'completion rate' to be the headline metric on the course page and pitched a study-group leaderboard for the next cohort — Tomás passed on both.",
      'What unites them: short-horizon thinking (this week, this post), tactic-loyalty over posture, and a metric reflex shaped by the dashboard their previous role measured them on. They are eager, capable, often well-liked inside their organizations, and they are exactly the founder Foundry would refuse to sign — because the work they would buy is the work that would visibly drift the brand inside ninety days.',
      'This avatar is useful for two things. One: it tells the partner team which voices to listen for in a discovery call as disqualification signal. Two: it tells Riley which secondary stakeholders inside existing accounts to actively buffer the work against — so that the tactic-first instinct does not quietly reshape a campaign Maya, Sara, and the founder already aligned on.',
    ].join('\n\n'),
    memberContactSlugs: ['plinthworks-devrel', 'throughput-bizdev-head', 'almanac-instructor-lead'],
    dominantPainPoints: [
      'Conflating reach with pipeline as the marketing metric.',
      'Pushing tactical execution (SDR sequences, blitzes, leaderboards) before positioning is locked.',
      'Anchoring on completion rate / engagement metrics instead of outcome quality.',
      'Function-loyal: the dashboard their role measures them on becomes the brand brief.',
      'Short-horizon — this week, this post, this cohort — instead of the multi-quarter posture.',
    ],
    blindSpots:
      'They are often the easiest stakeholder to please in a meeting, which makes their misaligned instinct hard to spot until a campaign has quietly drifted; their founders defer to them on tactics and assume their own posture will hold the line — sometimes it does not.',
    discriminatorProfile: {
      stakes: {
        value: 'engagement and activity numbers their role is measured on',
        strength: 0.85,
      },
      horizon: { value: 'this week, this post, this cohort', strength: 0.85 },
      money: {
        value: 'cautious about strategy spend, optimistic about tactical line items',
        strength: 0.7,
      },
      reference_frame: { value: 'other functional peers, category playbooks', strength: 0.8 },
      identity: { value: 'I run a function, I am tactically focused', strength: 0.85 },
      pain: { value: 'reach, completion rate, lead count, leaderboard motion', strength: 0.9 },
      risk: {
        value: 'high appetite for change without conviction — chases new tactics',
        strength: 0.65,
      },
    },
    emotionalSignature: {
      tactical: 0.9,
      'metric-seeking': 0.85,
      'eager-for-volume': 0.8,
      'short-horizon': 0.85,
    },
    emergedAt: dateInWeek(12, 3, 10, 30),
    status: 'shifting',
  },
]
