/**
 * Mission briefs — 30 missions across the 6 client campaigns + Internal Ops,
 * Sales, and Wiki, with mixed statuses (queued / in_progress / completed /
 * cancelled) and realistic timestamps anchored to the 90-day arc.
 *
 * Wave 3 fills this. P7 seeds missions + mission_subtasks +
 * mission_deliverables; P7.5c backfills FKs from deliverables to artifacts.
 *
 * Status mix: 10 completed · 12 in_progress · 7 queued · 1 cancelled.
 */
import type { MissionBrief } from './_types'
import { dateInWeek } from './timeline'

export const MISSIONS: readonly MissionBrief[] = [
  // ── PLINTHWORKS (acme) — 5 missions ─────────────────────────────────────
  {
    slug: 'mission-plinthworks-on-call-positioning-v2',
    title: 'Plinthworks on-call positioning v2',
    campaignSlug: 'acme',
    spaceSlug: 'plinthworks-workspace',
    briefText:
      'Plinthworks v1 positioning reads like every incident-management tool from 2022. The founders want the v2 to sit squarely on the on-call engineer — not the SRE manager, not the buyer. Read the eight customer interviews from Q1, pull the exact phrases on-call engineers use about pager fatigue, and rebuild the homepage hero, sub-hed, and three-up around that voice. Maya owns the position; Sara writes the lines.',
    status: 'completed',
    queuedAt: dateInWeek(8, 1, 10, 0),
    startedAt: dateInWeek(9, 1, 11, 0),
    completedAt: dateInWeek(11, 4, 16, 30),
    subtasks: [
      { title: 'Re-read all 8 customer interview transcripts', done: true },
      { title: 'Pull verbatim quotes — pager fatigue / 3am incidents', done: true },
      { title: 'Draft three position candidates, score each', done: true },
      { title: 'Founder review + Nico pressure-test', done: true },
      { title: 'Sara writes hero + sub-hed + three-up', done: true },
      { title: 'Casey set type and rhythm at 14px and at billboard scale', done: true },
      { title: 'Approval call with Plinthworks CEO', done: true },
    ],
    deliverableKinds: ['positioning', 'offer'],
    assignedAgentName: 'Maya',
  },
  {
    slug: 'mission-plinthworks-dev-launch-post-v04',
    title: 'Plinthworks dev launch post — v0.4 release',
    campaignSlug: 'acme',
    spaceSlug: 'plinthworks-workspace',
    briefText:
      'v0.4 ships staged rollouts and a new rollback API. The launch post lives on the Plinthworks blog and needs to sound like an engineer wrote it for engineers, not like marketing. Specific examples over claims, one screenshot of the staging diff, and a kill criterion line at the bottom: if you have never paged the on-call rotation, this release does nothing for you.',
    status: 'completed',
    queuedAt: dateInWeek(6, 3, 9, 0),
    startedAt: dateInWeek(6, 4, 10, 30),
    completedAt: dateInWeek(7, 4, 17, 0),
    subtasks: [
      { title: 'Sit on staging walkthrough with Plinthworks eng', done: true },
      { title: 'Draft post — engineer voice, no adjectives', done: true },
      { title: 'Devon embeds rollback API snippet', done: true },
      { title: 'Founder review (the "would I send this to a friend on-call" test)', done: true },
      { title: 'Ship to blog + cross-post to Hacker News at 9am ET', done: true },
    ],
    deliverableKinds: ['copy_doc'],
    assignedAgentName: 'Sara',
  },
  {
    slug: 'mission-plinthworks-docs-voice-audit',
    title: 'Plinthworks top-of-funnel docs voice audit',
    campaignSlug: 'acme',
    spaceSlug: 'plinthworks-workspace',
    briefText:
      "The first 200 pages of Plinthworks' docs are written by three different people in three different voices. New visitors hit the quickstart and immediately feel three different companies. Audit pages 1-50 first, flag every line that drifts off the v2 positioning, and propose a rewrite tier: must-fix, drift, leave alone. Sara leads; Maya signs off on the voice rubric.",
    status: 'in_progress',
    queuedAt: dateInWeek(11, 2, 14, 30),
    startedAt: dateInWeek(12, 1, 10, 0),
    subtasks: [
      { title: 'Define the 4-axis voice rubric', done: true },
      { title: 'Audit quickstart + first 10 concept pages', done: true },
      { title: 'Tag every drift line with tier (must-fix / drift / leave)', done: false },
      { title: 'Rewrite 5 sample pages to demo the tier system', done: false },
      { title: 'Loop in Plinthworks docs lead for approval flow', done: false },
    ],
    deliverableKinds: ['audit_doc'],
    assignedAgentName: 'Sara',
  },
  {
    slug: 'mission-plinthworks-q2-paid-experiment',
    title: 'Plinthworks Q2 paid experiment kickoff',
    campaignSlug: 'acme',
    spaceSlug: 'plinthworks-workspace',
    briefText:
      'One paid experiment per quarter — that is the retainer scope. Q2 hypothesis: the on-call engineer hangs out on Reddit r/sysadmin and r/devops, not LinkedIn. Two-week test, $4k spend cap, kill criterion is CAC > $1200 on day 10. Leo writes the test plan; founder approves the budget before a dollar gets spent.',
    status: 'in_progress',
    queuedAt: dateInWeek(12, 1, 11, 0),
    startedAt: dateInWeek(12, 3, 14, 0),
    subtasks: [
      { title: 'Write the two-page test plan (hypothesis, audience, kill)', done: true },
      { title: 'Build three creative variants — engineer voice only', done: true },
      { title: 'Founder + Plinthworks CMO budget approval', done: false },
      { title: 'Launch and pull session replays after 48 hours', done: false },
      { title: 'Day-10 read: CAC and 7-day cohort, kill or extend', done: false },
    ],
    deliverableKinds: ['campaign_plan'],
    assignedAgentName: 'Leo',
  },
  {
    slug: 'mission-plinthworks-marketing-site-copy-rewrite',
    title: 'Plinthworks marketing site copy rewrite',
    campaignSlug: 'acme',
    spaceSlug: 'plinthworks-workspace',
    briefText:
      'Now that the v2 position is live on the hero, every secondary page is off. Pricing reads like 2022, the "why" page is a wall of adjectives, the customers page lists logos with no story. Rewrite all five secondary pages against the v2 rubric. Riley schedules the read-throughs; founder reads the pricing page out loud as the test.',
    status: 'queued',
    queuedAt: dateInWeek(13, 0, 16, 30),
    subtasks: [
      { title: 'Inventory every secondary page + flag drift', done: false },
      { title: 'Rewrite pricing page first (highest-traffic)', done: false },
      { title: 'Rewrite why / customers / changelog / integrations', done: false },
      { title: 'Devon stages all five behind a flag', done: false },
      { title: 'Founder reads pricing out loud — go / no-go', done: false },
    ],
    deliverableKinds: ['copy_doc'],
    assignedAgentName: 'Sara',
  },

  // ── SALTLINE & CO (beta) — 5 missions ───────────────────────────────────
  {
    slug: 'mission-saltline-q4-holiday-calendar',
    title: 'Saltline Q4 holiday calendar',
    campaignSlug: 'beta',
    spaceSlug: 'saltline-workspace',
    briefText:
      'Saltline\'s Q4 is the bulk of the year. We own the calendar end-to-end — twelve drops from late September through New Year\'s, each one needs a story (not a sale), a photograph, and a lifecycle email. Maya sets the throughline ("a shared table in low light"), Sara writes the stories, Casey directs the photography. No discount-stack messaging.',
    status: 'completed',
    queuedAt: dateInWeek(4, 1, 11, 0),
    startedAt: dateInWeek(5, 1, 10, 0),
    completedAt: dateInWeek(8, 2, 17, 30),
    subtasks: [
      { title: 'Map twelve drops to a single throughline', done: true },
      { title: 'Sara: short story per drop (60-90 words)', done: true },
      { title: 'Casey: photography brief per drop', done: true },
      { title: 'Lifecycle email per drop, no discount stacking', done: true },
      { title: 'Client approval — Saltline founder reads it back', done: true },
      { title: 'Hand off to Saltline ops for scheduling', done: true },
    ],
    deliverableKinds: ['campaign_plan', 'email'],
    assignedAgentName: 'Maya',
  },
  {
    slug: 'mission-saltline-pantry-small-batch-story',
    title: 'Saltline pantry — small batch line story',
    campaignSlug: 'beta',
    spaceSlug: 'saltline-workspace',
    briefText:
      'New product story for the small-batch pantry line — five SKUs, hand-tied to the farm that grows the olives. Sara writes the long-form story for the product page; Casey directs a low-light still-life set. The voice has to feel lived-in, not curated. The word "artisanal" appears nowhere on the page.',
    status: 'completed',
    queuedAt: dateInWeek(7, 2, 11, 0),
    startedAt: dateInWeek(8, 1, 10, 0),
    completedAt: dateInWeek(10, 3, 16, 0),
    subtasks: [
      { title: 'Visit transcripts from Saltline founder — pull verbatim', done: true },
      { title: 'Long-form story (600 words) for the product page', done: true },
      { title: 'Casey directs the photo set — five stills, low light', done: true },
      { title: 'Three short-form variations for email + social', done: true },
      { title: 'Founder + Saltline approval', done: true },
    ],
    deliverableKinds: ['copy_doc', 'media_asset'],
    assignedAgentName: 'Sara',
  },
  {
    slug: 'mission-saltline-photography-direction-refresh',
    title: 'Saltline photography direction refresh',
    campaignSlug: 'beta',
    spaceSlug: 'saltline-workspace',
    briefText:
      "Saltline's photography has been drifting toward overhead-shot, white-background, every-DTC-brand for six months. Casey rebuilds the direction document around three rules: shoot in low light, shoot at the table not the studio, never shoot the product alone. Refresh the Figma library and document the new approval flow with the Saltline in-house photographer.",
    status: 'in_progress',
    queuedAt: dateInWeek(11, 4, 14, 0),
    startedAt: dateInWeek(12, 1, 10, 30),
    subtasks: [
      { title: 'Audit last 6 months of Saltline shots', done: true },
      { title: 'Draft three-rule direction document', done: true },
      { title: 'Build Figma library with reference grids', done: false },
      { title: 'Sample shoot with in-house photographer — pressure test', done: false },
      { title: 'Document approval flow + sign-off', done: false },
    ],
    deliverableKinds: ['design_system'],
    assignedAgentName: 'Casey',
  },
  {
    slug: 'mission-saltline-lifecycle-email-rewrite',
    title: 'Saltline lifecycle email rewrite',
    campaignSlug: 'beta',
    spaceSlug: 'saltline-workspace',
    briefText:
      'The welcome series and the post-purchase series both sound like a 2021 Klaviyo template. Sara rewrites both end-to-end — welcome is 4 emails, post-purchase is 6 emails. Voice rule: sensory, unhurried, no "your journey" language. Riley pulls the open and click rates after two weeks live.',
    status: 'in_progress',
    queuedAt: dateInWeek(12, 0, 9, 30),
    startedAt: dateInWeek(12, 2, 11, 0),
    subtasks: [
      { title: 'Read the existing 10 emails + open / click data', done: true },
      { title: 'Welcome series rewrite — 4 emails', done: true },
      { title: 'Post-purchase series rewrite — 6 emails', done: false },
      { title: 'Devon wires up the new flows in Klaviyo', done: false },
      { title: 'Two-week read on open / click delta', done: false },
    ],
    deliverableKinds: ['email', 'sequence'],
    assignedAgentName: 'Sara',
  },
  {
    slug: 'mission-saltline-scope-rewrite',
    title: 'Saltline scope rewrite — kitchenware expansion',
    campaignSlug: 'beta',
    spaceSlug: 'saltline-workspace',
    briefText:
      "Saltline asked us in Week 3 to take on their new kitchenware line on top of the existing retainer — separate brand voice, separate calendar, separate photography. Maya scoped it; the retro showed it would have doubled the retainer's footprint for the same fee. Jules killed it in Week 4 and we held the line on scope. Keeping the mission on record so the next retainer expansion ask routes through Owen first.",
    status: 'cancelled',
    queuedAt: dateInWeek(3, 4, 10, 30),
    startedAt: dateInWeek(4, 1, 11, 0),
    subtasks: [
      { title: 'Initial scoping doc — kitchenware voice exploration', done: true },
      { title: 'Calendar + fee delta proposal', done: true },
      { title: 'Retro: this is a separate retainer, not a tweak', done: true },
      { title: 'Communicate the no to Saltline founder', done: false },
      { title: 'Loop into pricing playbook so we hold the line', done: false },
    ],
    deliverableKinds: [],
    assignedAgentName: 'Owen',
  },

  // ── HELMSMARK (gamma) — 4 missions ──────────────────────────────────────
  {
    slug: 'mission-helmsmark-controller-repositioning-narrative',
    title: 'Helmsmark controller repositioning narrative',
    campaignSlug: 'gamma',
    spaceSlug: 'helmsmark-workspace',
    briefText:
      'Helmsmark\'s pre-Foundry positioning was "small-business banking app for solo founders." The actual buyer is the controller at a 50-200 person company, and the founder-led copy was scaring them away. Maya rebuilds the narrative around reconciliation, cash position visibility, and audit trail. Nico runs the controller interviews; we cite three of them verbatim in the brief.',
    status: 'completed',
    queuedAt: dateInWeek(7, 1, 10, 0),
    startedAt: dateInWeek(8, 1, 11, 0),
    completedAt: dateInWeek(11, 2, 17, 0),
    subtasks: [
      { title: 'Nico runs 6 controller interviews', done: true },
      { title: 'Maya synthesizes pain points — close week, variance, audit', done: true },
      { title: 'Draft three positioning candidates', done: true },
      { title: 'Pressure-test with Helmsmark CFO + a controller advisor', done: true },
      { title: 'Lock the v2 narrative + decision log entry', done: true },
      { title: 'Brief Devon + Sara for the site rewrite', done: true },
    ],
    deliverableKinds: ['positioning'],
    assignedAgentName: 'Maya',
  },
  {
    slug: 'mission-helmsmark-new-site-ia-copy',
    title: 'Helmsmark new site — IA + copy',
    campaignSlug: 'gamma',
    spaceSlug: 'helmsmark-workspace',
    briefText:
      'Site rebuild against the v2 controller position. New IA: home, product (reconciliation / cash position / audit trail), pricing, security, customers, blog. Sara writes the copy; Devon builds the components and stages the rebuild behind a flag. Hard rule: never the word "frictionless", never the phrase "next-gen banking".',
    status: 'in_progress',
    queuedAt: dateInWeek(11, 3, 10, 0),
    startedAt: dateInWeek(12, 0, 9, 0),
    subtasks: [
      { title: 'IA spec + sitemap signed off', done: true },
      { title: 'Sara: home + product copy v1', done: true },
      { title: 'Casey: type scale + grid for the new site', done: true },
      { title: 'Devon: component library + flag-gated stage', done: false },
      { title: 'Pricing + security + customers pages', done: false },
      { title: 'SOC 2 page in the controller voice', done: false },
      { title: 'Launch dress rehearsal with Helmsmark eng', done: false },
    ],
    deliverableKinds: ['site', 'copy_doc'],
    assignedAgentName: 'Devon',
  },
  {
    slug: 'mission-helmsmark-controller-persona-research-synthesis',
    title: 'Helmsmark controller persona research synthesis',
    campaignSlug: 'gamma',
    spaceSlug: 'helmsmark-workspace',
    briefText:
      "Nico has six full interview transcripts and four ride-along call notes. Need a single synthesis doc that names the controller's three sharpest pain points, the language they use about each, and a one-page reference Sara can keep on her desk while writing. Maya owns the synthesis; Nico signs off before it leaves the room.",
    status: 'queued',
    queuedAt: dateInWeek(13, 1, 10, 30),
    subtasks: [
      { title: 'Re-read all 6 transcripts + 4 ride-along notes', done: false },
      { title: 'Tag every line by pain bucket', done: false },
      { title: 'Draft synthesis — three pains, verbatim phrases, blind spots', done: false },
      { title: 'Nico pressure-test before circulation', done: false },
    ],
    deliverableKinds: ['research_synthesis'],
    assignedAgentName: 'Maya',
  },
  {
    slug: 'mission-helmsmark-series-a-launch-case-study',
    title: 'Helmsmark Series-A launch case study',
    campaignSlug: 'gamma',
    spaceSlug: 'helmsmark-workspace',
    briefText:
      "Helmsmark's Series-A is announcing in 3 weeks. The case study we are building is the public story of how the controller repositioning unlocked the round. Not a brag piece — a working document about the repositioning bet, what it cost to make, and what the close-rate delta looked like. Sara writes; founder signs off on the numbers before publication.",
    status: 'queued',
    queuedAt: dateInWeek(13, 0, 14, 0),
    subtasks: [
      { title: 'Source the close-rate delta numbers from Helmsmark', done: false },
      { title: 'Draft the case study (1500 words, founder voice)', done: false },
      { title: 'Casey: cover image + pull-quote layout', done: false },
      { title: 'Devon stages the case study page', done: false },
      { title: 'Lock embargo with Helmsmark PR', done: false },
    ],
    deliverableKinds: ['case_study'],
    assignedAgentName: 'Sara',
  },

  // ── CLOVERKIN HEALTH (delta) — 4 missions ───────────────────────────────
  {
    slug: 'mission-cloverkin-care-navigator-hero-offer',
    title: 'Cloverkin care navigator — hero offer',
    campaignSlug: 'delta',
    spaceSlug: 'cloverkin-workspace',
    briefText:
      'Cloverkin\'s care navigator is the unique part of the product — a real human who follows your care plan with you between visits. The current site buries it. Maya builds the hero around the navigator as the offer: name them, show them, quote a member back to the visitor. No "wellness journey" copy. Sara writes the lines, Casey shoots the navigator portrait.',
    status: 'completed',
    queuedAt: dateInWeek(8, 2, 10, 0),
    startedAt: dateInWeek(9, 1, 11, 0),
    completedAt: dateInWeek(11, 4, 16, 0),
    subtasks: [
      { title: 'Sit on 3 navigator-led calls (with consent)', done: true },
      { title: 'Pull verbatim quotes from member feedback', done: true },
      { title: 'Draft hero offer — name, photo, one-line promise', done: true },
      { title: 'Casey shoots navigator portraits — warm, clinical, lived-in', done: true },
      { title: 'Cloverkin medical director review', done: true },
      { title: 'Devon swaps the hero behind a flag for split test', done: true },
    ],
    deliverableKinds: ['offer', 'media_asset'],
    assignedAgentName: 'Maya',
  },
  {
    slug: 'mission-cloverkin-new-patient-onboarding-sequence',
    title: 'Cloverkin new-patient onboarding sequence',
    campaignSlug: 'delta',
    spaceSlug: 'cloverkin-workspace',
    briefText:
      'From sign-up to first visit, a Cloverkin member gets 7 touchpoints — 4 emails, 2 SMS, 1 navigator call script. The current sequence reads like a SaaS app, not a clinic. Sara rewrites in the warm-clinical voice with one rule: never the word "consumer." Riley coordinates with the Cloverkin care team for accuracy on every clinical claim.',
    status: 'in_progress',
    queuedAt: dateInWeek(11, 1, 11, 0),
    startedAt: dateInWeek(12, 0, 10, 0),
    subtasks: [
      { title: 'Map the 7 touchpoints + current copy audit', done: true },
      { title: 'Draft 4 emails — warm, clinical, no SaaS voice', done: true },
      { title: 'Draft 2 SMS', done: false },
      { title: 'Navigator call script — what the human says when they call', done: false },
      { title: 'Cloverkin clinical review on every claim', done: false },
      { title: 'Devon wires up the sequence + tracking', done: false },
    ],
    deliverableKinds: ['sequence', 'email'],
    assignedAgentName: 'Sara',
  },
  {
    slug: 'mission-cloverkin-three-metros-launch-site',
    title: 'Cloverkin three-metros launch site',
    campaignSlug: 'delta',
    spaceSlug: 'cloverkin-workspace',
    briefText:
      'Cloverkin is launching in Boston, Providence, and Hartford in 5 weeks. Each metro needs its own page — locations, in-network plans, navigator names, member testimonial. Devon builds the city-page template once, Sara writes the three variants. Hard rule: never just swap the city name and call it three pages.',
    status: 'in_progress',
    queuedAt: dateInWeek(11, 4, 10, 0),
    startedAt: dateInWeek(12, 1, 10, 0),
    subtasks: [
      { title: 'City page template — fields + variants', done: true },
      { title: 'Devon builds the template + flag-gated stage', done: true },
      { title: 'Sara writes Boston page first (the launch market)', done: false },
      { title: 'Providence + Hartford variants', done: false },
      { title: 'Casey: hero photo direction per metro', done: false },
      { title: 'Cloverkin compliance review on in-network claims', done: false },
    ],
    deliverableKinds: ['site'],
    assignedAgentName: 'Devon',
  },
  {
    slug: 'mission-cloverkin-member-copy-system',
    title: 'Cloverkin member-facing copy system',
    campaignSlug: 'delta',
    spaceSlug: 'cloverkin-workspace',
    briefText:
      'Once the three metros launch, member-facing copy starts piling up — appointment reminders, post-visit follow-ups, after-hours scripts, billing notices. Sara designs the system: tone rubric, 12 base templates, the rule for when to use which. The system has to survive a Tuesday — no agent should have to ask Maya before sending a reminder.',
    status: 'queued',
    queuedAt: dateInWeek(13, 1, 11, 0),
    subtasks: [
      { title: 'Tone rubric — warm, clinical, plainspoken', done: false },
      { title: '12 base templates covering the common touchpoints', done: false },
      { title: 'Decision tree: which template when', done: false },
      { title: 'Train Cloverkin ops on the system', done: false },
    ],
    deliverableKinds: ['copy_system'],
    assignedAgentName: 'Sara',
  },

  // ── THROUGHPUT GROUP (epsilon) — 3 missions ─────────────────────────────
  {
    slug: 'mission-throughput-service-line-repackage-v1',
    title: 'Throughput service line repackage v1',
    campaignSlug: 'epsilon',
    spaceSlug: 'throughput-workspace',
    briefText:
      'Throughput has six service lines today and three of them overlap. The site reads like a capabilities deck. Maya leads the repackage into a clear hierarchy — three flagship service lines, two specialty, one labs. Riley coordinates with Throughput practice leads; final hierarchy gets signed off in writing before any copy lands.',
    status: 'in_progress',
    queuedAt: dateInWeek(11, 1, 14, 0),
    startedAt: dateInWeek(11, 3, 10, 30),
    subtasks: [
      { title: 'Map the 6 lines + overlap matrix', done: true },
      { title: 'Interview each of the 6 practice leads', done: true },
      { title: 'Draft three flagship / two specialty / one labs hierarchy', done: true },
      { title: 'Pressure-test with Throughput COO + CFO', done: false },
      { title: 'Lock the hierarchy in writing', done: false },
      { title: 'Brief Sara for the new service-line copy', done: false },
    ],
    deliverableKinds: ['positioning', 'service_taxonomy'],
    assignedAgentName: 'Maya',
  },
  {
    slug: 'mission-throughput-proposal-kit-rewrite',
    title: 'Throughput proposal kit rewrite',
    campaignSlug: 'epsilon',
    spaceSlug: 'throughput-workspace',
    briefText:
      "Throughput's current proposal kit is a 40-page deck the partners have not opened in a year. New kit is 8 pages — diagnosis, recommended pod, gross-margin assumption, billable plan, kill criteria, scope, fee, next step. Sara writes; Casey sets the type. Hard rule: every proposal goes out under the v1 hierarchy or it does not go out.",
    status: 'in_progress',
    queuedAt: dateInWeek(12, 1, 10, 0),
    startedAt: dateInWeek(12, 2, 14, 0),
    subtasks: [
      { title: 'Audit last 12 Throughput proposals — win / loss reasons', done: true },
      { title: 'Outline the 8-page structure', done: true },
      { title: 'Sara: write the 4 narrative sections', done: false },
      { title: 'Casey: type + grid + cover treatment', done: false },
      { title: 'Devon stages an editable template in their CRM', done: false },
      { title: 'Sample dry-run on a current Throughput pipeline deal', done: false },
    ],
    deliverableKinds: ['proposal_kit'],
    assignedAgentName: 'Sara',
  },
  {
    slug: 'mission-throughput-coo-outbound-sequence',
    title: 'Throughput COO outbound sequence',
    campaignSlug: 'epsilon',
    spaceSlug: 'throughput-workspace',
    briefText:
      "Outbound program targeting COOs at 200-1000 person services firms. Five-touch sequence, no spray. Leo builds the audience, Sara writes the lines, Riley coordinates with Throughput's SDR. Kill criterion: reply rate under 6% by week 4 and we kill the sequence and start over.",
    status: 'queued',
    queuedAt: dateInWeek(13, 0, 11, 0),
    subtasks: [
      { title: 'Leo: build the 200-1000 person services firm audience', done: false },
      { title: 'Sara: five-touch sequence in the COO voice', done: false },
      { title: 'Riley: SDR brief + reply routing', done: false },
      { title: 'Launch + week-2 read on reply rate', done: false },
      { title: 'Week-4 kill or extend decision', done: false },
    ],
    deliverableKinds: ['sequence'],
    assignedAgentName: 'Leo',
  },

  // ── ALMANAC LEARNING (zeta) — 3 missions ────────────────────────────────
  {
    slug: 'mission-almanac-public-reading-list-inbound-asset',
    title: 'Almanac public reading list as inbound asset',
    campaignSlug: 'zeta',
    spaceSlug: 'almanac-workspace',
    briefText:
      'Almanac mentors curate reading lists for every cohort. Right now they live in private Notion. The bet: publish the reading lists publicly with the mentor commentary, and they become the inbound channel. Sara structures the format, Devon builds the template, Maya signs off on which lists are public vs members-only.',
    status: 'completed',
    queuedAt: dateInWeek(11, 1, 10, 0),
    startedAt: dateInWeek(11, 3, 11, 0),
    completedAt: dateInWeek(12, 4, 16, 0),
    subtasks: [
      { title: 'Inventory all mentor reading lists across cohorts', done: true },
      { title: 'Define the public list format — book, why, mentor note', done: true },
      { title: 'Devon: reading list page template', done: true },
      { title: 'Publish 4 lists from the writing cohort first', done: true },
      { title: 'Two-week read on referral traffic', done: true },
    ],
    deliverableKinds: ['site', 'copy_doc'],
    assignedAgentName: 'Sara',
  },
  {
    slug: 'mission-almanac-adult-writing-cohort-landing-page',
    title: 'Almanac adult writing cohort landing page',
    campaignSlug: 'zeta',
    spaceSlug: 'almanac-workspace',
    briefText:
      'The next adult writing cohort starts in 6 weeks. The current landing page reads like every cohort-based course on the internet — "unlock your writing potential" type copy. Sara rewrites for the actual buyer: a 35-year-old who has wanted to write a book for a decade and has been burned by two writing programs already. Specific, generous, plain.',
    status: 'in_progress',
    queuedAt: dateInWeek(12, 0, 10, 0),
    startedAt: dateInWeek(12, 1, 11, 0),
    subtasks: [
      { title: 'Read Almanac alum interviews — the burned-twice pattern', done: true },
      { title: 'Draft the page hero + sub-hed', done: true },
      { title: 'Mentor bios in their own voice (not template)', done: false },
      { title: 'Syllabus block — rubric, office hours, Sunday review', done: false },
      { title: 'Devon: page build + flag', done: false },
      { title: 'Founder reads it aloud test', done: false },
    ],
    deliverableKinds: ['site', 'copy_doc'],
    assignedAgentName: 'Devon',
  },
  {
    slug: 'mission-almanac-mentor-matching-email-sequence',
    title: 'Almanac mentor matching email sequence',
    campaignSlug: 'zeta',
    spaceSlug: 'almanac-workspace',
    briefText:
      'After sign-up, a learner gets matched with a mentor in 7 days. The matching email sequence currently sends three identical templates. New sequence: a personal intro from the matched mentor in their own voice, a syllabus walk, and a Sunday-review preview. Three emails, one per voice axis.',
    status: 'queued',
    queuedAt: dateInWeek(13, 1, 9, 30),
    subtasks: [
      { title: 'Outline the three-email sequence', done: false },
      { title: 'Mentor-voice templates (4 mentors × 3 emails)', done: false },
      { title: 'Sunday-review preview email', done: false },
      { title: 'Devon: sequence wiring + tracking', done: false },
    ],
    deliverableKinds: ['sequence', 'email'],
    assignedAgentName: 'Sara',
  },

  // ── INTERNAL OPS — 2 missions ────────────────────────────────────────────
  {
    slug: 'mission-ops-new-retainer-sop',
    title: 'New retainer SOP — kickoff to week-2',
    campaignSlug: 'internal-ops',
    briefText:
      "Owen's first big mission as Ops Lead: write the SOP for spinning up a new retainer. Every kickoff up to now has been improvised. New SOP covers the kickoff doc, the first interview cadence, the channel spin-up, the first retro at day 14, and the scope-creep tripwires. Run it once on the next retainer and tune.",
    status: 'completed',
    queuedAt: dateInWeek(12, 1, 10, 0),
    startedAt: dateInWeek(12, 2, 9, 30),
    completedAt: dateInWeek(13, 0, 17, 0),
    subtasks: [
      { title: 'Interview Jules + Riley on what actually happens on Monday', done: true },
      { title: 'Pull the last 4 retainer kickoffs — what worked / failed', done: true },
      { title: 'Draft the SOP — 8 pages, no longer', done: true },
      { title: 'Add the scope-creep tripwires section', done: true },
      { title: 'Jules + founder sign-off', done: true },
    ],
    deliverableKinds: ['sop'],
    assignedAgentName: 'Owen',
  },
  {
    slug: 'mission-ops-weekly-status-template-overhaul',
    title: 'Weekly status template overhaul',
    campaignSlug: 'internal-ops',
    briefText:
      'The current Friday status note across all 6 clients is a wall of bullet points. Half of them go unread. Riley redesigns to a one-screen format: what shipped, what is in flight, what is blocked, and the one decision we need from the client this week. Test on Plinthworks + Helmsmark first.',
    status: 'in_progress',
    queuedAt: dateInWeek(13, 0, 11, 0),
    startedAt: dateInWeek(13, 1, 10, 0),
    subtasks: [
      { title: 'Audit last 4 Friday notes per client — what got opened', done: true },
      { title: 'Draft the one-screen format', done: true },
      { title: 'Run on Plinthworks + Helmsmark this Friday', done: false },
      { title: 'Read open / reply rates after two weeks', done: false },
      { title: 'Roll out to all 6 retainers or revise', done: false },
    ],
    deliverableKinds: ['sop', 'template'],
    assignedAgentName: 'Riley',
  },

  // ── SALES / PIPELINE — 2 missions ───────────────────────────────────────
  {
    slug: 'mission-sales-cold-outbound-playbook-icp',
    title: 'Cold outbound playbook for ICP',
    campaignSlug: 'sales',
    spaceSlug: 'pipeline',
    briefText:
      'Foundry has a tight ICP — founder-led companies between Series A and Series B who refuse to sound like their competitors. The playbook codifies how we reach them: where they actually read, what the first message says, and the kill criterion for a sequence. Riley + founder author; goal is to disqualify fast, not to fill the top.',
    status: 'completed',
    queuedAt: dateInWeek(11, 0, 11, 0),
    startedAt: dateInWeek(12, 0, 10, 0),
    completedAt: dateInWeek(13, 1, 16, 30),
    subtasks: [
      { title: 'Define the ICP in two sentences', done: true },
      { title: 'Channel map — newsletters, podcasts, two Slacks', done: true },
      { title: 'First-touch message templates (3 variants)', done: true },
      { title: 'Disqualification criteria + Riley routing rules', done: true },
      { title: 'Run the playbook on 12 prospects in week-13', done: true },
    ],
    deliverableKinds: ['playbook'],
    assignedAgentName: 'Riley',
  },
  {
    slug: 'mission-sales-discovery-call-framework',
    title: 'Discovery call framework',
    campaignSlug: 'sales',
    spaceSlug: 'pipeline',
    briefText:
      'Every discovery call up to now is whatever the founder feels like asking that day. We need a structure that gets us to "is this the right retainer" or "this is a project" by minute 30. Maya designs; the framework includes the three positioning questions, two operating questions, and one hard scope question we will not skip.',
    status: 'in_progress',
    queuedAt: dateInWeek(12, 1, 14, 0),
    startedAt: dateInWeek(13, 0, 10, 0),
    subtasks: [
      { title: 'Pull the last 8 discovery calls — what we learned vs missed', done: true },
      { title: 'Draft the three positioning questions', done: true },
      { title: 'Draft the two operating questions', done: false },
      { title: 'The one hard scope question — never skip', done: false },
      { title: 'Run the framework on next 3 discovery calls and tune', done: false },
    ],
    deliverableKinds: ['playbook'],
    assignedAgentName: 'Maya',
  },

  // ── WIKI — 2 missions ────────────────────────────────────────────────────
  {
    slug: 'mission-wiki-foundry-positioning-principles-page',
    title: 'Foundry positioning principles — wiki page',
    campaignSlug: 'wiki',
    briefText:
      'The principles we keep saying out loud on every retainer call but have never written down. Maya synthesizes from the founder narrative + the first 9 weeks of channel transcripts. Output is one page, 9 principles, each with one example we lived through. Goal is the doc a new agent reads in their first week and stops asking which Foundry is.',
    status: 'completed',
    queuedAt: dateInWeek(8, 4, 14, 0),
    startedAt: dateInWeek(9, 1, 10, 0),
    completedAt: dateInWeek(11, 0, 17, 0),
    subtasks: [
      { title: 'Read first 9 weeks of #foundry-general transcripts', done: true },
      { title: 'Cluster recurring positions into principle candidates', done: true },
      { title: 'Draft the 9 principles + one example each', done: true },
      { title: 'Founder + Nico pressure-test every principle', done: true },
      { title: 'Lock in the wiki + link from new-agent onboarding', done: true },
    ],
    deliverableKinds: ['principles_doc'],
    assignedAgentName: 'Maya',
  },
  {
    slug: 'mission-wiki-anti-pattern-catalog',
    title: 'Anti-pattern catalog',
    campaignSlug: 'wiki',
    briefText:
      'Cortex crystallized the first anti-pattern in Week 9 ("Async approvals burn trust"). Owen wants the catalog: every anti-pattern we have named so far, with the moment it formed, the symptom that triggered it, and the protocol we put in place. Living document, owned by Ops.',
    status: 'queued',
    queuedAt: dateInWeek(13, 1, 11, 30),
    subtasks: [
      { title: 'Pull every anti_pattern cortex object', done: false },
      { title: 'Map each to the formation moment + symptom', done: false },
      { title: 'Document the protocol that replaced it', done: false },
      { title: 'Owen owns + reviews monthly', done: false },
    ],
    deliverableKinds: ['catalog'],
    assignedAgentName: 'Owen',
  },
]
