/** User-facing copy for Space workflows (internal: `space_automations`). */
export const FLOWS_UI = {
  feature: 'Flows',
  featureSingular: 'Flow',
  browseTab: 'Browse',
  myLoopsLabel: 'My Loops',
  myTemplatesLabel: 'My templates',
  allTemplatesLabel: 'All templates',
  manageTab: 'Manage',
  buildTab: 'Build',
  clarificationsTab: 'Clarifications',
  addFlow: 'Add flow',
  new: 'New flow',
  create: 'Create flow',
  loading: 'Loading flows...',
  emptyList: 'No flows yet. Create one to run workflows in this space.',
  emptyFilter: 'No flows match your filters or search.',
  manageEmptyTitle: 'No flows yet',
  manageEmptyDescription: 'Create one to run workflows in this space.',
  manageFilterEmptyTitle: 'No flows match your filters',
  manageFilterEmptyDescription: 'Try another search or loosen the filters to bring them back.',
  draftsSection: 'Drafts',
  openPlan: 'Plan',
  openDraft: 'Draft',
  openSession: 'Session',
  noBuildSession: 'No Loop build linked to this draft.',
  noConversation: 'No Loop conversation linked to this draft.',
  noCompiledDraft: 'No compiled draft yet — finish the Loop build first.',
  draftEnableTooltip: 'Finish the draft and publish to turn this loop on.',
  draftEnableBlocked: "You can't turn it on until you publish this draft.",
  saveAndUpdate: 'Save and update',
  savingUpdate: 'Saving…',
  flowUpdated: 'Flow updated',
  loopBuildInProgress: 'Loop build in progress',
  allCampaigns: 'All campaigns',
  allSpaces: 'All spaces',
  filterByCampaign: 'Filter by campaign',
  filterBySpace: 'Filter by space',
  selectSpaceForLoop: 'Choose a space above to build with Loop.',
  selectSpaceForBrowse: 'Select a space to install or create a flow.',
  selectSpaceForHistory: 'Select a space to narrow flow run history.',
  createAnythingLabel: 'Create anything',
  createAnythingTooltip: 'Create flows without having to assign them to a space.',
  createAnythingHint: 'Build and test flow concepts here. Turn off to assign flows to a Space.',
  assignToSpaceLabel: 'Assign to Space',
  flowNotAssigned: 'Not assigned to a space',
  flowScopeMultipleCampaigns: 'Multiple campaigns',
  flowScopeMultipleSpaces: '{count} spaces',
  flowScopeInstalledIn: 'Installed in',
  flowScopeCampaignTooltip: 'Campaign this loop belongs to.',
  flowScopeSpaceTooltip: 'Space this loop runs in. Click to focus that scope.',
  flowScopeSpacesAria: 'Spaces this loop is installed in',
  browseTemplatesTitle: 'Browse flow templates',
  browseTemplatesDescription:
    'Browse every template. Select a space when you are ready to install one.',
  historyTitle: 'Flow history',
  historyDescription: 'Review flow runs across the selected campaign and space scope.',
  templatesEmptyTitle: 'No templates in this category',
  templatesEmptyDescription: 'Try another category or start a blank flow for this space.',
  myTemplatesEmptyTitle: 'No templates yet',
  myTemplatesEmptyDescription:
    'Open a loop in My Loops, use the menu, and choose Make as template to save one here.',
  noRuns: 'No flow runs yet.',
  noRunsForFilters: 'No run history matches these filters.',
  noCampaign: 'No campaign',
  unknownSpace: 'Unknown space',
  completedCard: 'Completed flows',
  completedEmpty: 'No completed flows yet in your Spaces.',
  fallbackRunName: 'Flow',
  flowRuns: 'Flow runs',
  updateFailed: 'Could not update flow — try again.',
  legacySchedule:
    'This flow uses a legacy cron expression. Pick a repeat pattern below to replace it',
  addDescription: '+ Add description',
  descriptionPlaceholder: 'Add a description…',
  searchAria: 'Search flows',
  filtersAria: 'Flow filters',
  incompleteOnlyAria: 'Show incomplete flows only',
  actionsAria: 'Flow actions',
  activityLabel: 'Flow',
  activityAction: 'Flow action',
  activityRanAction: 'ran flow action',
} as const
