export const INBOX_MESSAGES = {
  TITLE: 'Inbox',
  SUBTITLE: 'Everything that needs your attention, sorted and ready.',
  LOADING: 'Pulling your inbox together…',
  VIEWS: {
    primary: 'Primary',
    other: 'Other',
    later: 'Later',
    cleared: 'Cleared',
  },
  FILTER: {
    label: 'Filter by type',
    all: 'All types',
    search: 'Search this view',
  },
  DETAIL: {
    emptyTitle: 'Select something to review',
    emptyBody: 'Pick an inbox item and I’ll keep its context and actions right here.',
    context: 'Context',
    received: 'Received',
    location: 'Location',
    status: 'Inbox status',
    readState: 'Read state',
    read: 'Read',
    unread: 'Unread',
    inboxOnly: 'Inbox only',
    noBody: 'No extra note was included with this update.',
    back: 'Back to inbox',
  },
  EMPTY: {
    primary: 'Primary is clear. You’re all caught up.',
    other: 'Nothing else is waiting.',
    later: 'Nothing is snoozed right now.',
    cleared: 'Cleared items will show up here.',
    all: 'Your inbox is clear.',
    search: 'Nothing in this view matches that search.',
  },
  ACTIONS: {
    clear: 'Clear this item',
    restore: 'Bring this back',
    snooze: 'Save this for tomorrow',
    unsnooze: 'Bring this back now',
    read: 'Mark as read',
    unread: 'Mark as unread',
    open: 'Open details',
    source: 'View source',
    primary: 'Move to Primary',
    other: 'Move to Other',
    clearView: 'Clear this view',
    readAll: 'Mark everything read',
  },
  ERRORS: {
    load: "I couldn't load your inbox. Give it another shot?",
    update: "That change didn't stick. I put everything back—try once more?",
  },
} as const
