#!/usr/bin/env python3
"""Build assets/search-index.js for the ROAS wiki.

Walks every *.html page under documentation/wiki (except _template.html),
splits each page into sections at <h2>, and writes one JSON record per
section: page path, page title, section id, heading, tab, and plain text.
Run it after editing any wiki page:

    python3 documentation/wiki/tools/build-search-index.py
"""
from __future__ import annotations

import json
import os
import re
import sys
from html.parser import HTMLParser

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
OUT = os.path.join(ROOT, 'assets', 'search-index.js')
SKIP = {'_template.html'}


class Page(HTMLParser):
    """Collects title and per-<h2> sections of one wiki page."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.title = ''
        self._in_title = False
        self._in_wrap = 0
        self._depth = 0
        self._wrap_depth = None
        self._in_h2 = False
        self._skip = 0  # inside <script>/<style>/<aside>
        self.sections: list[dict] = [{'id': '', 'heading': 'Introduction', 'tab': 'Overview', 'text': []}]
        self._h2_buf: list[str] = []
        self._h2_count = 0

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        self._depth += 1
        if tag == 'title':
            self._in_title = True
        if tag in ('script', 'style', 'aside', 'nav'):
            self._skip += 1
        if tag == 'div' and a.get('class', '') == 'wrap' and self._wrap_depth is None:
            self._wrap_depth = self._depth
        if tag == 'h2' and self._wrap_depth is not None:
            self._in_h2 = True
            self._h2_buf = []
            self._h2_count += 1
            sid = a.get('id') or f'section-{self._h2_count}'  # same fallback id wiki.js assigns at runtime
            self.sections.append({'id': sid, 'heading': '', 'tab': a.get('data-tab') or 'Overview', 'text': []})
        if tag in ('p', 'li', 'tr', 'dt', 'dd', 'h3', 'div', 'br') and self._wrap_depth is not None:
            self.sections[-1]['text'].append(' ')

    def handle_endtag(self, tag):
        if tag == 'title':
            self._in_title = False
        if tag in ('script', 'style', 'aside', 'nav'):
            self._skip = max(0, self._skip - 1)
        if tag == 'h2' and self._in_h2:
            self._in_h2 = False
            h = re.sub(r'\s+', ' ', ''.join(self._h2_buf)).strip()
            h = re.sub(r'^(\d+|\?)\s+', '', h)
            self.sections[-1]['heading'] = h
        if self._wrap_depth is not None and self._depth == self._wrap_depth and tag == 'div':
            self._wrap_depth = -1  # closed
        self._depth -= 1

    def handle_data(self, data):
        if self._in_title:
            self.title += data
        if self._skip or self._wrap_depth is None or self._wrap_depth == -1:
            return
        if self._in_h2:
            self._h2_buf.append(data)
        self.sections[-1]['text'].append(data)


def build() -> list[dict]:
    records = []
    for dirpath, _dirs, files in os.walk(ROOT):
        for f in sorted(files):
            if not f.endswith('.html') or f in SKIP:
                continue
            path = os.path.join(dirpath, f)
            rel = os.path.relpath(path, ROOT).replace(os.sep, '/')
            p = Page()
            with open(path, encoding='utf-8') as fh:
                p.feed(fh.read())
            title = re.sub(r'\s*·\s*ROAS Wiki\s*$', '', p.title).strip()
            for sec in p.sections:
                text = re.sub(r'\s+', ' ', ''.join(sec['text'])).strip()
                if not text and not sec['heading']:
                    continue
                records.append({
                    'p': rel,
                    'pt': title,
                    'id': sec['id'],
                    'h': sec['heading'],
                    'tab': sec['tab'],
                    't': text,
                })
    return records


def main() -> int:
    records = build()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('// Generated by tools/build-search-index.py. Do not edit by hand.\n')
        fh.write('window.ROAS_WIKI_INDEX = ')
        json.dump(records, fh, ensure_ascii=False, separators=(',', ':'))
        fh.write(';\n')
    pages = len({r['p'] for r in records})
    print(f'wrote {OUT}: {len(records)} sections from {pages} pages')
    return 0


if __name__ == '__main__':
    sys.exit(main())
