import { z } from 'zod'
import {
  AgentCollaborationSchema,
  ArtifactKindSchema,
  AutomationAssigneeTargetSchema,
  BrainImportDomainSchema,
  ContinuationSchema,
  EmailArtifactSourceSchema,
  SendToAgentOutputTypeSchema,
  SocialResearchAutomationEnrichmentSchema,
  SocialResearchAutomationPlatformSchema,
  SocialResearchAutomationSyncModeSchema,
} from './space-automation-shared.dto'
import { SpacePrioritySchema } from './space-core.dto'

export const LooseAutomationActionSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('create_task'),
    title_template: z.string().optional(),
    status: z.string().optional(),
    assignees: z.array(AutomationAssigneeTargetSchema).max(50).optional(),
    assignee_type: z.enum(['human', 'agent', 'unassigned']).optional(),
    assignee_id: z.string().optional(),
    priority: SpacePrioritySchema.optional(),
    notes_template: z.string().optional(),
    field_values: z.record(z.string(), z.unknown()).optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('send_to_agent'),
    agent_key: z.string().optional(),
    prompt_template: z.string().optional(),
    inject_fields: z.array(z.string()).optional(),
    output_type: SendToAgentOutputTypeSchema.optional(),
    target_item_ref: z.string().optional(),
    extended_brain_knowledge: z.boolean().optional(),
    agent_collaboration: AgentCollaborationSchema.optional(),
    priority: SpacePrioritySchema.optional(),
    continuation: ContinuationSchema,
    completed_status: z.string().max(200).optional(),
  }),
  z.object({
    type: z.literal('send_to_agents'),
    prompt_template: z.string().optional(),
    agent_tasks: z
      .array(
        z.object({
          agent_key: z.string().optional(),
          prompt_template: z.string().optional(),
        }),
      )
      .max(10)
      .optional(),
    inject_fields: z.array(z.string()).optional(),
    target_item_ref: z.string().optional(),
    extended_brain_knowledge: z.boolean().optional(),
    agent_collaboration: AgentCollaborationSchema.optional(),
    priority: SpacePrioritySchema.optional(),
    continuation: ContinuationSchema,
    completed_status: z.string().max(200).optional(),
  }),
  z.object({
    type: z.literal('send_to_cursor'),
    connection_id: z.string().uuid().optional(),
    repo_url: z.string().optional(),
    base_branch: z.string().optional(),
    branch_name: z.string().optional(),
    prompt_template: z.string().optional(),
    model_id: z.string().optional(),
    inject_fields: z.array(z.string()).optional(),
    target_item_ref: z.string().optional(),
    priority: SpacePrioritySchema.optional(),
    continuation: ContinuationSchema,
    completed_status: z.string().max(200).optional(),
  }),
  z.object({
    type: z.literal('add_brain_context_to_task'),
    target_item_ref: z.string().optional(),
    query_template: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('agent_suggest_tasks'),
    agent_key: z.string().optional(),
    max_suggestions: z.number().int().min(1).max(20).optional(),
    instructions: z.string().optional(),
    extended_brain_knowledge: z.boolean().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('assign_to'),
    assignees: z.array(AutomationAssigneeTargetSchema).max(50).optional(),
    assignee_type: z.enum(['human', 'agent']).optional(),
    assignee_id: z.string().optional(),
    target_item_ref: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('change_status'),
    status: z.string().optional(),
    target_item_ref: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('change_priority'),
    priority: SpacePrioritySchema.optional(),
    target_item_ref: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('add_comment'),
    message_template: z.string().optional(),
    target_item_ref: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('human_gate'),
    target_item_ref: z.string().optional(),
    assignees: z.array(AutomationAssigneeTargetSchema).max(50).optional(),
    assignee_type: z.enum(['human', 'agent']).optional(),
    assignee_id: z.string().min(1).optional(),
    waiting_status: z.string().max(200).optional(),
    resume_on_status: z.string().max(200).optional(),
    reject_on_status: z.string().max(200).optional(),
    on_reject_goto_step_index: z.number().int().min(0).optional(),
    message_template: z.string().max(10000).optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('flow_loop'),
    target_step_index: z.number().int().min(0).optional(),
    when: z.enum(['on_reject', 'always']).optional(),
    max_iterations: z.number().int().min(1).max(20).optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('flow_branch'),
    field_id: z.string().optional(),
    operator: z.enum(['equals', 'not_equals', 'contains', 'is_empty', 'is_not_empty']).optional(),
    value: z.string().optional(),
    then_step_index: z.number().int().min(0).optional(),
    else_step_index: z.number().int().min(0).optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('send_email'),
    tool_slug: z.string().optional(),
    connected_account_id: z.string().optional(),
    to: z.string().optional(),
    subject_template: z.string().optional(),
    body_template: z.string().optional(),
    subject_source: EmailArtifactSourceSchema.optional(),
    email_artifact_id: z.string().uuid().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('send_slack_message'),
    channel_id: z.string().optional(),
    text_template: z.string().optional(),
    thread_ts: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('request_slack_follow_up_confirm'),
    meeting_scope: z.enum(['all', 'client']).optional(),
    delivery_mode: z.enum(['shadow', 'active']).optional(),
    channel_delivery: z.enum(['disabled', 'automatic']).optional(),
    destination_channel_id: z.string().optional(),
    dm_email: z.string().optional(),
    confirm_reaction: z.string().optional(),
    suggestion_ids: z.array(z.string()).optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('observe_slack_team'),
    loop_kind: z
      .enum([
        'brain_compounding',
        'workflow_discovery',
        'unanswered_questions',
        'client_risk',
        'all',
      ])
      .optional(),
    delivery_mode: z.enum(['shadow', 'active']).optional(),
    channel_ids: z.array(z.string()).max(200).optional(),
    person_ids: z.array(z.string()).max(500).optional(),
    lookback_minutes: z.number().int().min(5).max(1440).optional(),
    daily_limit: z.number().int().min(1).max(100).optional(),
    quiet_hours: z
      .object({
        start: z.string().optional(),
        end: z.string().optional(),
        timezone: z.string().optional(),
      })
      .optional(),
    instructions: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('send_channel_message'),
    channel_id: z.string().optional(),
    content_template: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('create_contact'),
    email_template: z.string().optional(),
    name_template: z.string().optional(),
    source: z.string().optional(),
    field_values: z.record(z.string(), z.string()).optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('update_contact_field'),
    contact_id: z.string().optional(),
    field_id: z.string().optional(),
    value_template: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('add_contact_tag'),
    contact_id: z.string().optional(),
    tag: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('remove_contact_tag'),
    contact_id: z.string().optional(),
    tag: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('attach_note_to_contact'),
    contact_id: z.string().optional(),
    content_template: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('link_item_to_contact'),
    contact_id: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('create_artifact'),
    artifact_kind: ArtifactKindSchema.optional(),
    title_template: z.string().optional(),
    campaign_id: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('publish_artifact'),
    artifact_kind: ArtifactKindSchema.optional(),
    artifact_id: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('unpublish_artifact'),
    artifact_kind: ArtifactKindSchema.optional(),
    artifact_id: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('ask_agent_to_improve_artifact'),
    artifact_kind: ArtifactKindSchema.optional(),
    artifact_id: z.string().optional(),
    agent_key: z.string().optional(),
    prompt_template: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('attach_artifact_to_item'),
    artifact_kind: ArtifactKindSchema.optional(),
    artifact_id: z.string().optional(),
    target_item_ref: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('create_subtask'),
    title_template: z.string().optional(),
    assignees: z.array(AutomationAssigneeTargetSchema).max(50).optional(),
    assignee_type: z.enum(['human', 'agent', 'unassigned']).optional(),
    assignee_id: z.string().optional(),
    target_item_ref: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('sync_social_research'),
    platform: SocialResearchAutomationPlatformSchema.optional(),
    sync_mode: SocialResearchAutomationSyncModeSchema.optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('select_social_outliers'),
    platform: SocialResearchAutomationPlatformSchema.optional(),
    min_outlier_score: z.number().min(0).max(100).optional(),
    limit: z.number().int().min(1).max(50).optional(),
    since_days: z.number().int().min(1).max(30).optional(),
    source_step: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('enrich_social_research_items'),
    enrichments: z.array(SocialResearchAutomationEnrichmentSchema).optional(),
    source_step: z.string().optional(),
    continuation: ContinuationSchema,
  }),
  z.object({
    type: z.literal('ingest_youtube_channel_to_agent_brain'),
    agent_key: z.string().min(1).optional(),
    brain_id: z.string().uuid().optional(),
    channel_urls: z.array(z.string().min(1).max(500)).max(10).optional(),
    since_days: z.number().int().min(1).max(30).optional(),
    max_videos_per_channel: z.number().int().min(1).max(200).optional(),
    include_shorts: z.boolean().optional(),
    domain: BrainImportDomainSchema.optional(),
    continuation: ContinuationSchema,
  }),
  z.object({ type: z.literal('choose_action'), continuation: ContinuationSchema }),
])
