/**
 * GoHighLevel legacy capabilities: email builder, schedules, forms, funnels.
 */
import type { GhlLegacyRow } from './ghl-legacy-capabilities.shared.partial'
import { p } from './ghl-legacy-capabilities.shared.partial'

export const GHL_LEGACY_EMAIL_FORMS_FUNNELS_CAPABILITY_ENTRIES: GhlLegacyRow[] = [
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_email_builder_templates',
    execution_mode: 'legacy',
    display_name: 'List GHL Email Builder Templates',
    description: 'List email templates from the GHL email builder.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_email_builder_template',
    execution_mode: 'legacy',
    display_name: 'Get GHL Email Builder Template',
    description: 'Get a single email builder template by templateId.',
    parameters: p({ templateId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_email_schedules',
    execution_mode: 'legacy',
    display_name: 'List GHL Email Schedules',
    description: 'List scheduled email sends (emails/schedule.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_forms',
    execution_mode: 'legacy',
    display_name: 'List GHL Forms',
    description: 'List capture forms in the GoHighLevel location.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_form',
    execution_mode: 'legacy',
    display_name: 'Get GHL Form',
    description: 'Get form configuration and fields by formId.',
    parameters: p({ formId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_funnels',
    execution_mode: 'legacy',
    display_name: 'List GHL Funnels',
    description: 'List funnels for landing pages and sales flows (funnels/funnel.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_funnel_pages',
    execution_mode: 'legacy',
    display_name: 'List GHL Funnel Pages',
    description: 'List pages inside funnels.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_funnel_page',
    execution_mode: 'legacy',
    display_name: 'Get GHL Funnel Page',
    description: 'Get funnel page details by pageId.',
    parameters: p({ pageId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_funnel_redirects',
    execution_mode: 'legacy',
    display_name: 'List GHL Funnel Redirects',
    description: 'List URL redirects configured for funnels.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_funnel_redirect',
    execution_mode: 'legacy',
    display_name: 'Create GHL Funnel Redirect',
    description: 'Create a funnel redirect rule.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
]
