/**
 * GoHighLevel legacy capabilities: calendars and scheduling.
 */
import type { GhlLegacyRow } from './ghl-legacy-capabilities.shared.partial'
import { p } from './ghl-legacy-capabilities.shared.partial'

export const GHL_LEGACY_CALENDARS_CAPABILITY_ENTRIES: GhlLegacyRow[] = [
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_calendars',
    execution_mode: 'legacy',
    display_name: 'List GHL Calendars',
    description: 'List calendars for scheduling and appointments in GoHighLevel.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_calendar',
    execution_mode: 'legacy',
    display_name: 'Create GHL Calendar',
    description: 'Create a calendar in the connected GoHighLevel location.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_calendar_events',
    execution_mode: 'legacy',
    display_name: 'List GHL Calendar Events',
    description: 'List calendar events; filter by calendar, date range, or contact.',
    parameters: p({
      calendarId: { type: 'string' },
      startTime: { type: 'string' },
      endTime: { type: 'string' },
    }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_calendar_event',
    execution_mode: 'legacy',
    display_name: 'Create GHL Calendar Event',
    description: 'Create a calendar event or appointment in GoHighLevel.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_calendar_event',
    execution_mode: 'legacy',
    display_name: 'Get GHL Calendar Event',
    description: 'Fetch a single calendar event by eventId.',
    parameters: p({ eventId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_calendar_event',
    execution_mode: 'legacy',
    display_name: 'Update GHL Calendar Event',
    description: 'Update an existing calendar event by eventId.',
    parameters: p({ eventId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'delete_calendar_event',
    execution_mode: 'legacy',
    display_name: 'Delete GHL Calendar Event',
    description: 'Delete a calendar event by eventId.',
    parameters: p({ eventId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_calendar_groups',
    execution_mode: 'legacy',
    display_name: 'List GHL Calendar Groups',
    description: 'List calendar groups for team or resource scheduling.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_calendar_group',
    execution_mode: 'legacy',
    display_name: 'Create GHL Calendar Group',
    description: 'Create a calendar group in GoHighLevel.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_calendar_resources',
    execution_mode: 'legacy',
    display_name: 'List GHL Calendar Resources',
    description: 'List bookable resources (rooms, staff) linked to calendars.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_calendar_resource',
    execution_mode: 'legacy',
    display_name: 'Create GHL Calendar Resource',
    description: 'Create a calendar resource in GoHighLevel.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
]
