/**
 * GoHighLevel legacy capabilities: invoices, schedules, templates, estimates.
 */
import type { GhlLegacyRow } from './ghl-legacy-capabilities.shared.partial'
import { p } from './ghl-legacy-capabilities.shared.partial'

export const GHL_LEGACY_INVOICES_CAPABILITY_ENTRIES: GhlLegacyRow[] = [
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_invoices',
    execution_mode: 'legacy',
    display_name: 'List GHL Invoices',
    description: 'List invoices for the location.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_invoice',
    execution_mode: 'legacy',
    display_name: 'Create GHL Invoice',
    description: 'Create an invoice in GoHighLevel.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_invoice_schedules',
    execution_mode: 'legacy',
    display_name: 'List GHL Invoice Schedules',
    description: 'List invoice payment schedules.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_invoice_schedule',
    execution_mode: 'legacy',
    display_name: 'Create GHL Invoice Schedule',
    description: 'Create an invoice schedule.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_invoice_templates',
    execution_mode: 'legacy',
    display_name: 'List GHL Invoice Templates',
    description: 'List invoice templates.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_invoice_template',
    execution_mode: 'legacy',
    display_name: 'Create GHL Invoice Template',
    description: 'Create an invoice template.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_invoice_estimates',
    execution_mode: 'legacy',
    display_name: 'List GHL Invoice Estimates',
    description: 'List estimates / quotes.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_invoice_estimate',
    execution_mode: 'legacy',
    display_name: 'Create GHL Invoice Estimate',
    description: 'Create an estimate in GoHighLevel.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
]
