/**
 * GoHighLevel legacy capabilities: LC email, trigger links, media, custom objects.
 */
import type { GhlLegacyRow } from './ghl-legacy-capabilities.shared.partial'
import { p } from './ghl-legacy-capabilities.shared.partial'

export const GHL_LEGACY_LINKS_MEDIA_OBJECTS_CAPABILITY_ENTRIES: GhlLegacyRow[] = [
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_lc_email',
    execution_mode: 'legacy',
    display_name: 'List GHL LC Email',
    description: 'Read LC email resources (lc-email.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_links',
    execution_mode: 'legacy',
    display_name: 'List GHL Trigger Links',
    description: 'List trigger links for automations (links.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_link',
    execution_mode: 'legacy',
    display_name: 'Create GHL Trigger Link',
    description: 'Create a trigger link (links.write).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_medias',
    execution_mode: 'legacy',
    display_name: 'List GHL Media',
    description: 'List media files in the media library.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'upload_media',
    execution_mode: 'legacy',
    display_name: 'Upload GHL Media',
    description: 'Upload media to the GoHighLevel library.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'delete_media',
    execution_mode: 'legacy',
    display_name: 'Delete GHL Media',
    description: 'Delete a media asset by mediaId.',
    parameters: p({ mediaId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_object_schemas',
    execution_mode: 'legacy',
    display_name: 'List GHL Custom Object Schemas',
    description: 'List custom object type schemas (objects/schema.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_object_schema',
    execution_mode: 'legacy',
    display_name: 'Create GHL Custom Object Schema',
    description: 'Create a custom object schema definition.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_object_records',
    execution_mode: 'legacy',
    display_name: 'List GHL Custom Object Records',
    description: 'List records for a custom object type.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_object_record',
    execution_mode: 'legacy',
    display_name: 'Create GHL Custom Object Record',
    description: 'Create a custom object record.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_object_record',
    execution_mode: 'legacy',
    display_name: 'Update GHL Custom Object Record',
    description: 'Update a custom object record by recordId.',
    parameters: p({ recordId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
]
