/**
 * GoHighLevel legacy capabilities: proposals/contracts, store, surveys, Twilio, workflows.
 */
import type { GhlLegacyRow } from './ghl-legacy-capabilities.shared.partial'
import { p } from './ghl-legacy-capabilities.shared.partial'

export const GHL_LEGACY_DOCUMENTS_STORE_AUTOMATIONS_CAPABILITY_ENTRIES: GhlLegacyRow[] = [
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_documents_contracts',
    execution_mode: 'legacy',
    display_name: 'List GHL Proposals / Contracts',
    description: 'List contracts or proposals (documents_contracts/list.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'send_documents_contract_link',
    execution_mode: 'legacy',
    display_name: 'Send GHL Contract Link',
    description: 'Send a signing link for a contract.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_documents_contract_templates',
    execution_mode: 'legacy',
    display_name: 'List GHL Contract Templates',
    description: 'List contract templates.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'send_documents_contract_template_link',
    execution_mode: 'legacy',
    display_name: 'Send GHL Contract Template Link',
    description: 'Send a link from a contract template.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_store_shipping',
    execution_mode: 'legacy',
    display_name: 'Get GHL Store Shipping',
    description: 'Get store shipping settings.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_store_shipping',
    execution_mode: 'legacy',
    display_name: 'Update GHL Store Shipping',
    description: 'Update store shipping settings.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_store_settings',
    execution_mode: 'legacy',
    display_name: 'Get GHL Store Settings',
    description: 'Get general store settings.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_store_settings',
    execution_mode: 'legacy',
    display_name: 'Update GHL Store Settings',
    description: 'Update store settings.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_surveys',
    execution_mode: 'legacy',
    display_name: 'List GHL Surveys',
    description: 'List surveys in the location.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_twilio_account',
    execution_mode: 'legacy',
    display_name: 'Get GHL Twilio Account',
    description: 'Read Twilio account linkage for the location (twilioaccount.read).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_workflows',
    execution_mode: 'legacy',
    display_name: 'List GHL Workflows',
    description: 'List automation workflows (workflows.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
]
