/**
 * GoHighLevel legacy capabilities: opportunities and payments.
 */
import type { GhlLegacyRow } from './ghl-legacy-capabilities.shared.partial'
import { p } from './ghl-legacy-capabilities.shared.partial'

export const GHL_LEGACY_OPPORTUNITIES_PAYMENTS_CAPABILITY_ENTRIES: GhlLegacyRow[] = [
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_opportunities',
    execution_mode: 'legacy',
    display_name: 'List GHL Opportunities',
    description: 'List pipeline opportunities / deals in GoHighLevel.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_opportunity',
    execution_mode: 'legacy',
    display_name: 'Get GHL Opportunity',
    description: 'Get opportunity details by opportunityId.',
    parameters: p({ opportunityId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_opportunity',
    execution_mode: 'legacy',
    display_name: 'Create GHL Opportunity',
    description: 'Create a new opportunity in a pipeline.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_opportunity',
    execution_mode: 'legacy',
    display_name: 'Update GHL Opportunity',
    description: 'Update an opportunity by opportunityId.',
    parameters: p({ opportunityId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_payment_orders',
    execution_mode: 'legacy',
    display_name: 'List GHL Payment Orders',
    description: 'List payment orders (payments/orders.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_payment_order',
    execution_mode: 'legacy',
    display_name: 'Create GHL Payment Order',
    description: 'Create a payment order.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'collect_payment_order',
    execution_mode: 'legacy',
    display_name: 'Collect GHL Payment Order',
    description: 'Collect payment on an order (payments/orders.collectPayment).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_payment_integrations',
    execution_mode: 'legacy',
    display_name: 'List GHL Payment Integrations',
    description: 'List payment provider integrations for the location.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_payment_integration',
    execution_mode: 'legacy',
    display_name: 'Update GHL Payment Integration',
    description: 'Update payment integration settings.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_payment_transactions',
    execution_mode: 'legacy',
    display_name: 'List GHL Payment Transactions',
    description: 'List payment transactions.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_payment_subscriptions',
    execution_mode: 'legacy',
    display_name: 'List GHL Payment Subscriptions',
    description: 'List recurring subscriptions.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_payment_coupons',
    execution_mode: 'legacy',
    display_name: 'List GHL Payment Coupons',
    description: 'List discount coupons.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_payment_coupon',
    execution_mode: 'legacy',
    display_name: 'Create GHL Payment Coupon',
    description: 'Create a coupon.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_custom_payment_providers',
    execution_mode: 'legacy',
    display_name: 'List GHL Custom Payment Providers',
    description: 'List custom payment providers.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_custom_payment_provider',
    execution_mode: 'legacy',
    display_name: 'Update GHL Custom Payment Provider',
    description: 'Update custom payment provider configuration.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
]
