/**
 * GoHighLevel legacy capabilities: campaigns, contacts, conversations, location custom fields.
 */
import type { GhlLegacyRow } from './ghl-legacy-capabilities.shared.partial'
import { p } from './ghl-legacy-capabilities.shared.partial'

export const GHL_LEGACY_CRM_CAPABILITY_ENTRIES: GhlLegacyRow[] = [
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_ghl_campaigns',
    execution_mode: 'legacy',
    display_name: 'List GHL Campaigns',
    description: 'List marketing campaigns in the GoHighLevel sub-account (campaigns.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_ghl_campaign',
    execution_mode: 'legacy',
    display_name: 'Get GHL Campaign',
    description: 'Get campaign details by campaignId.',
    parameters: p({ campaignId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_contacts',
    execution_mode: 'legacy',
    display_name: 'List GHL Contacts',
    description:
      'List CRM contacts for the location with optional filters and pagination (contacts.readonly).',
    parameters: p({
      query: { type: 'string' },
      limit: { type: 'number' },
      startAfterId: { type: 'string' },
    }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_contact',
    execution_mode: 'legacy',
    display_name: 'Get GHL Contact',
    description: 'Get a single contact by contactId.',
    parameters: p({ contactId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_contact',
    execution_mode: 'legacy',
    display_name: 'Create GHL Contact',
    description: 'Create a new CRM contact (contacts.write).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_contact',
    execution_mode: 'legacy',
    display_name: 'Update GHL Contact',
    description: 'Update an existing contact by contactId.',
    parameters: p({ contactId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_conversations',
    execution_mode: 'legacy',
    display_name: 'List GHL Conversations',
    description: 'List conversations (inbox, SMS, email threads) for the location.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'get_conversation',
    execution_mode: 'legacy',
    display_name: 'Get GHL Conversation',
    description: 'Get conversation details by conversationId.',
    parameters: p({ conversationId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_conversation_messages',
    execution_mode: 'legacy',
    display_name: 'List GHL Conversation Messages',
    description: 'List messages in a conversation thread.',
    parameters: p({ conversationId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'send_conversation_message',
    execution_mode: 'legacy',
    display_name: 'Send GHL Conversation Message',
    description:
      'Send a message in a conversation (email, SMS, etc.). Pass GHL payload fields such as type, contactId, subject, html.',
    parameters: p({
      type: { type: 'string' },
      contactId: { type: 'string' },
      emailFrom: { type: 'string' },
      emailTo: { type: 'string' },
      subject: { type: 'string' },
      html: { type: 'string' },
      message: { type: 'string' },
    }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_conversation_reports',
    execution_mode: 'legacy',
    display_name: 'List GHL Conversation Reports',
    description: 'Fetch conversation reporting / analytics data for the location.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_location_custom_fields',
    execution_mode: 'legacy',
    display_name: 'List GHL Location Custom Fields',
    description:
      'List custom field definitions for the location (locations/customFields.readonly).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_location_custom_field',
    execution_mode: 'legacy',
    display_name: 'Create GHL Location Custom Field',
    description: 'Create a custom field on the location.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_location_custom_field',
    execution_mode: 'legacy',
    display_name: 'Update GHL Location Custom Field',
    description: 'Update a custom field by customFieldId.',
    parameters: p({ customFieldId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
]
