/**
 * GoHighLevel legacy capabilities: phone numbers, number pools, products and pricing.
 */
import type { GhlLegacyRow } from './ghl-legacy-capabilities.shared.partial'
import { p } from './ghl-legacy-capabilities.shared.partial'

export const GHL_LEGACY_PHONES_PRODUCTS_CAPABILITY_ENTRIES: GhlLegacyRow[] = [
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_phone_numbers',
    execution_mode: 'legacy',
    display_name: 'List GHL Phone Numbers',
    description: 'List phone numbers for the location (phonenumbers.read).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'update_phone_number',
    execution_mode: 'legacy',
    display_name: 'Update GHL Phone Number',
    description: 'Update phone number settings by phoneNumberId.',
    parameters: p({ phoneNumberId: { type: 'string', required: true } }),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_number_pools',
    execution_mode: 'legacy',
    display_name: 'List GHL Number Pools',
    description: 'List number pools (numberpools.read).',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_products',
    execution_mode: 'legacy',
    display_name: 'List GHL Products',
    description: 'List products in the GHL store.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_product',
    execution_mode: 'legacy',
    display_name: 'Create GHL Product',
    description: 'Create a product.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_product_prices',
    execution_mode: 'legacy',
    display_name: 'List GHL Product Prices',
    description: 'List prices for products.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_product_price',
    execution_mode: 'legacy',
    display_name: 'Create GHL Product Price',
    description: 'Create a product price.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'list_product_collections',
    execution_mode: 'legacy',
    display_name: 'List GHL Product Collections',
    description: 'List product collections.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
  {
    integration_id: 'gohighlevel',
    action_slug: 'create_product_collection',
    execution_mode: 'legacy',
    display_name: 'Create GHL Product Collection',
    description: 'Create a product collection.',
    parameters: p({}),
    examples: [],
    metadata: {},
    domains: [],
  },
]
