#!/usr/bin/env tsx
/**
 * Generates supabase/migrations/*_strategist_agency_skills.sql from
 * docker/agents/templates/strategist skills + employee template row.
 *
 * Apply to ROAS with:
 *   ./scripts/roas/apply-via-supabase-api.sh supabase/migrations/<file>.sql
 * Or prefer: pnpm tsx scripts/seed-strategist-skills.ts --hire-test
 */
import { existsSync, writeFileSync } from 'node:fs'
import { readdir, readFile } from 'node:fs/promises'
import * as path from 'node:path'

const REPO_ROOT = path.resolve(__dirname, '..')
const TEMPLATE_KEY = 'strategist'
const TEMPLATE_DIR = path.join(REPO_ROOT, 'docker/agents/templates/strategist')
const SKILLS_DIR = path.join(TEMPLATE_DIR, 'skills')
const SKILL_KEYS = [
  'auto-skill-1-roas-precall-strategy',
  'auto-skill-2-roas-strategy-adjust',
  'auto-skill-3-roas-launch-brief',
  'roas-market-research',
  'dylans-super-voice',
] as const
const DEFINITION_FILES = ['AGENTS.md', 'IDENTITY.md', 'ROLE.md', 'SOUL.md', 'TOOLS.md'] as const
const OUT = path.join(
  REPO_ROOT,
  'supabase/migrations/20260714020000_strategist_agency_skills.sql',
)

function parseSkillFrontmatter(markdown: string): { name: string; description: string; body: string } {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n?/)
  if (!match) {
    return { name: 'Untitled', description: '', body: markdown.trim() }
  }
  const yaml = match[1]
  const name = (yaml.match(/^name:\s*(.+)$/m)?.[1] ?? '').trim().replace(/^["']|["']$/g, '')
  const description = (yaml.match(/^description:\s*(.+)$/m)?.[1] ?? '')
    .trim()
    .replace(/^["']|["']$/g, '')
  return { name: name || 'Untitled', description, body: markdown.slice(match[0].length).trim() }
}

function sqlQuote(tag: string, content: string): string {
  return `$${tag}$${content}$${tag}$`
}

function displayName(skillKey: string, frontmatterName: string): string {
  const base = frontmatterName || skillKey
  return base
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ')
}

async function walkResources(skillDir: string): Promise<Array<{ relPath: string; absPath: string }>> {
  const out: Array<{ relPath: string; absPath: string }> = []
  async function walk(dir: string, prefix: string): Promise<void> {
    if (!existsSync(dir)) return
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const absPath = path.join(dir, entry.name)
      const relPath = prefix ? `${prefix}/${entry.name}` : entry.name
      if (entry.isDirectory()) await walk(absPath, relPath)
      else out.push({ relPath, absPath })
    }
  }
  for (const sub of ['references', 'assets'] as const) {
    await walk(path.join(skillDir, sub), sub)
  }
  return out
}

async function main(): Promise<void> {
  const lines: string[] = [
    '-- Agency Strategist template + ROAS strategy onboarding skills (skill_library).',
    '-- Generated by scripts/generate-strategist-skills-migration.ts',
    'BEGIN;',
    '',
  ]

  for (const skillKey of SKILL_KEYS) {
    const markdown = await readFile(path.join(SKILLS_DIR, skillKey, 'SKILL.md'), 'utf-8')
    const { name, description, body } = parseSkillFrontmatter(markdown)
    const tag = skillKey.replace(/[^a-z0-9]+/gi, '_')
    lines.push(`-- ${skillKey}`)
    lines.push(`INSERT INTO public.skill_library (skill_key, name, description, markdown_content, category, updated_at)`)
    lines.push(`VALUES (`)
    lines.push(`  '${skillKey}',`)
    lines.push(`  ${sqlQuote(`${tag}_name`, displayName(skillKey, name))},`)
    lines.push(`  ${sqlQuote(`${tag}_desc`, description)},`)
    lines.push(`  ${sqlQuote(`${tag}_body`, body)},`)
    lines.push(`  'agency_strategy',`)
    lines.push(`  now()`)
    lines.push(`)`)
    lines.push(`ON CONFLICT (skill_key) DO UPDATE SET`)
    lines.push(`  name = EXCLUDED.name,`)
    lines.push(`  description = EXCLUDED.description,`)
    lines.push(`  markdown_content = EXCLUDED.markdown_content,`)
    lines.push(`  category = EXCLUDED.category,`)
    lines.push(`  updated_at = now();`)
    lines.push('')

    for (const { relPath, absPath } of await walkResources(path.join(SKILLS_DIR, skillKey))) {
      const content = await readFile(absPath, 'utf-8')
      const rtag = `${tag}_${relPath.replace(/[^a-z0-9]+/gi, '_')}`
      lines.push(`INSERT INTO public.skill_library_resources (skill_key, file_path, content, content_type)`)
      lines.push(`VALUES ('${skillKey}', '${relPath}', ${sqlQuote(rtag, content)}, 'text/markdown')`)
      lines.push(`ON CONFLICT (skill_key, file_path) DO UPDATE SET`)
      lines.push(`  content = EXCLUDED.content,`)
      lines.push(`  content_type = EXCLUDED.content_type;`)
      lines.push('')
    }

    lines.push(
      `INSERT INTO public.template_skill_assignments (template_key, skill_key, is_enabled)`,
    )
    lines.push(`VALUES ('${TEMPLATE_KEY}', '${skillKey}', true)`)
    lines.push(`ON CONFLICT (template_key, skill_key) DO UPDATE SET is_enabled = true;`)
    lines.push('')
  }

  for (const fileName of DEFINITION_FILES) {
    const content = await readFile(path.join(TEMPLATE_DIR, fileName), 'utf-8')
    const tag = `def_${fileName.replace('.', '_')}`
    lines.push(`INSERT INTO public.agent_templates (template_key, name, role, level, file_name, content, updated_at)`)
    lines.push(
      `VALUES ('${TEMPLATE_KEY}', 'Strategist', 'Agency Strategist', 'employee', '${fileName}', ${sqlQuote(tag, content)}, now())`,
    )
    lines.push(`ON CONFLICT (template_key, file_name) DO UPDATE SET`)
    lines.push(`  name = EXCLUDED.name,`)
    lines.push(`  role = EXCLUDED.role,`)
    lines.push(`  level = EXCLUDED.level,`)
    lines.push(`  content = EXCLUDED.content,`)
    lines.push(`  updated_at = now();`)
    lines.push('')
  }

  lines.push(`INSERT INTO public.agent_employee_templates (`)
  lines.push(
    `  role_key, template_key, skill_seed_key, default_name, name_pool, role, level, disc_profile,`,
  )
  lines.push(
    `  tagline, description, responsibilities, skills, core_beliefs, specialty, image_url, is_enabled, sort_order`,
  )
  lines.push(`) VALUES (`)
  lines.push(`  'strategist', 'strategist', 'strategist', 'Nate',`)
  lines.push(`  '["Nate","Aaron","Dylan","Mira"]'::jsonb,`)
  lines.push(`  'Agency Strategist', 'employee', 'C/D (Conscientious / Dominant)',`)
  lines.push(`  'The Map-Maker',`)
  lines.push(
    `  'Owns agency client strategy from intake through launch brief — pre-call maps, post-call strategy, and the strategist approval package.',`,
  )
  lines.push(
    `  '["Build pre-call strategy maps before kickoff","Finalize post-call strategy and client messages same day","Consolidate THE PLAN launch brief for strategist approval","Run ad-library market research with receipts"]'::jsonb,`,
  )
  lines.push(
    `  '["auto-skill-1-roas-precall-strategy","auto-skill-2-roas-strategy-adjust","auto-skill-3-roas-launch-brief","roas-market-research","dylans-super-voice"]'::jsonb,`,
  )
  lines.push(
    `  '["Walk in knowing — confirm-or-correct beats discovery","The call outranks the map","Receipts or questions — no naked claims","One strategist checkpoint at the launch brief","EOD is a feature"]'::jsonb,`,
  )
  lines.push(
    `  'Client strategy, offer/avatar mapping, competitive research, launch briefs, agency onboarding',`,
  )
  lines.push(`  'https://api.dicebear.com/9.x/shapes/svg?seed=Strategist',`)
  lines.push(`  true, 16`)
  lines.push(`)`)
  lines.push(`ON CONFLICT (role_key) DO UPDATE SET`)
  lines.push(`  template_key = EXCLUDED.template_key,`)
  lines.push(`  skill_seed_key = EXCLUDED.skill_seed_key,`)
  lines.push(`  default_name = EXCLUDED.default_name,`)
  lines.push(`  name_pool = EXCLUDED.name_pool,`)
  lines.push(`  role = EXCLUDED.role,`)
  lines.push(`  level = EXCLUDED.level,`)
  lines.push(`  disc_profile = EXCLUDED.disc_profile,`)
  lines.push(`  tagline = EXCLUDED.tagline,`)
  lines.push(`  description = EXCLUDED.description,`)
  lines.push(`  responsibilities = EXCLUDED.responsibilities,`)
  lines.push(`  skills = EXCLUDED.skills,`)
  lines.push(`  core_beliefs = EXCLUDED.core_beliefs,`)
  lines.push(`  specialty = EXCLUDED.specialty,`)
  lines.push(`  image_url = EXCLUDED.image_url,`)
  lines.push(`  is_enabled = EXCLUDED.is_enabled,`)
  lines.push(`  sort_order = EXCLUDED.sort_order,`)
  lines.push(`  updated_at = now();`)
  lines.push('')
  lines.push('COMMIT;')

  writeFileSync(OUT, lines.join('\n') + '\n')
  console.log(`Wrote ${OUT} (${lines.length} lines)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
