"""Delivery, quality, and team-operations executable SOP blueprints."""

from company_wiki_blueprints import TopicBlueprint, rule


DELIVERY_BLUEPRINTS: dict[str, TopicBlueprint] = {
    "A2P Registration and Messaging Setup": {
        "outcome": "Business messaging begins only after accurate brand and campaign registration, approved opt-in evidence, configured help and stop behavior, and tested sending paths.",
        "steps": [
            "Identify the legal business, tax identity, website, address, authorized representative, messaging platform, sending numbers, and accountable operations owner.",
            "Define each messaging use case, audience, purpose, expected volume, sample messages, frequency, sender identity, and whether marketing or transactional rules apply.",
            "Document the complete opt-in path with page or form URL, unchecked consent language, privacy and terms links, timestamp, source, and proof screenshot.",
            "Prepare accurate brand and campaign registration details, including help, stop, opt-out, support, and prohibited-content handling.",
            "Submit through the approved platform and record submission IDs, status, requested corrections, owner, and review dates without storing credentials.",
            "Do not activate regulated messaging until required approval, number assignment, sender configuration, and platform status are confirmed.",
            "Configure sender identity, opt-out keywords, help response, quiet hours, suppression, consent fields, templates, routing, and delivery monitoring.",
            "Run labeled opt-in, send, reply, help, stop, resubscribe where allowed, invalid-number, and suppression tests; preserve evidence.",
            "Monitor rejection, filtering, delivery, opt-out, complaint, and consent issues and update registration when the business or use case changes.",
        ],
        "rules": [
            rule("Registration is pending, rejected, or mismatched", "Do not send the affected messaging and correct the authoritative record.", "Platform availability does not equal authorization."),
            rule("Consent evidence cannot be produced", "Exclude the contact until valid permission exists.", "A phone number alone is not marketing consent."),
            rule("Use case, domain, brand, or sample content materially changes", "Review whether registration must be updated before sending.", "Approval applies to represented traffic."),
            rule("A contact opts out", "Suppress promptly across applicable workflows and preserve the record.", "Opt-out must survive automation changes."),
        ],
    },
    "Billing and Invoicing — Draft": {
        "outcome": "Invoices reflect approved commercial terms, delivered period, authoritative customer data, tax and payment requirements, and a traceable review and collection path.",
        "steps": [
            "Gather signed terms, billing entity, contact, address, currency, tax treatment, amount, cadence, start date, payment method, and purchase-order requirements.",
            "Create the billing schedule and map each invoice to the covered service period, milestone, usage, credit, deposit, or approved change.",
            "Verify customer and commercial data against the authoritative contract and approved change records before generating the invoice.",
            "Prepare line items with clear description, quantity, rate, date, subtotal, tax, credit, total, due date, remittance, and support contact.",
            "Run independent review for entity, amount, period, duplicates, tax, credits, terms, and recipient before sending.",
            "Send through the approved billing system and record invoice ID, delivery status, due date, payment link or instructions, and owner.",
            "Monitor paid, pending, failed, disputed, overdue, refunded, and written-off states; communicate using the approved cadence.",
            "Reconcile payment to invoice and ledger, issue required receipt or credit, restrict access only through authorized policy, and preserve records.",
        ],
        "rules": [
            rule("Contract and internal billing setup disagree", "Pause invoice and obtain an authorized commercial decision.", "Billing must follow approved terms."),
            rule("A client disputes an amount", "Preserve the invoice, gather contract and delivery evidence, and route to the billing decision owner.", "Untracked edits can erase the dispute trail."),
            rule("Payment fails", "Use the approved retry and notification path without exposing sensitive payment data.", "Collection should remain secure and consistent."),
            rule("A one-off exception is approved", "Record approver, reason, amount, duration, and effect on future invoices.", "Exceptions must not silently become policy."),
        ],
    },
    "ClickUp Delivery Governance": {
        "outcome": "ClickUp reflects the real delivery state, ownership, dependencies, approvals, and evidence so no critical work lives only in memory or chat.",
        "steps": [
            "Create the project from the approved scope template, remove irrelevant tasks, and add any sold deliverables or required controls missing from the template.",
            "Give every material task one outcome, accountable owner, reviewer, due date, priority, dependency, acceptance condition, and source link.",
            "Use statuses according to their defined evidence state and require the owner to maintain blocker, forecast date, and next action.",
            "Convert actionable chat, meeting, approval, and client requests into linked tasks or decisions without duplicating uncontrolled instructions.",
            "Attach approved deliverables, review results, test evidence, and client acceptance to the correct task version.",
            "Review overdue, blocked, unowned, awaiting-input, awaiting-review, and critical-path work during the operating cadence.",
            "When priority or scope changes, update dependencies and displaced commitments and notify every affected owner.",
            "Close only after acceptance evidence and handoff are complete; archive or retain according to the project lifecycle.",
        ],
        "rules": [
            rule("A task has several accountable owners", "Choose one and list collaborators separately.", "Shared accountability often produces no accountability."),
            rule("Status and actual state differ", "Correct status immediately and record the blocker.", "The system must represent reality."),
            rule("A request exists only in chat", "Create or update the canonical work record.", "Chat is context, not durable task governance."),
            rule("Template work does not apply", "Remove it after checking dependencies.", "False tasks obscure the plan."),
        ],
    },
    "Crisis and Incident Escalation — Draft": {
        "outcome": "Material customer, financial, security, compliance, platform, or delivery incidents are contained, owned, communicated, resolved, and prevented through one traceable process.",
        "steps": [
            "Open an incident record with first observed time, reporter, affected systems or customers, symptom, severity, current owner, and known unknowns.",
            "Preserve logs, screenshots, record IDs, URLs, recent changes, messages, financial exposure, and customer impact before altering evidence.",
            "Assign incident lead, technical or functional owner, communications owner, decision authority, and backup; establish one coordination channel.",
            "Contain active harm using the least destructive reversible action and state what is paused, unaffected, or degraded.",
            "Build and test root-cause hypotheses from source through destination, recording disproven causes and avoiding simultaneous uncontrolled fixes.",
            "Communicate factual status, impact, action, owner, and next update time to authorized stakeholders without exposing secrets or speculation.",
            "Implement the approved correction, validate the full affected path, monitor recovery, and prepare rollback if the correction fails.",
            "Close only after stability, customer follow-up, financial or access reconciliation, root cause, prevention owner, and retrospective are complete.",
        ],
        "rules": [
            rule("Active harm is increasing", "Contain first and notify decision authority immediately.", "Delay increases impact."),
            rule("Security or privacy exposure is suspected", "Limit access and use the authorized security/legal response path.", "Ordinary troubleshooting may destroy evidence or widen exposure."),
            rule("Root cause is not confirmed", "Use a reversible experiment and keep the incident open.", "A symptom patch is not resolution."),
            rule("Customer communication is required", "Use one approved factual message and update cadence.", "Conflicting messages compound incidents."),
        ],
    },
    "Email Deliverability Setup": {
        "outcome": "Email sends from an authenticated, permissioned, monitored domain and reaches intended recipients without undermining sender reputation or suppression controls.",
        "steps": [
            "Identify sending domain and subdomain, platform, message types, expected volume, audience sources, sender identities, and accountable technical owner.",
            "Configure and verify SPF, DKIM, DMARC, return path, tracking domain, from and reply-to identities, and required domain ownership.",
            "Separate transactional and marketing streams where appropriate and document reputation, warm-up, and volume constraints.",
            "Audit consent, list source, age, validation, bounce, complaint, unsubscribe, suppression, and buyer-state handling before import or send.",
            "Configure unsubscribe, preference, footer identity, physical address where required, reply routing, bounce handling, and complaint feedback.",
            "Send labeled tests to representative providers and devices, checking authentication, inbox or spam placement, links, rendering, merge fields, and replies.",
            "Ramp volume according to current reputation and engagement while monitoring delivery, bounce, complaint, unsubscribe, block, and domain diagnostics.",
            "Contain reputation issues, correct the source, and preserve suppression and historical evidence during migrations or platform changes.",
        ],
        "rules": [
            rule("Authentication fails or DMARC alignment is wrong", "Do not scale sends until corrected.", "Unauthenticated mail damages trust and placement."),
            rule("List source or permission is unclear", "Exclude the records until verified.", "Purchased or unconsented lists create legal and reputation risk."),
            rule("Bounce or complaint exceeds the approved guardrail", "Pause the affected source or stream and investigate.", "Continued sending compounds reputation damage."),
            rule("A domain migration is planned", "Stage authentication, warm-up, testing, and monitoring before moving full volume.", "Reputation does not transfer automatically."),
        ],
    },
    "GoHighLevel Automation Standard": {
        "outcome": "Every GoHighLevel workflow has a defined entry, state change, owner, message path, exit, suppression, test record, and observable business purpose.",
        "steps": [
            "Define workflow purpose, audience state, trigger, required fields, desired action, owner, timing, consent, and completion state before opening the builder.",
            "Map trigger, filters, tags, opportunity or pipeline changes, assignment, notifications, waits, branches, messages, webhooks, goals, and exits.",
            "Name the workflow and internal steps by client, purpose, version, and state so another operator can understand lineage.",
            "Prevent duplicate enrollment, conflicting workflows, repeat messages, buyer leakage, opt-out bypass, stale waits, and circular state changes.",
            "Configure sender identity, time zones, quiet hours, merge fields, links, reply routing, error handling, and manual handoff.",
            "Use labeled test contacts to exercise every branch, including missing data, duplicate, opt-out, conversion, failed send, and exit.",
            "Verify contact history, tags, pipeline, owner, notifications, messages, events, integrations, and reporting after each test.",
            "Publish only the reviewed version, monitor first live entries, and document changes plus rollback or disable steps.",
        ],
        "rules": [
            rule("A contact can enter more than once unintentionally", "Add deduplication or re-entry conditions before activation.", "Duplicate automation creates customer harm."),
            rule("Two workflows can send conflicting messages", "Create state precedence, suppression, or consolidation.", "The customer should experience one coherent journey."),
            rule("A required field is missing", "Route to a safe exception path rather than sending incorrect personalization.", "Automation must handle incomplete records."),
            rule("A live change affects active contacts", "Assess current positions, test a copy, and define migration or rollback.", "Existing contacts may follow old and new logic differently."),
        ],
    },
    "Google Ads Execution — Draft": {
        "outcome": "Google campaigns launch against verified business-value conversions with controlled intent, budget, creative, destination, policy, and measurement.",
        "steps": [
            "Define objective, primary and secondary conversions, values, geography, language, audience or keyword intent, budget, offer, destination, and policy constraints.",
            "Audit account ownership, billing, manager access, domain, auto-tagging, linked analytics, conversion actions, enhanced conversions where approved, and existing exclusions.",
            "Research intent and map campaigns or groups to distinct customer needs, destinations, negatives, and conversion expectations.",
            "Choose the simplest structure that supports budget control, intent separation, creative relevance, and sufficient event volume.",
            "Write or assemble responsive assets from approved messages and proof, checking pinning, claims, URLs, extensions or assets, and policy.",
            "Configure bidding, budget, schedule, locations, language, networks, devices, audiences, keywords or feeds, negatives, tracking, and experiments.",
            "Test ads, destination, forms or checkout, GCLID preservation, conversions, values, CRM attribution, and reporting with labeled records.",
            "Launch under the approved gate and monitor search terms, spend, delivery, conversion integrity, lead quality, sales, and policy; improve the verified constraint.",
        ],
        "rules": [
            rule("The primary conversion is not verified", "Block launch or use a clearly authorized alternate measurement plan.", "Bidding follows the configured value signal."),
            rule("Search terms show irrelevant intent", "Add negatives or restructure while preserving valid volume.", "Keyword inclusion alone does not guarantee intent."),
            rule("Volume is too low for the selected bidding strategy", "Use a more appropriate strategy until signal matures.", "Automation requires enough reliable data."),
            rule("Policy disapproves an asset", "Resolve the actual policy issue; do not evade enforcement.", "Account health is a launch constraint."),
        ],
    },
    "Knowledge Maintenance": {
        "outcome": "The wiki and Company Cortex remain current, traceable, nonduplicative, privacy-aware, and governed by newer applicable evidence.",
        "steps": [
            "Review new or changed sources for owner, date, scope, sensitivity, lineage, applicability, and conflict with current company knowledge.",
            "Locate the canonical wiki page before creating a new one and decide update, consolidate, supersede, draft, restrict, or exclude.",
            "Preserve source evidence and distinguish direct requirement, interpretation, working standard, example, and unknown.",
            "Resolve true version conflicts using the newest applicable source and owner decision; do not let client customizations replace a master automatically.",
            "Update the executable wiki page first, including steps, decisions, templates, QA, troubleshooting, source, owner, and review date.",
            "Identify reusable anonymized lessons for Company Cortex and keep person, client, credential, compensation, and restricted detail out of broad memory.",
            "Review proposed Cortex signals through the approved gate, merge duplicates, retire obsolete knowledge, and preserve replacement lineage.",
            "Verify retrieval and human usability, record the change, notify affected roles, and schedule review for volatile subjects.",
        ],
        "rules": [
            rule("A source contains sensitive internal material", "Exclude or restrict it rather than broadening visibility.", "Knowledge access must follow sensitivity."),
            rule("Two sources disagree but are not true versions", "Preserve both contexts and obtain an owner decision.", "Newer is not automatically more applicable."),
            rule("A lesson is client-specific", "Keep full evidence in its context and anonymize only reusable learning.", "Company memory should not fixate on one client."),
            rule("A wiki page is not executable by a teammate", "Keep it in draft and complete the missing instruction before Cortex synchronization.", "The wiki is the human source of truth."),
        ],
    },
    "Performance Review — Draft": {
        "outcome": "A role review evaluates agreed outcomes, observable behaviors, quality, collaboration, growth, system constraints, and a specific next plan fairly.",
        "steps": [
            "Confirm the role outcomes, responsibilities, operating standards, review period, evidence sources, and prior commitments before collecting judgments.",
            "Gather delivery, quality, client, collaboration, reliability, skill, learning, and corrective evidence using comparable definitions and context.",
            "Invite the team member's self-review and examples, including constraints, support needs, achievements, misses, and proposed growth.",
            "Separate verified facts, interpretation, isolated incidents, recurring patterns, system failures, capacity issues, and individual ownership gaps.",
            "Evaluate strengths and gaps against communicated standards rather than personality, changing expectations, or unrecorded preferences.",
            "Hold the conversation with examples, listen for missing context, and reach a shared or clearly documented understanding of each finding.",
            "Create a plan with outcome, behavior or skill, support, owner, milestone, evidence, review date, and consequences where applicable.",
            "Store the review in the approved restricted system, follow up at the scheduled checkpoints, and update role or process standards when the system is causal.",
        ],
        "rules": [
            rule("An expectation was never communicated", "Do not treat it as a prior performance failure; clarify it going forward.", "Fair review requires known standards."),
            rule("The same gap affects several people", "Investigate system, training, incentives, and capacity.", "Patterns often exceed one individual."),
            rule("Evidence contains sensitive or irrelevant personal detail", "Exclude it and use the restricted process.", "Reviews require privacy and relevance."),
            rule("A serious corrective decision is possible", "Use authorized people-operations and legal procedures.", "Ordinary wiki guidance does not replace formal process."),
        ],
    },
    "Proxy and Technical Environment": {
        "outcome": "Authorized technical or proxy environments are configured, documented, tested, and monitored without sharing credentials or creating ambiguous account identity.",
        "steps": [
            "Define the approved use case, platform, account, geography, identity, device, owner, security requirement, and policy or legal constraints.",
            "Confirm the platform and client authorize the proposed environment and that it will not evade enforcement, impersonate users, or conceal prohibited activity.",
            "Select the approved proxy, browser profile, device, access manager, and authentication path using least privilege and controlled recovery.",
            "Create naming and assignment records for profile, proxy, account, owner, purpose, start date, review date, and restriction without recording secrets.",
            "Configure time zone, locale, browser, network, cookies, MFA, recovery, and platform identity consistently with the authorized operation.",
            "Test connection stability, location, DNS or leak behavior where relevant, platform login, MFA, account access, and expected low-risk action.",
            "Monitor errors, verification challenges, reputation, access changes, and account notices; stop when behavior indicates policy or security risk.",
            "Rotate or remove access when roles change, preserve required records, and review the environment on the defined cadence.",
        ],
        "rules": [
            rule("The purpose is to evade platform policy or enforcement", "Do not configure or use the environment.", "Technical capability does not create authorization."),
            rule("Identity, geography, or authorization is unclear", "Pause until the accountable owner resolves it.", "Ambiguity can trigger security and platform harm."),
            rule("Credentials are shared in ordinary messages", "Move them to approved secure storage and remove exposure.", "Secrets require controlled handling."),
            rule("The environment triggers repeated security checks", "Stop retries and investigate configuration, ownership, and platform status.", "Repeated access attempts can worsen lockout."),
        ],
    },
    "Reporting Definitions and Reconciliation — Draft": {
        "outcome": "Teams use one metric dictionary and can reconcile platform, analytics, CRM, payment, and sales reports without presenting incompatible numbers as one truth.",
        "steps": [
            "List every reported metric with business question, formula, numerator, denominator, event, source, owner, time zone, window, attribution, currency, and exclusions.",
            "Classify each value as platform-reported, modeled, estimated, verified, manually entered, or derived and state its refresh timing.",
            "Map identifiers across ad, session, lead, contact, opportunity, appointment, order, customer, and revenue systems.",
            "Choose authoritative sources for spend, leads, qualification, appointments, sales, cash, refunds, and customer outcomes.",
            "Pull the same cohort and date logic from each system, then quantify gaps from latency, duplicates, attribution, missing IDs, refunds, taxes, or status definitions.",
            "Resolve defects at the data source when possible and document accepted variance plus the reason when exact reconciliation is impossible.",
            "Publish the metric dictionary and reconciliation record with examples, query or report links, owner, and review date.",
            "Use the defined metrics in client and internal reports and require change control when a formula or source changes.",
        ],
        "rules": [
            rule("Two metrics share a name but different definitions", "Rename or qualify them before reporting together.", "Labels must preserve meaning."),
            rule("A source is incomplete or delayed", "Label the value and expected maturation window.", "Freshness affects interpretation."),
            rule("Revenue differs due to cash, booked, or attributed basis", "Report each explicitly instead of forcing one total.", "Different commercial questions need different measures."),
            rule("A definition changes", "Version it and restate prior comparisons where material.", "Trend continuity depends on stable meaning."),
        ],
    },
    "Retention and Renewal — Draft": {
        "outcome": "Renewal decisions use outcome, delivery, relationship, economics, future opportunity, risk, and explicit next-scope evidence rather than last-minute pressure.",
        "steps": [
            "Set the renewal decision date early and schedule health reviews far enough ahead to correct problems before commercial discussion.",
            "Review sold outcomes, delivered scope, quality, responsiveness, client responsibilities, performance, customer impact, and open risk from authoritative records.",
            "Collect client sentiment, decision-maker priorities, changed business conditions, unresolved objections, and future goals through direct conversation.",
            "Separate relationship, execution, strategy, offer, market, capacity, and expectation issues and assign corrective actions before proposing renewal.",
            "Build the next recommendation from the verified constraint and opportunity, with scope, outcomes, exclusions, dependencies, measures, timeline, and price authority.",
            "Present evidence, acknowledge misses, explain the future path, and obtain a clear decision without unsupported guarantees or artificial urgency.",
            "If renewing, update commercial records, access, plan, owners, and kickoff; if not, activate the approved resolution and offboarding path.",
            "Record reasons and reusable anonymized learning, then improve qualification, delivery, or renewal timing where patterns repeat.",
        ],
        "rules": [
            rule("Material service issues remain unresolved", "Address them before treating renewal as a sales objection.", "Commercial pressure should not hide delivery truth."),
            rule("The future scope does not address a verified need", "Do not recommend it merely to preserve revenue.", "Renewal should create credible value."),
            rule("A decision-maker is absent", "Secure the appropriate conversation or written authority.", "Positive user sentiment may not equal renewal authority."),
            rule("Renewal is declined", "Move promptly into professional offboarding and evidence capture.", "A clean exit protects trust and security."),
        ],
    },
    "Secure Access Management — Draft": {
        "outcome": "Access follows approved identity, least privilege, secure secret handling, recoverable ownership, periodic review, and prompt removal when responsibility ends.",
        "steps": [
            "Inventory systems, accounts, owners, business purpose, data sensitivity, required roles, recovery contacts, and current access.",
            "Require unique controlled identities, multi-factor authentication, approved password or secret management, and role-based invitation where supported.",
            "Approve access from documented responsibility and least privilege; avoid shared personal accounts and broad administrator rights by default.",
            "Grant through the authoritative platform, verify the recipient and permission, and record account ID, role, approver, date, and review date without secret values.",
            "Test that required work is possible and prohibited or unnecessary access is not present.",
            "Review access on role, client, vendor, project, and scheduled changes; investigate orphaned identities, inactive users, and excess privilege.",
            "Revoke or adjust promptly when responsibility ends, rotate exposed secrets, transfer ownership, and verify recovery still works.",
            "Preserve audit evidence and escalate suspected compromise through the incident process rather than repeated login attempts.",
        ],
        "rules": [
            rule("A shared credential is the only access path", "Create a controlled migration and restrict interim use.", "Shared identity destroys accountability."),
            rule("A user requests more privilege for convenience", "Grant only the specific function or obtain authorized exception.", "Convenience does not justify broad access."),
            rule("A secret may be exposed", "Rotate it, contain access, and open an incident record.", "Uncertainty should not leave active credentials unchanged."),
            rule("An owner leaves or changes role", "Transfer ownership and recovery before revocation where continuity requires it.", "Removal must not orphan business assets."),
        ],
    },
    "Team Onboarding and Role Certification": {
        "outcome": "A teammate gains the context, access, supervised practice, and evidence required to perform a role independently without relying on outdated names or tribal knowledge.",
        "steps": [
            "Define role outcomes, recurring responsibilities, systems, permissions, SOPs, quality gates, risks, communication, and certification evidence.",
            "Create the onboarding plan with owner, buddy or reviewer, milestones, source material, practice work, live shadowing, and check-in dates.",
            "Provision least-privilege access and verify secure identity, MFA, recovery, and actual task capability without sharing credentials.",
            "Teach the company operating model, systems of record, escalation, client communication, privacy, and quality standards before isolated tactics.",
            "Walk through role workflows using current SOPs and real anonymized examples, requiring the teammate to explain decisions and evidence.",
            "Assign supervised practice with increasing risk, unit review, corrections, and documented demonstration of each competency.",
            "Run certification scenarios covering normal work, edge cases, incidents, handoffs, and refusal conditions; record pass, gap, and retraining.",
            "Grant independent responsibility only for passed competencies and schedule reinforcement or recertification when systems change.",
        ],
        "rules": [
            rule("A teammate has access but has not demonstrated the workflow", "Keep work supervised.", "Access is not competence."),
            rule("Training material conflicts with the current SOP", "Use the newest applicable approved source and correct the stale material.", "Onboarding should not perpetuate drift."),
            rule("A high-risk competency fails", "Do not certify that responsibility; retrain and reassess.", "Certification must protect customers and systems."),
            rule("A role changes materially", "Update outcomes and recertify affected competencies.", "Past proficiency may not cover new responsibility."),
        ],
    },
    "Texas and Federal SMS Compliance": {
        "outcome": "SMS campaigns use documented permission, accurate identity, approved timing and content, durable suppression, and current legal and platform requirements before sending.",
        "steps": [
            "Identify business, sender, audience location, use case, marketing or transactional purpose, numbers, platform, volume, and accountable compliance owner.",
            "Use the active ROAS legal SOP and current authorized counsel or policy guidance to determine applicable federal, state, platform, and registration requirements.",
            "Document opt-in wording, placement, unchecked action, source URL, timestamp, purpose, sender identity, frequency, rates notice, privacy, terms, and proof.",
            "Confirm A2P or other registration, number or sender approval, sample messages, help and stop behavior, and content alignment with the approved use case.",
            "Configure quiet hours and time zones, sender identification, opt-out keywords, suppression, help response, consent fields, records, and workflow exits.",
            "Review every campaign for truthful identity, offer, claim, links, frequency, recipient state, exclusions, and prohibited or high-risk content.",
            "Test opt-in, send, help, stop, suppression, reply, invalid contact, time-zone, and audit-record behavior with labeled contacts.",
            "Monitor complaints, opt-outs, carrier filtering, delivery, legal or platform changes, and consent defects; stop affected sends and preserve evidence.",
        ],
        "rules": [
            rule("Consent cannot be tied to the sender and use case", "Do not send marketing SMS to that contact.", "Generic contact information is not specific permission."),
            rule("A recipient opts out", "Suppress promptly across applicable systems and do not re-enroll without a valid new basis.", "Suppression must be durable."),
            rule("The law or authoritative guidance changes", "Update the SOP and affected workflows before continued sending.", "Compliance is time-sensitive."),
            rule("A campaign is legally or contextually unclear", "Pause and route to the authorized compliance decision owner.", "The wiki does not replace case-specific legal judgment."),
        ],
    },
    "Video Production Workflow — Draft": {
        "outcome": "Video moves from approved brief through script, preproduction, capture, storage, edit, review, native export, delivery, and reusable learning with clear ownership.",
        "steps": [
            "Create the brief with audience, objective, message, hook, script, proof, CTA, channels, formats, duration, brand, references, due date, and approver.",
            "Approve the script or content outline and verify claims, pronunciation, names, offer facts, captions source, and required permissions.",
            "Build the shot plan and production schedule covering owner, talent, location, equipment, sound, light, framing, wardrobe, props, B-roll, releases, and backups.",
            "Run a technical check, record organized takes and variations, confirm critical footage on site, and back up originals before teardown.",
            "Store footage using campaign, concept, date, speaker, scene, take, and rights naming with controlled access and no destructive overwrite.",
            "Edit for story, pace, clarity, audio, color, captions, proof, brand, safe zones, channel constraints, CTA, and required versions.",
            "Run unit and final review against the brief, record timecoded corrections, apply them to identified versions, and retest exports.",
            "Deliver approved masters and native exports with usage rights, captions, thumbnails, source links, and destination; archive learning after performance review.",
        ],
        "rules": [
            rule("Critical footage or audio is unusable", "Reshoot before polishing around the failure unless an approved alternate works.", "Editing cannot reliably invent missing source quality."),
            rule("Usage permission is unclear", "Exclude the asset until verified.", "Production possession is not publication permission."),
            rule("A late change affects claims or narrative", "Rerun content review and affected edits.", "Final review belongs to a specific message version."),
            rule("One export is reused across incompatible placements", "Create native crops or explicitly exclude placements.", "Format affects comprehension and composition."),
        ],
    },
}
