"""Webinar and event executable SOP blueprints."""

from company_wiki_blueprints import TopicBlueprint, rule


WEBINAR_BLUEPRINTS: dict[str, TopicBlueprint] = {
    "Campaign Selection and Success Definition": {
        "outcome": "The team selects an event campaign only when the audience, offer, proof, economics, capacity, and measurable post-event path can support it.",
        "steps": [
            "Define the business outcome, offer, audience, event format, date constraints, and the action attendees must take after receiving the teaching.",
            "Review offer proof, customer demand, sales capacity, fulfillment capacity, list size, media budget, platform access, and presenter readiness.",
            "Map the acquisition-to-revenue path: impression, registration, attendance, pitch exposure, application or checkout, sales follow-up, purchase, and fulfillment.",
            "Pull historical or comparable performance and label verified, estimated, and unknown inputs before forecasting registrations or revenue.",
            "Model required registrations, show rate, pitch exposure, conversion, sales follow-up, cash collection, spend, and break-even scenarios.",
            "Identify the primary strategic hypothesis and the event-specific risks that could prevent the forecast from being interpretable.",
            "Choose proceed, validate first, redesign, or decline; record the reasons, dependencies, owner, and next decision gate.",
            "Publish the approved success definition with metric formulas, sources, windows, targets, guardrails, and post-event decision rules.",
        ],
        "rules": [
            rule("The offer is unproven or materially changing", "Run a validation stage before using a large event launch.", "An event cannot compensate for an unclear offer."),
            rule("Sales or fulfillment cannot handle plausible demand", "Reduce scale, add capacity, or delay.", "A successful promotion can still create an operational failure."),
            rule("No trustworthy baseline exists", "Use scenario ranges and label the campaign exploratory.", "False precision hides uncertainty."),
            rule("The event has no defined post-event conversion path", "Do not approve promotion until routing and ownership exist.", "Attention without a next step cannot produce the intended outcome."),
        ],
    },
    "Case Study Capture": {
        "outcome": "Event results and customer stories become verified, permissioned case-study evidence with context, limits, and reusable assets.",
        "steps": [
            "Define the result or transformation to document and identify the source systems, customer contact, account owner, and permission status.",
            "Collect baseline, intervention, timeline, outcome, costs, constraints, and supporting platform, CRM, payment, or delivery evidence.",
            "Interview the customer or internal owner using open questions about the prior state, decision, experience, result, and what contributed to it.",
            "Verify every number, date, quote, identity, and causal statement against records; remove claims the evidence cannot support.",
            "Write the story as context, problem, approach, implementation, result, limitations, and next step without implying typical or guaranteed outcomes.",
            "Obtain written approval for identity, quote, result, channels, duration, and any required disclaimer or anonymization.",
            "Produce the approved long-form story plus modular quotes, proof slides, ad-safe excerpts, sales notes, and internal learning.",
            "Store evidence and permissions with the final assets, set a review date, and withdraw or update the story when facts or permission change.",
        ],
        "rules": [
            rule("A result cannot be reconciled", "Exclude the disputed value or label the uncertainty.", "Case studies must be auditable."),
            rule("Permission is missing or narrower than the desired use", "Use only the authorized scope or anonymize after approval.", "Ownership of data does not equal marketing permission."),
            rule("Several factors contributed to the result", "Describe contribution without claiming sole causation.", "Credibility requires causal restraint."),
            rule("The story is old or the offer changed", "Reverify relevance before reuse.", "Stale evidence can misrepresent the current experience."),
        ],
    },
    "Client Inputs and Asset Readiness": {
        "outcome": "The event team begins production with usable offer, audience, proof, brand, presenter, platform, funnel, and promotion inputs instead of unresolved placeholders.",
        "steps": [
            "Issue one event intake checklist covering offer, price, bonuses, guarantee, scarcity, audience, proof, presenter, dates, brand, platform, funnel, CRM, media, and approvals.",
            "Assign one client owner and one ROAS owner to each required input with a due date tied to the critical path.",
            "Review submissions for completeness, accuracy, permission, format, and production usability; do not mark an inaccessible link or rough mention complete.",
            "Verify offer terms and claims across commercial records, sales material, fulfillment capacity, and legal or platform constraints.",
            "Inventory logos, fonts, colors, photos, video, testimonials, screenshots, product views, case studies, and usage permissions in the source folder.",
            "Confirm presenter availability, rehearsal windows, technical environment, recording rights, and backup contact.",
            "Convert gaps into explicit blockers, approved placeholders, or scoped research tasks and recalculate affected dates.",
            "Hold the asset-readiness review and release only the workstreams whose required inputs are approved and stable.",
        ],
        "rules": [
            rule("A critical offer fact is unresolved", "Block dependent copy, pitch, checkout, and promotion.", "One uncertain term can invalidate many assets."),
            rule("An asset exists but usage rights are unclear", "Exclude it until permission is verified.", "Availability is not authorization."),
            rule("A missing input affects only one independent workstream", "Begin unblocked work and keep the dependency visible.", "Parallel progress should not hide blockers."),
            rule("Client delay compresses the review window", "Move the milestone or obtain an explicit risk trade-off.", "Quality gates should not disappear silently."),
        ],
    },
    "Launch Timeline and Critical Path": {
        "outcome": "The event launches from a dependency-based backward plan with realistic review time, named owners, and protected go-live gates.",
        "steps": [
            "Lock the live date, time zone, format, offer, platform, presenter, and accountable launch owner before calculating downstream deadlines.",
            "Work backward through event operation, final rehearsal, slides, funnel, automations, tracking, promotion, creative, copy, outline, offer, and intake.",
            "Define each deliverable's input, owner, reviewer, duration, acceptance condition, dependency, and latest safe completion date.",
            "Mark the true critical path and add review, correction, upload, propagation, and contingency time rather than planning only creation time.",
            "Add client decision deadlines and state the exact milestone impact when an approval or input arrives late.",
            "Publish a single timeline view and require owners to update status, blocker, forecast date, and next action during the operating cadence.",
            "Review critical-path variance frequently, re-sequence independent work, and escalate compression before quality gates are threatened.",
            "Freeze the launch configuration after final QA and reserve the final window for monitoring readiness, not unplanned feature additions.",
        ],
        "rules": [
            rule("A critical task slips", "Recalculate every dependent date and communicate the decision needed.", "Critical-path delay propagates."),
            rule("The remaining time cannot support required review", "Move launch or reduce scope through an authorized decision.", "A calendar does not make unsafe work possible."),
            rule("A noncritical task slips", "Re-sequence or defer it without hiding the change.", "Not every delay should move launch."),
            rule("A late request adds new scope", "Name the displaced work and obtain the trade-off.", "New work cannot enter the critical path invisibly."),
        ],
    },
    "Live Event Operations": {
        "outcome": "The live event runs from an assigned control plan covering platform, presenter, moderation, attendance, offer, links, sales handoff, recording, and incident response.",
        "steps": [
            "Publish the run of show with join time, checks, opening, teaching, transitions, pitch, Q&A, close, follow-up trigger, and responsible role for every segment.",
            "Confirm host, co-host, presenter, moderator, technical producer, chat owner, link owner, sales contact, backup, and incident decision authority.",
            "Open and test the room, audio, video, screen sharing, slides, recording, captions, polls, chat, attendee permissions, links, and backup connection.",
            "Load approved slides, offer URLs, checkout or application links, moderator scripts, FAQs, proof assets, and escalation contacts in an operator packet.",
            "Admit attendees according to plan, monitor room health, capture attendance and engagement, and moderate support or inappropriate content.",
            "Track actual timing, pitch exposure, offer links, questions, objections, technical incidents, and material presenter deviations with timestamps.",
            "Use the incident matrix to continue, adapt, pause, switch backup, or end; communicate changes clearly without exposing internal confusion.",
            "Close with the intended CTA and expectation, preserve recording and chat, export participant data, trigger follow-up, and verify sales ownership.",
            "Hold the immediate debrief and record facts, incidents, hot leads, corrections, and next-day responsibilities.",
        ],
        "rules": [
            rule("The presenter loses connection", "Use the named backup host and reconnection script while preserving the room.", "Preassigned continuity prevents panic."),
            rule("Checkout or application link fails", "Stop repeating the broken CTA, post the approved alternate, and log affected prospects.", "A clear recovery path protects intent."),
            rule("The schedule is running late", "Protect core teaching, transition, offer clarity, and CTA; cut optional material first.", "The commercial sequence should not collapse from timing drift."),
            rule("A safety, legal, or severe platform incident occurs", "Pause the affected activity and let the incident owner decide continuation.", "Live momentum does not override safety."),
        ],
    },
    "Offer and Value Stack": {
        "outcome": "The event presents a coherent, deliverable offer whose product, components, price, bonuses, scarcity, and risk reversal are approved before scripting the pitch.",
        "steps": [
            "Define the buyer, current problem, desired transformation, offer name, delivery model, access, timeline, and primary benefit in one offer statement.",
            "List two to five core components and explain each as setup, customer payoff, proof, and tie-down to the desired result.",
            "Set price, payment options, eligibility, fulfillment limits, taxes or fees, and the checkout or sales path from the authoritative commercial source.",
            "Build five to seven bonuses only where each removes a real obstacle, accelerates use, or increases certainty without obscuring the core offer.",
            "Create truthful value framing from actual alternatives, effort, delay, or component value; do not invent inflated retail values.",
            "Define real scarcity or urgency with reason, quantity or deadline, proof method, exact consequence, and consistent wording across assets.",
            "Design a supportable risk reversal with qualifying action, timeframe, remedy, exclusions, operational owner, and approved language.",
            "Review the entire stack against fulfillment capacity, proof, sales objections, legal requirements, checkout, slides, page, emails, and sales scripts.",
            "Freeze the approved offer sheet before the pitch and require explicit change control afterward.",
        ],
        "rules": [
            rule("A bonus adds complexity but not buyer progress", "Remove or redesign it.", "More items do not automatically create more value."),
            rule("Scarcity cannot be proven or enforced", "Do not use it.", "False urgency damages trust and compliance."),
            rule("A guarantee cannot be fulfilled operationally", "Rewrite it before promotion.", "Risk reversal must be a real business process."),
            rule("Offer terms change after downstream work begins", "Update every affected asset and rerun review.", "Commercial inconsistency creates customer and legal risk."),
        ],
    },
    "Paid Media for Events": {
        "outcome": "Event media produces trackable registrations from matched audiences and creative while protecting budget, show-up quality, and post-event economics.",
        "steps": [
            "Translate the event goal into registration, attendance, pitch exposure, and revenue scenarios using budget, dates, show rate, and conversion assumptions.",
            "Define cold, warm, retargeting, registrant, attendee, no-show, buyer, and exclusion audiences with source, window, and purpose.",
            "Build creative angles around the event promise, problem, mechanism, presenter proof, teaching value, date, and real urgency, each with a hypothesis.",
            "Create campaign architecture, naming, budget pacing, attribution parameters, registration event, and downstream reporting lineage.",
            "Run launch QA through ad, page, registration, confirmation, CRM, reminder, attendance, and buyer exclusion using labeled test records.",
            "Launch early enough to learn while reserving planned spend for the final registration period; monitor delivery and lead quality at fixed checkpoints.",
            "Retarget page visitors and registrants with appropriate proof and show-up creative without continuing acquisition messaging to buyers or excluded groups.",
            "Evaluate cost per registration, registration rate, show rate, pitch exposure, qualified actions, sales, and cash rather than CPL alone.",
            "Use results to adjust creative, audience, reminder, page, or event strategy based on the verified constraint.",
        ],
        "rules": [
            rule("Registrations are cheap but show rate is weak", "Inspect promise match, confirmation, calendar, reminders, and audience quality before scaling.", "Registration is an intermediate event."),
            rule("The pixel or registration event is wrong", "Block or pause affected delivery and repair tracking.", "The platform will learn from the wrong signal."),
            rule("Frequency rises near the event", "Refresh creative or reallocate while preserving required final-call coverage.", "Urgency cannot compensate for fatigue indefinitely."),
            rule("The event is capacity constrained", "Use truthful limits and cap media accordingly.", "Promotion should reflect real operational capacity."),
        ],
    },
    "Post-Event Follow-Up": {
        "outcome": "Attendees, no-shows, buyers, applicants, and high-intent prospects receive the correct time-bounded follow-up and sales ownership after the event.",
        "steps": [
            "Export and reconcile registration, attendance, duration, engagement, offer-link, application, checkout, buyer, and sales data immediately after the event.",
            "Segment buyers, applicants, booked calls, attendees, no-shows, partial attendees, and high-intent questions so no group receives an inappropriate message.",
            "Deliver replay, resources, offer path, deadlines, and next step promptly using accurate access and expiration terms.",
            "Build the bounded sequence across email, SMS, retargeting, and sales outreach with proof, objections, urgency, FAQs, and one clear CTA.",
            "Create a hot-lead list using observable intent and provide contact, evidence, suggested action, owner, and response deadline to sales.",
            "Apply buyer and opt-out suppression, prevent duplicate automations, and verify each segment enters and exits the intended path.",
            "Monitor delivery, clicks, applications, bookings, sales, cash, replies, complaints, and support issues during the follow-up window.",
            "Close the time-sensitive sequence when the real deadline passes and route remaining prospects into the appropriate longer-term path.",
            "Reconcile final outcomes and feed objections, questions, and conversion evidence into the event audit.",
        ],
        "rules": [
            rule("A buyer remains in acquisition follow-up", "Remove and correct suppression immediately.", "Post-purchase promotion creates confusion and complaints."),
            rule("A deadline or scarcity condition is not real", "Do not communicate it.", "Urgency must be accurate."),
            rule("Sales cannot work the hot-lead list promptly", "Prioritize by intent and reassign coverage.", "Event intent decays quickly."),
            rule("Replay access fails", "Use the approved alternate and notify affected segments.", "Follow-up cannot convert through a broken asset."),
        ],
    },
    "Presenter Coaching and Rehearsal": {
        "outcome": "The presenter can deliver the approved story, teaching, transitions, pitch, objections, and CTA within time while recovering from common failures.",
        "steps": [
            "Review the approved outline, script, slides, offer, timing, audience, proof, claims, CTA, and platform controls with the presenter.",
            "Coach the opening until relevance, promise, authority, expectations, and reason to stay are clear without reading or unnecessary setup.",
            "Rehearse teaching for comprehension, examples, interaction, pacing, belief change, and benefit-focused recaps rather than information dumping.",
            "Practice the bridge from teaching to offer, permission, value stack, price, risk reversal, urgency, checkout, and clear next action.",
            "Role-play likely objections, difficult questions, technical interruptions, timing compression, low chat activity, and a failed link.",
            "Run a full timed rehearsal in the actual or equivalent technical environment and record timing plus correction notes by section.",
            "Apply corrections to delivery or approved assets, then rehearse the changed sections and verify claims remain supportable.",
            "Confirm backup plan, operator cues, communication channel, join time, final version, and no-late-change rule before declaring ready.",
        ],
        "rules": [
            rule("The rehearsal runs long", "Cut repetition and optional examples before compressing core transition or offer clarity.", "Critical sequence deserves protected time."),
            rule("The presenter changes an offer fact or claim", "Return to the approved source and correct it before live delivery.", "Spoken deviations create the same risk as written ones."),
            rule("A materially changed deck or offer arrives after rehearsal", "Rehearse affected sections again.", "Readiness does not transfer automatically to a new version."),
            rule("The presenter cannot execute the full path", "Simplify, add operator support, or move the event.", "Live pressure amplifies unresolved gaps."),
        ],
    },
    "Promotion Plan": {
        "outcome": "Paid, email, SMS, organic, partner, community, and sales promotion operate from one promise, calendar, segment plan, and measurement system.",
        "steps": [
            "Define registration target, audience segments, event promise, proof, CTA, dates, consent constraints, channel owners, and baseline reach.",
            "Build the promotion calendar from announcement through open, teaching or proof, objection handling, urgency, final call, and show-up phases.",
            "Assign each channel a role, audience, message adaptation, asset, send or publish time, owner, approval, and tracking parameter.",
            "Create a message matrix that preserves the same core promise while changing context and format for cold, warm, partner, customer, and registrant audiences.",
            "Coordinate paid and owned frequency so audiences receive deliberate reinforcement rather than conflicting or excessive messages.",
            "Verify list consent, suppression, sender identity, links, dates, time zones, partner terms, and platform requirements before scheduling.",
            "Launch in phases and monitor reach, registration, source attribution, deliverability, opt-outs, cost, and segment quality.",
            "Shift effort from channels or messages that miss the verified constraint while preserving accurate final-call and registrant communication.",
            "Reconcile registrations by source and document reusable message and channel learning after the event.",
        ],
        "rules": [
            rule("A segment has not consented to the planned channel", "Exclude it or use an authorized channel.", "Promotion must respect permission."),
            rule("Channels use different dates, offer terms, or promises", "Stop and reconcile to the approved source.", "Inconsistency reduces trust and creates support load."),
            rule("Registration pace is behind", "Diagnose reach, message, page, or audience quality before simply increasing frequency.", "More volume can amplify the wrong constraint."),
            rule("An audience is already registered or purchased", "Move it to show-up or buyer communication and suppress acquisition promotion.", "State-specific messaging improves experience."),
        ],
    },
    "Registration and Confirmation Funnel": {
        "outcome": "A visitor can understand the event, register once, receive correct confirmation and calendar information, and enter measurable reminder and sales systems.",
        "steps": [
            "Confirm event title, promise, audience, learning outcomes, presenter proof, date, time zone, format, consent language, and post-registration expectation.",
            "Write and build the registration page with one primary action, essential fields, relevant proof, clear date and time, and mobile-first layout.",
            "Configure form validation, duplicate handling, consent capture, source parameters, hidden attribution fields, and the correct CRM destination.",
            "Build the confirmation page with success message, calendar action, join or delivery expectation, support path, and optional next qualifying step.",
            "Connect CRM contact, tags, campaign membership, pipeline or lead state, internal notification, reminder enrollment, and exclusion logic.",
            "Install and verify analytics and ad-platform registration events with correct firing location, deduplication, and test identifiers.",
            "Submit test registrations on mobile and desktop from multiple sources and verify page, CRM, event, email, SMS, calendar, notification, and reporting behavior.",
            "Record passes and failures, correct the path, rerun affected tests, and freeze the approved version before promotion.",
        ],
        "rules": [
            rule("Registration succeeds but CRM or reminders fail", "Block promotion until routing is repaired.", "A visible thank-you page is not a complete registration."),
            rule("The form asks for unnecessary data", "Remove it unless qualification or operations require it.", "Extra friction should have a purpose."),
            rule("Time zone presentation is ambiguous", "Show the canonical zone and provide calendar conversion.", "Event timing errors directly reduce attendance."),
            rule("The event changes after registrations begin", "Update every page and message and notify affected registrants.", "Existing commitments must be corrected, not only future promotion."),
        ],
    },
    "Reminder and Show-Up System": {
        "outcome": "Every valid registrant receives accurate, permissioned reminders and a frictionless path to attend while buyers and opt-outs are handled correctly.",
        "steps": [
            "Define reminder goal, event date and time zone, join path, sender identity, consent basis, segment rules, and attendance source of truth.",
            "Design a cadence from registration confirmation through calendar action, pre-event value, day-before, day-of, near-start, and live-now messages.",
            "Write messages that restate the event promise, preparation, date, time, join action, support path, and any real attendance incentive without false urgency.",
            "Configure email and SMS triggers, delays, time-zone behavior, duplicate prevention, opt-out, buyer suppression, invalid contact handling, and exit conditions.",
            "Add calendar files or links with title, canonical time, duration, location, description, reminders, and update behavior.",
            "Test with labeled contacts across time zones and channels, verifying every send, link, merge field, suppression, reply route, and attendance record.",
            "Monitor delivery, bounce, complaint, opt-out, click, calendar, and attendance signals and repair failures before the highest-volume reminders.",
            "Stop live reminders after the event begins or ends as designed and route registrants into attendee or no-show follow-up.",
        ],
        "rules": [
            rule("Consent for SMS is absent or uncertain", "Do not send SMS; use an authorized channel.", "Registration does not automatically authorize every channel."),
            rule("A reminder contains the wrong time or link", "Pause affected sends, correct, and issue a clear correction to impacted recipients.", "Timing and access are critical facts."),
            rule("Deliverability degrades", "Inspect sender setup, content, list quality, cadence, and suppression before adding volume.", "More sends can worsen reputation."),
            rule("Registrants attend but show rate remains low overall", "Analyze source quality, promise, timing, confirmation, calendar, and reminder engagement by segment.", "Show-up is a system outcome."),
        ],
    },
    "Reporting and Optimization": {
        "outcome": "The event is evaluated across promotion, registration, attendance, engagement, pitch, sales, cash, and follow-up so the next decision addresses the real constraint.",
        "steps": [
            "Lock the analysis window, time zone, attribution basis, audience cohorts, offer, costs, and authoritative sources before pulling results.",
            "Collect spend, reach, registrations, source attribution, cost per registration, page conversion, delivery, and reminder engagement.",
            "Collect attendance, peak and retained viewers, duration, chat or poll engagement, pitch exposure, offer-link activity, and technical incidents.",
            "Collect applications, bookings, show rate, sales outcomes, purchases, cash, refunds, payment issues, and longer-tail pipeline.",
            "Reconcile ad, analytics, event platform, CRM, sales, and payment data; label missing, estimated, platform-reported, and verified values.",
            "Compare results with the approved scenario and separate measurement, traffic, page, show-up, presentation, offer, sales, and follow-up constraints.",
            "Use chat, questions, survey, call, and support evidence to explain behavior without overstating causation.",
            "Prioritize corrections by expected business impact, evidence strength, effort, and time before the next event; assign owners and success checks.",
            "Publish the audit, decision, next test plan, and reusable learning while keeping client-specific evidence in the appropriate restricted layer.",
        ],
        "rules": [
            rule("Data sources cannot be reconciled", "Resolve definitions and gaps before presenting precise conclusions.", "The audit must distinguish data failure from campaign failure."),
            rule("Registration is strong but attendance is weak", "Prioritize promise quality, source mix, timing, confirmation, calendar, and reminders.", "Acquisition alone is not the constraint."),
            rule("Attendance is strong but pitch conversion is weak", "Review audience-offer fit, transition, proof, value stack, clarity, checkout, and objections.", "More registrants may not solve a pitch problem."),
            rule("Night-of revenue is low but pipeline remains active", "Track the defined follow-up window before closing the result.", "Event economics may mature after the broadcast."),
        ],
    },
    "Slides and Visual QA": {
        "outcome": "The final deck supports the approved narrative, remains readable in the live environment, shows proof accurately, and contains no commercial or technical surprises.",
        "steps": [
            "Freeze the approved outline and offer source, then map every slide to opening, teaching, transition, pitch, objection, proof, or CTA purpose.",
            "Verify slide sequence preserves story, belief progression, interaction, benefit recaps, bridge, value stack, price, risk reversal, urgency, and next action.",
            "Review each slide for one clear idea, readable hierarchy, limited text, appropriate visual support, contrast, safe margins, and brand consistency.",
            "Verify names, dates, prices, values, guarantees, claims, statistics, quotes, testimonials, logos, permissions, links, and screenshots against sources.",
            "Check speaker notes, builds, animations, embedded media, fonts, aspect ratio, exports, click behavior, and backup PDF in the actual presentation environment.",
            "Run the deck on the event device and screen-share path, confirming remote readability and presenter control.",
            "Record corrections by slide number and severity, apply them to the identified version, and rerun affected content and visual checks.",
            "Obtain client and final reviewer approval, store editable and presentation versions, and prevent unreviewed late edits.",
        ],
        "rules": [
            rule("A slide is readable only on the editor's monitor", "Simplify and test it through the live screen-share view.", "Audience conditions define readability."),
            rule("A claim or offer fact differs from the source", "Block the deck until corrected.", "Live delivery magnifies factual inconsistency."),
            rule("Embedded media is unreliable", "Prepare and rehearse a local or static fallback.", "A single media failure should not stop the event."),
            rule("A late edit affects narrative or commerce", "Rerun content review and rehearsal for the affected section.", "Visual approval alone is insufficient."),
        ],
    },
    "Webinar Narrative and Outline": {
        "outcome": "The webinar moves the intended audience from relevance through belief change and useful teaching into a clear, credible next action.",
        "steps": [
            "Complete the audience and offer inputs: current beliefs, desired outcome, obstacles, mechanism, proof, objections, offer, CTA, and presenter story.",
            "Write the big idea, title, supporting promise, reason to attend live, and reason to stay through the end without overpromising the teaching.",
            "Design the opening to establish relevance, expectations, presenter credibility, interaction, and an honest statement that an offer may be presented.",
            "Map the presenter story to the audience problem and discovery of the mechanism, removing biography that does not advance belief or trust.",
            "Choose three core lessons or discoveries that replace limiting beliefs with useful truths, each supported by explanation, example, proof, and action.",
            "Add interaction, questions, micro-commitments, open loops, and benefit recaps at deliberate points rather than as decoration.",
            "Build the bridge from completed teaching to next options, obtain permission to continue, and introduce the offer as the supported implementation path.",
            "Outline components, value, proof, price, risk reversal, urgency, checkout, objections, Q&A, and repeated CTA from the approved offer sheet.",
            "Analyze the outline for missing logic, unsupported claims, excessive teaching, weak transition, timing, and audience-offer mismatch before scripting or design.",
        ],
        "rules": [
            rule("A lesson is useful but unrelated to the offer mechanism", "Remove, relocate, or connect it honestly.", "Teaching should create coherent progress, not random value."),
            rule("The content solves the entire implementation without a next-step need", "Clarify the difference between understanding and supported execution without withholding essentials.", "The event must teach genuinely while preserving offer relevance."),
            rule("The pitch appears without a logical bridge", "Add a recap, next-options frame, and permission transition.", "Abrupt selling breaks trust."),
            rule("The outline cannot fit the scheduled time", "Prioritize belief-changing teaching and offer clarity; cut optional examples.", "Timing pressure should not destroy the core sequence."),
        ],
    },
}
