"""Offers, messaging, and conversion executable SOP blueprints."""

from company_wiki_blueprints import TopicBlueprint, rule


OFFERS_BLUEPRINTS: dict[str, TopicBlueprint] = {
    "Brand Accelerator": {
        "outcome": "The team converts strategy and evidence into a practical visual and verbal system that production can apply consistently across conversion assets.",
        "steps": [
            "Collect the audience, positioning, offer, proof, voice, desired perception, existing brand assets, constraints, and representative customer touchpoints.",
            "Audit current pages, ads, emails, decks, video, social, and sales material for recurring signals, inconsistencies, and conversion friction.",
            "Define brand promise, positioning, personality, tone, approved vocabulary, prohibited language, and evidence requirements in operational terms.",
            "Create the visual direction with logo rules, typography, color roles, imagery, composition, iconography, motion, and accessibility requirements.",
            "Build representative components for headline, CTA, proof, offer, form, testimonial, comparison, and presentation use rather than a mood board alone.",
            "Apply the system to priority conversion assets and verify clarity, credibility, message continuity, mobile use, and production feasibility.",
            "Review with strategy, copy, design, conversion, and the final approver; resolve conflicts against audience and outcome evidence.",
            "Publish the approved guide, source files, examples, owners, and revision date, then retire contradictory versions.",
        ],
        "rules": [
            rule("A style choice reduces comprehension or credibility", "Choose clarity and customer trust over decoration.", "Brand exists to support the outcome."),
            rule("An existing client example is highly specific", "Keep it as evidence, not a universal rule.", "Examples should not become accidental dogma."),
            rule("A new asset needs a pattern not in the system", "Create and approve the reusable pattern before multiplying one-off variants.", "Systems reduce future guesswork."),
            rule("Accessibility and brand preference conflict", "Meet accessibility first and adapt the expression.", "Usability is a quality requirement."),
        ],
    },
    "Content and Community Funnel": {
        "outcome": "Content or community moves a defined audience from discovery through activation, ongoing value, and an appropriate commercial next step.",
        "steps": [
            "Define the audience, recurring problem, community or content promise, activation event, ongoing value, commercial path, and success measures.",
            "Map discovery, opt-in or join, onboarding, first win, engagement cadence, proof, qualification, offer, purchase, retention, and support stages.",
            "Choose content pillars and formats from audience evidence and assign each a role in awareness, belief, activation, proof, or conversion.",
            "Build onboarding that establishes expectations, navigation, rules, first action, support path, and a fast path to the first meaningful outcome.",
            "Create the operating cadence for content, events, prompts, moderation, recognition, questions, and customer feedback with named owners.",
            "Design commercial transitions that follow demonstrated value and intent without manufacturing engagement or hiding the offer.",
            "Connect tracking, CRM, tags, attribution, moderation, support, and buyer suppression, then test representative journeys.",
            "Review activation, engagement quality, retention, appointments, sales, support load, and customer outcomes; improve the verified constraint.",
        ],
        "rules": [
            rule("Members join but do not complete the first action", "Simplify onboarding and strengthen the first-win path.", "Activation precedes durable engagement."),
            rule("Engagement is high but commercial intent is weak", "Inspect audience, promise, problem depth, and transition—not vanity activity.", "Conversation alone is not the business path."),
            rule("Promotion overwhelms value delivery", "Restore the agreed value cadence and segment commercial messages.", "Trust falls when every interaction sells."),
            rule("Moderation or support capacity is insufficient", "Limit growth or add coverage before increasing acquisition.", "Community quality requires operations."),
        ],
    },
    "Conversion Optimization": {
        "outcome": "The team improves the largest verified customer-journey constraint through controlled, measurable changes tied to downstream value.",
        "steps": [
            "Validate analytics, attribution, CRM, sales, payment, and qualitative evidence before selecting a conversion problem.",
            "Map stage volumes and rates from traffic through customer outcome, using consistent cohorts, windows, and definitions.",
            "Identify the constraint with the greatest business impact rather than the most visible or easiest page element.",
            "Use recordings, surveys, interviews, sales calls, support, search, and behavior to explain why the constraint may exist.",
            "Write a hypothesis linking one customer problem to one proposed change, primary metric, quality guardrail, and decision rule.",
            "Prioritize by evidence strength, expected impact, effort, risk, and learning value; define the required implementation and QA.",
            "Launch the change with version tracking and sufficient exposure, avoiding simultaneous uncontrolled changes.",
            "Evaluate conversion, lead or buyer quality, revenue, refunds, and longer-term outcome; keep, iterate, retest, or reverse.",
        ],
        "rules": [
            rule("Data quality is uncertain", "Repair or label measurement before optimizing.", "A false constraint wastes effort."),
            rule("A change lifts the local metric but harms downstream quality", "Reject it as a business winner.", "Optimization must serve the full journey."),
            rule("Traffic is insufficient for a conclusive experiment", "Use research, longer windows, or larger changes and label evidence directional.", "Low volume cannot support false precision."),
            rule("Several changes ship together", "Treat the result as a package and design follow-up isolation if needed.", "Causal learning is limited."),
        ],
    },
    "Copy Platform": {
        "outcome": "Ads, pages, emails, webinars, and sales assets draw from one evidence-backed message foundation without guessing audience, promise, proof, or voice.",
        "steps": [
            "Gather customer interviews, sales calls, reviews, surveys, search, community language, performance evidence, offer details, and approved claims.",
            "Define the buying situation, audience segments, current problem, consequences, desired future, alternatives tried, objections, and decision criteria.",
            "Separate verbatim evidence from interpretation and link every important message claim to a source or approved working hypothesis.",
            "Write the primary promise, supporting outcomes, unique mechanism, why-now context, proof hierarchy, risk reversal, and action in plain language.",
            "Create three to five message pillars, each with belief to change, argument, proof, examples, objections, and phrases the audience actually uses.",
            "Document voice, tone range, approved phrases, prohibited claims, terminology, metaphor boundaries, and client-specific language that should not generalize.",
            "Build a message matrix by awareness stage and asset type so teams know what to emphasize in ads, pages, email, webinar, and sales.",
            "Test the platform by drafting representative assets and checking message continuity, specificity, evidence, and differentiation.",
            "Approve and version the platform, then update it when the offer, market evidence, proof, or customer language materially changes.",
        ],
        "rules": [
            rule("A statement sounds strong but has no evidence", "Label it a hypothesis or remove it.", "The platform is a source of truth, not a swipe file."),
            rule("Segments have materially different problems or awareness", "Create segment-specific branches under the shared foundation.", "One message should not flatten distinct buying situations."),
            rule("An asset repeatedly needs language outside the platform", "Review whether evidence changed or the asset is off-strategy.", "Recurring exceptions signal a platform gap."),
            rule("Client language conflicts with how customers speak", "Preserve the decision but present the evidence and testable alternative.", "Internal preference should not erase market truth."),
        ],
    },
    "Email Sequence Design": {
        "outcome": "Each recipient enters, receives, and exits an accurate email journey that advances one defined customer action without conflicting messages.",
        "steps": [
            "Define audience segment, entry event, current state, desired action, offer, timing, consent basis, sender, and authoritative facts.",
            "Map the sequence purpose and progression across acknowledgement, value, proof, objection handling, urgency, CTA, and post-action state.",
            "Specify each email's send condition, delay, subject, job, evidence, CTA, destination, personalization, and exit condition.",
            "Write from the copy platform using one clear idea per email and accurate dates, prices, links, identity, proof, and expectations.",
            "Configure triggers, branches, waits, time zones, duplicate prevention, buyer or converter suppression, unsubscribe, and reply routing.",
            "Test every branch with labeled contacts, verifying sender setup, merge fields, rendering, links, tracking, CRM changes, and exits.",
            "Launch to the intended segment and monitor delivery, bounce, complaint, unsubscribe, click, reply, conversion, and downstream quality.",
            "Improve the actual constraint and preserve version lineage; do not optimize subject lines while the path or offer is broken.",
        ],
        "rules": [
            rule("A recipient reaches the goal", "Exit acquisition messaging and enter the correct next state.", "State-aware communication prevents confusion."),
            rule("Consent or sender authority is unclear", "Do not send until the approved basis is confirmed.", "Deliverability and compliance begin with permission."),
            rule("A date, price, or link changes", "Update every scheduled and automated occurrence and retest.", "Automations can repeat stale facts at scale."),
            rule("Delivery degrades", "Inspect authentication, list quality, complaints, content, cadence, and reputation before adding sends.", "More volume can worsen the root problem."),
        ],
    },
    "Funnel Build Workflow": {
        "outcome": "Approved strategy and copy become a tested mobile and desktop customer journey with working integrations, tracking, ownership, and rollback.",
        "steps": [
            "Freeze the approved funnel map, offer, copy, brand inputs, required pages, conversions, integrations, events, and acceptance criteria.",
            "Create the build record with page URLs, environment, owner, reviewer, source files, dependencies, credentials path, and release plan.",
            "Build the page hierarchy and components mobile-first from approved content, preserving message continuity and one primary action per stage.",
            "Configure forms, validation, checkout, calendar, CRM, pipeline, notifications, email or SMS, redirects, and suppression from the funnel map.",
            "Install analytics, ad events, attribution parameters, consent behavior, domains, and cross-domain tracking where required.",
            "Run unit checks on content, layout, links, forms, integrations, events, accessibility basics, speed, and error states.",
            "Submit labeled end-to-end tests from representative sources and verify every customer, data, notification, and reporting handoff.",
            "Correct and retest failures, obtain final approval, publish the reviewed version, and monitor the first live conversions.",
        ],
        "rules": [
            rule("Approved copy or offer is missing", "Block the dependent build or use an explicitly labeled placeholder outside production.", "Builders should not invent strategy."),
            rule("A test succeeds visually but data routing fails", "Keep launch blocked.", "A funnel includes the downstream system."),
            rule("A late change touches shared components or automation", "Retest all affected paths.", "Shared dependencies broaden impact."),
            rule("The live release causes harm", "Use the documented rollback or pause affected traffic.", "Releases must be reversible."),
        ],
    },
    "Landing Page Copy": {
        "outcome": "A qualified visitor can quickly understand relevance, problem, mechanism, proof, offer, objections, and one primary next action.",
        "steps": [
            "Confirm traffic source, audience awareness, promise, conversion action, offer, proof, objections, voice, and page constraints from approved sources.",
            "Write the above-the-fold section with audience relevance, specific outcome, supporting context, proof signal, and one visible CTA.",
            "Develop the problem and stakes using customer evidence without exaggeration or treating the reader as a stereotype.",
            "Explain the mechanism or process simply enough to create understanding and differentiation before presenting features.",
            "Translate deliverables into benefits and outcomes, then support important claims with testimonials, demonstrations, data, or authority.",
            "Present offer terms, price or next-step expectation, risk reversal, eligibility, FAQs, objections, and repeated CTA consistently.",
            "Edit for mobile scanning, hierarchy, specificity, natural voice, truthful urgency, accessibility, and message continuity with traffic.",
            "Review every fact and claim, build the page, test the complete conversion path, and improve from behavior plus downstream quality.",
        ],
        "rules": [
            rule("Traffic sources carry different promises", "Create aligned variants or narrow the page promise.", "One page cannot resolve contradictory expectations."),
            rule("A section does not advance understanding, trust, desire, or action", "Remove or rewrite it.", "Length should earn its place."),
            rule("Proof is impressive but irrelevant to the reader's decision", "Use more relevant evidence or explain applicability honestly.", "Proof works through relevance."),
            rule("Conversion rises but lead or buyer quality falls", "Add qualification and inspect promise mismatch.", "The page must serve the business outcome."),
        ],
    },
    "Lead Form and Application Funnel": {
        "outcome": "The form captures only necessary information, sets expectations, qualifies appropriately, and routes every submission to the correct owner and follow-up.",
        "steps": [
            "Define the conversion goal, required qualification, sales capacity, privacy basis, follow-up, and data needed to take the next action.",
            "Choose form depth and steps based on intent and operational use; remove fields that no owner or decision actually uses.",
            "Write clear labels, help text, validation, consent, privacy, error, and next-step language for mobile and desktop completion.",
            "Define qualification and routing rules for qualified, unqualified, duplicate, spam, existing customer, and incomplete submissions.",
            "Configure CRM fields, source attribution, pipeline, owner, notification, calendar or checkout, nurture, and suppression.",
            "Build success and alternate paths that accurately explain what happens next without firing inappropriate conversion signals.",
            "Submit labeled test records covering every rule and verify page, database, CRM, event, notification, assignment, and follow-up behavior.",
            "Monitor completion, validation failures, qualification, appointment, show, sales, complaints, and data quality; improve the verified friction.",
        ],
        "rules": [
            rule("A field has no operational use", "Remove it or document why it is required.", "Unnecessary friction and data collection create risk."),
            rule("Unqualified submissions train the paid optimization event", "Separate routing and events.", "Signal quality shapes acquisition quality."),
            rule("A qualified lead has no owner", "Block launch or provide monitored fallback ownership.", "Intent decays without response."),
            rule("Form completion falls after a change", "Inspect mobile behavior, errors, load, field burden, and source-message match.", "The visible rate has several possible causes."),
        ],
    },
    "Market Research": {
        "outcome": "Strategy and copy use traceable customer language and evidence about situations, pains, desires, alternatives, objections, proof, and awareness.",
        "steps": [
            "Write the research decision: what offer, audience, message, creative, or funnel choice this work must inform.",
            "Define participant and evidence criteria so the sample matches the buying situation rather than collecting convenient opinions.",
            "Gather interviews, sales calls, support, reviews, surveys, communities, search, competitor, performance, and client evidence with source metadata.",
            "Extract verbatim language and tag context, problem, stakes, outcome, alternative, objection, trigger, proof, and awareness without rewriting it first.",
            "Separate repeated patterns, strong outliers, internal assumptions, and unsupported interpretations.",
            "Synthesize implications for offer, message, creative, sales, page, and testing while linking each conclusion to evidence.",
            "Review findings with customer-facing functions and challenge contradictions or selection bias.",
            "Publish the evidence bank, findings, decisions, unknowns, and recommended tests; refresh when market or offer conditions change.",
        ],
        "rules": [
            rule("Evidence comes only from internal opinions", "Do not label it market research.", "Customer truth requires customer or behavioral evidence."),
            rule("A loud quote appears once", "Preserve it as an outlier until corroborated.", "Vivid does not mean representative."),
            rule("Sources disagree", "Segment the context and prefer newer applicable evidence where lineage is real.", "Different buyers or situations may both be valid."),
            rule("Research cannot answer the decision", "Gather the missing evidence or design a test.", "More notes are not automatically useful research."),
        ],
    },
    "Mechanism Validation": {
        "outcome": "The offer's explanation of why the old way fails and the new approach works is understandable, supportable, relevant, and consistent across assets.",
        "steps": [
            "Define the audience's current approach, desired outcome, failure pattern, existing beliefs, alternatives, and evidence from research.",
            "Name the root cause or constraint the mechanism addresses without inventing science, certainty, or exclusivity.",
            "Describe the new process in simple causal steps and connect each step to an obstacle or outcome the audience recognizes.",
            "Collect proof for the mechanism through demonstrations, examples, customer results, expert basis, data, or operational logic.",
            "Write the old-way/new-way explanation, unique name if useful, proof, boundaries, and what the mechanism does not guarantee.",
            "Test comprehension and credibility with prospects, buyers, sales, and delivery; capture verbatim confusion and objections.",
            "Refine language, remove jargon, and align mechanism across offer, copy, creative, webinar, sales, and fulfillment.",
            "Approve the validated version and define the next evidence required when confidence remains limited.",
        ],
        "rules": [
            rule("The mechanism is only a renamed common tactic", "State the real differentiation or drop the novelty claim.", "Naming alone does not create uniqueness."),
            rule("The explanation requires unsupported causal claims", "Qualify or redesign it.", "Credibility is more durable than drama."),
            rule("Prospects cannot repeat the mechanism", "Simplify the causal chain and use a clearer example.", "Comprehension is a validation condition."),
            rule("Delivery does not match the marketed mechanism", "Align operations or messaging before launch.", "The promise must describe the actual experience."),
        ],
    },
    "Offer Design": {
        "outcome": "A specific market receives a clear, deliverable, differentiated, and testable path to a valued transformation.",
        "steps": [
            "Define the target buying situation, urgent problem, desired transformation, existing alternatives, objections, constraints, and willingness evidence.",
            "State the offer as who it helps, what outcome it supports, how, in what timeframe, with what customer responsibility and limits.",
            "Design the core delivery process and components from required customer progress, not from a list of available company activities.",
            "Set access, support, timeline, capacity, eligibility, fulfillment ownership, and experience so the promise can be delivered consistently.",
            "Choose price and payment structure using value, alternatives, economics, capacity, risk, and market evidence rather than arbitrary anchoring.",
            "Add proof, bonuses, risk reversal, and real urgency only where each improves decision clarity or removes a real obstacle.",
            "Model acquisition, sales, delivery, cash, refund, support, and margin scenarios and identify the assumptions requiring validation.",
            "Review with strategy, sales, delivery, finance, and compliance; publish the offer sheet and test plan before scaling.",
        ],
        "rules": [
            rule("The promise exceeds delivery evidence", "Reduce, qualify, or validate before promotion.", "An exciting offer must remain fulfillable."),
            rule("The offer serves several incompatible audiences", "Choose a primary segment or create separate versions.", "Specificity improves message and delivery."),
            rule("Economics depend on unrealistic conversion or retention", "Redesign price, cost, scope, or acquisition assumptions.", "A spreadsheet cannot rescue impossible unit economics."),
            rule("The offer is new", "Treat it as a hypothesis with bounded scale and learning goals.", "Unvalidated offers should not be treated as established truth."),
        ],
    },
    "Order Bumps": {
        "outcome": "Checkout offers one simple, complementary addition that improves customer use or outcome without confusing or weakening the core purchase.",
        "steps": [
            "Review the main purchase, immediate next obstacle, common add-on demand, delivery capacity, refund reasons, and checkout constraints.",
            "Choose an item that complements the main purchase and is not required for the core offer to function as promised.",
            "Define the bump's promise, contents, price, fulfillment, eligibility, support, refund treatment, and relationship to the main product.",
            "Write concise checkout copy covering what it is, why it helps now, what is included, price, and the accept control.",
            "Design the selection so default state, price change, consent, and removal are clear and nondeceptive.",
            "Configure product, tax, payment, fulfillment, confirmation, CRM, analytics, and buyer communication.",
            "Test accepted, declined, duplicate, failed-payment, refund, mobile, and support paths with labeled transactions.",
            "Review take rate, main conversion, revenue, refund, support, and customer outcome; keep only if total value improves.",
        ],
        "rules": [
            rule("The bump is necessary for the main promise", "Move it into the core offer.", "Required functionality should not be hidden at checkout."),
            rule("Adding the bump reduces main conversion or trust", "Simplify, reposition, or remove it.", "Incremental revenue should not damage the purchase."),
            rule("Fulfillment or refund behavior is unclear", "Do not launch until the complete path is defined.", "Checkout additions create real obligations."),
            rule("Take rate is high but complaints or refunds rise", "Evaluate net customer and business impact, not acceptance alone.", "A coerced yes is not success."),
        ],
    },
    "Post-Purchase Experience": {
        "outcome": "A buyer immediately receives accurate confirmation, access, expectations, support, and the next activation action while acquisition messaging stops.",
        "steps": [
            "Map successful, pending, failed, duplicate, refunded, financed, and manually closed purchase states plus their authoritative systems.",
            "Create confirmation that states what was purchased, amount or payment state, receipt path, access timing, support, and next action.",
            "Provision product, community, appointment, onboarding, or delivery access according to the offer and verify entitlement.",
            "Apply buyer tags, pipeline or customer state, internal ownership, notifications, attribution, and acquisition suppression.",
            "Send onboarding communication focused on access, expectations, preparation, first win, support, and scheduled milestones before more promotion.",
            "Test every purchase state with labeled transactions and verify payment, receipt, access, CRM, email, SMS, analytics, and support behavior.",
            "Monitor failed access, time to activation, support contacts, refunds, disputes, attendance, and early customer outcomes.",
            "Correct recurring friction at the system source and update the offer or pre-purchase expectation when mismatch is causal.",
        ],
        "rules": [
            rule("Payment succeeds but access fails", "Treat as a customer-impact incident and restore access promptly.", "The company has accepted payment without delivering the immediate obligation."),
            rule("A buyer remains in acquisition promotion", "Suppress and repair the state transition.", "Conflicting messages harm trust."),
            rule("The next action is unclear", "Simplify onboarding around one activation step.", "Early momentum depends on clarity."),
            rule("Refund reasons repeat", "Investigate offer expectation, checkout, onboarding, and delivery alignment.", "Refund patterns are product and message evidence."),
        ],
    },
    "Split Testing": {
        "outcome": "A controlled experiment answers one decision question with predefined evidence, guardrails, and a documented keep, iterate, or stop decision.",
        "steps": [
            "Identify the verified constraint and write the business decision the experiment must inform.",
            "State hypothesis, control, variant, changed variable, audience, primary metric, quality guardrail, and expected mechanism before launch.",
            "Define allocation, event, minimum exposure or duration, data exclusions, stopping conditions, and decision thresholds appropriate to volume.",
            "Build and QA each version, preserving message, technical, attribution, and version lineage except for the intended difference.",
            "Launch comparably and avoid mid-test changes, audience contamination, repeated peeking decisions, or incompatible time windows.",
            "Monitor technical integrity and guardrail harm without declaring a winner from early noise.",
            "Analyze primary and downstream outcomes, uncertainty, segment differences, implementation defects, and external changes.",
            "Choose keep, iterate, retest, or stop; document the evidence, limitations, rollout, and next question.",
        ],
        "rules": [
            rule("The test changes several material variables", "Treat it as a package test or redesign it.", "Causal interpretation is limited."),
            rule("Minimum evidence is not reached", "Mark the result inconclusive.", "A forced answer is worse than no answer."),
            rule("A guardrail shows material harm", "Stop or contain according to the predefined rule.", "Learning does not justify uncontrolled damage."),
            rule("A winner cannot be implemented consistently", "Resolve operational feasibility before rollout.", "A theoretical lift is not a usable system."),
        ],
    },
    "Upsells and Downsells": {
        "outcome": "The post-purchase path offers a logical acceleration or alternative without deceptive friction, duplicate promises, or unsupported delivery.",
        "steps": [
            "Map the main purchase, customer's next likely obstacle, acceleration opportunity, inability or reason to decline, and existing entitlements.",
            "Design the upsell as a distinct next value and the downsell as a legitimate fit alternative, not a confusing duplicate.",
            "Define promise, contents, price, payment, eligibility, fulfillment, support, refund, and effect on the original purchase.",
            "Write concise pages or scripts with context, outcome, proof, clear accept and decline paths, and accurate one-click purchase disclosure.",
            "Configure products, payment, taxes, entitlement, CRM, attribution, confirmation, buyer state, and prevention of duplicate purchase.",
            "Test accept, decline, downsell, back navigation, duplicate, payment failure, refund, mobile, and support paths.",
            "Launch with source and customer-state segmentation and monitor revenue, take rate, main-offer impact, refunds, support, and outcomes.",
            "Keep, revise, or remove from net value and customer evidence rather than gross revenue alone.",
        ],
        "rules": [
            rule("The upsell is required to achieve the original promise", "Include it in the core offer or correct the original promise.", "Post-purchase cannot repair an incomplete sale."),
            rule("Decline is hidden or difficult", "Make it clear and functional.", "Choice must be genuine."),
            rule("A buyer already owns the offered item", "Suppress or show an appropriate alternative.", "Duplicate selling creates disputes."),
            rule("Revenue rises but refunds or support rise more", "Evaluate net margin and customer outcome before keeping it.", "Gross lift can hide total harm."),
        ],
    },
    "VSL Strategy and Script": {
        "outcome": "The VSL creates relevance, belief, proof, offer understanding, objection resolution, and one clear action in a spoken and visually supportable sequence.",
        "steps": [
            "Confirm traffic, awareness, audience, problem, mechanism, proof, offer, objections, CTA, voice, target length, and visual production constraints.",
            "Choose the VSL's argument and outline hook, problem, stakes, failed alternatives, root cause, mechanism, proof, offer, objections, risk reversal, and CTA.",
            "Write the opening for immediate audience recognition and a specific reason to continue without unsupported curiosity or delay.",
            "Develop the problem and mechanism with causal clarity, customer language, examples, and visual opportunities rather than abstract claims.",
            "Sequence proof where each doubt arises using demonstrations, results, authority, testimonials, and transparent limitations.",
            "Present components as progress, explain price and terms, resolve core objections, state risk reversal and urgency accurately, and demonstrate the next action.",
            "Edit for spoken rhythm, sentence length, voice, repetition, transitions, timing, captions, and visual direction; read the full script aloud.",
            "Verify claims and offer facts, record or produce, review final audio and visuals, test the destination, and improve from retention plus conversion quality.",
        ],
        "rules": [
            rule("Retention falls before the mechanism is understood", "Tighten opening, relevance, pacing, and early proof.", "The audience cannot convert after leaving."),
            rule("The script depends on unsupported claims", "Replace them with supportable proof or honest qualification.", "VSL format does not reduce claim responsibility."),
            rule("The offer appears disconnected from teaching", "Strengthen the transition and implementation logic.", "The CTA should follow the argument."),
            rule("Shorter and longer traffic states differ", "Create aligned variants rather than one compromised script.", "Awareness determines needed explanation."),
        ],
    },
    "Value Stack and Risk Reversal": {
        "outcome": "The buyer sees how each component removes an obstacle, what the complete offer requires, and how risk is shared through a truthful operational promise.",
        "steps": [
            "Map the customer journey, obstacles, desired milestones, core deliverables, support, access, capacity, and evidence.",
            "Tie each component to a specific obstacle and explain what it is, how it is used, payoff, proof, and customer responsibility.",
            "Remove redundant items and classify true core components, support, bonuses, and optional additions.",
            "Set truthful value framing from alternatives, effort, delay, or standalone utility without inventing inflated values.",
            "Define price, payment, fulfillment limits, eligibility, and any real deadline consistently across the commercial path.",
            "Design risk reversal with condition, qualifying actions, timeframe, promised remedy, exclusions, evidence, and processing owner.",
            "Test the stack and guarantee against common objections, delivery capacity, finance, support, legal, sales, checkout, and customer expectations.",
            "Approve the offer sheet and verify every asset uses the same terms before promotion.",
        ],
        "rules": [
            rule("A component does not remove an obstacle or increase outcome confidence", "Remove or reposition it.", "Stacks should clarify value, not inflate item count."),
            rule("A guarantee depends on actions the company cannot verify", "Redesign the condition and evidence.", "Operational ambiguity creates disputes."),
            rule("Risk reversal would threaten delivery or cash capacity", "Change the remedy, price, scope, or eligibility.", "A promise must remain sustainable."),
            rule("Commercial assets show different terms", "Block launch until reconciled.", "The customer must receive one offer truth."),
        ],
    },
    "Website and Funnel Review": {
        "outcome": "The review produces a prioritized, evidenced correction plan for clarity, message continuity, usability, technical function, tracking, and conversion.",
        "steps": [
            "Define page goal, traffic sources, audience, conversion action, approved offer, device mix, data window, and review scope.",
            "Walk the journey as the intended visitor and assess above-the-fold relevance, promise, CTA, proof, mechanism, offer, objections, and navigation.",
            "Test representative desktop and mobile layouts, links, forms, validation, calendar, checkout, media, accessibility basics, and error states.",
            "Submit labeled conversions and verify analytics, ad events, attribution, CRM, pipeline, notifications, automation, and reporting.",
            "Review speed and technical behavior with available evidence, separating measured failures from subjective preference.",
            "Use recordings, analytics, form data, sales, support, surveys, and customer language to explain observed friction.",
            "Prioritize findings by severity, customer impact, business impact, evidence, effort, dependency, and owner.",
            "Correct and retest critical failures, publish the owned backlog, and measure the highest-value changes after release.",
        ],
        "rules": [
            rule("A critical conversion path fails", "Block or pause affected traffic until retested.", "Known broken journeys should not remain live."),
            rule("A finding is only personal preference", "Label it as a hypothesis and seek customer or behavior evidence.", "Taste is not conversion proof."),
            rule("Tracking is unreliable", "Repair measurement before interpreting rates.", "Bad instrumentation can invent a funnel problem."),
            rule("Many issues exist", "Fix the largest verified constraint first while containing severe defects.", "A long list is not a strategy."),
        ],
    },
}
