"""Paid media executable SOP blueprints."""

from company_wiki_blueprints import TopicBlueprint, rule


PAID_MEDIA_BLUEPRINTS: dict[str, TopicBlueprint] = {
    "Account and Access Setup": {
        "outcome": "The paid-media team has least-privilege, recoverable access to the correct business, account, identity, billing, tracking, and destination assets before setup begins.",
        "steps": [
            "Open an access record listing the legal business, platform business manager, ad account, pages or channels, pixel or tag, catalog, billing profile, domains, and accountable client owner.",
            "Request role-based access through the platform's approved business or manager-account path; never request passwords, shared personal logins, or authentication codes in chat or documents.",
            "Confirm the invited account belongs to the correct person or controlled team identity, uses multi-factor authentication, and has only the permissions required for the assigned function.",
            "Verify the business, ad account, page, profile, catalog, pixel, domain, and billing entities are connected to one another and match the campaign brief.",
            "Open each required surface and perform a harmless read or draft action to prove access is functional rather than merely listed as granted.",
            "Record account IDs, permission level, access owner, approval timestamp, recovery contact, and evidence links without recording credentials or secret values.",
            "Review policy restrictions, unpaid balances, spending limits, verification status, disabled assets, and ownership disputes that could block launch.",
            "Have the accountable media owner accept the access handoff and schedule removal or review when the engagement or role ends.",
        ],
        "rules": [
            rule("A teammate can log in only through a client's personal credentials", "Stop and establish approved role-based access.", "Shared credentials create security, ownership, and recovery risk."),
            rule("The required asset is owned by another business manager", "Document ownership and obtain an authorized partner or transfer decision.", "Creating duplicates can fragment data and control."),
            rule("Billing or policy status blocks delivery", "Keep launch blocked and route the exact platform notice to the authorized owner.", "Campaign setup cannot override account enforcement."),
            rule("A role changes or the engagement ends", "Remove unnecessary permissions and confirm the remaining recovery path.", "Access should follow current responsibility."),
        ],
    },
    "Ad Copy System": {
        "outcome": "Each ad-copy batch turns approved research, offer, proof, and creative concepts into distinct, supportable messages ready for testing.",
        "steps": [
            "Gather the approved audience, problem, desired outcome, mechanism, offer, proof, objections, voice, prohibited claims, destination, and conversion action into one copy brief.",
            "Build a claim-and-proof table that pairs every material result statement with its source, allowed wording, conditions, and required disclaimer.",
            "Choose distinct angles tied to verified customer motivations or objections; name the hypothesis each angle is intended to test.",
            "Write multiple hooks for each angle using different entry mechanisms such as problem recognition, outcome, proof, contrast, curiosity, or direct qualification.",
            "Develop primary text that moves from hook to relevance, mechanism, proof, offer, objection handling, and one clear action without adding unsupported promises.",
            "Write headline, description, CTA, and on-creative text that match the landing-page promise and do not introduce a second competing message.",
            "Read the copy aloud, remove generic filler, verify platform length and policy constraints, and compare all facts with the source brief.",
            "Label every variant by angle, hook, format, audience, and version; submit the complete copy matrix for review with its evidence links.",
            "After launch, connect performance back to the exact copy variant and record what the result does and does not prove.",
        ],
        "rules": [
            rule("A claim has no source or cannot be qualified accurately", "Remove or rewrite it before review.", "Unsupported claims create policy and trust risk."),
            rule("Two variants change angle, format, and offer simultaneously", "Separate them into controlled concepts or label the test exploratory.", "A multi-variable result cannot identify the cause."),
            rule("Ad promise and destination promise differ", "Align the ad or page before launch.", "Message discontinuity damages conversion and data quality."),
            rule("A copy winner attracts low-quality leads", "Evaluate downstream quality and test a more qualifying message.", "Cheap response is not the business outcome."),
        ],
    },
    "Audience Strategy": {
        "outcome": "Campaign audiences reflect the buying situation, available signal quality, exclusions, privacy constraints, and a testable reason each segment may respond.",
        "steps": [
            "Define the conversion objective, buying situation, geography, language, eligibility, exclusions, and downstream capacity before selecting targeting.",
            "Inventory first-party sources, platform engagement, customer lists, site events, CRM stages, value data, and consent status; record volume and freshness.",
            "Describe the primary audience from verified behaviors, problems, context, and intent rather than unsupported demographic stereotypes.",
            "Create a segmentation map for cold, warm, existing lead, customer, exclusion, and retargeting groups with one purpose per segment.",
            "Choose broad, interest, keyword, lookalike, custom, or retargeting approaches based on platform signal maturity and the hypothesis being tested.",
            "Set audience windows, source events, seed rules, overlap controls, exclusions, and minimum viable sizes; document any platform limitation.",
            "Estimate reach, frequency risk, budget fit, creative-message match, and the event volume available for learning before launch.",
            "Build the audiences using the naming standard, capture configuration evidence, and have another media owner verify inclusions and exclusions.",
            "Review audience quality using downstream conversion and customer evidence, not only clicks, CPM, or lead count.",
        ],
        "rules": [
            rule("A seed source is small, stale, mixed-quality, or unconsented", "Do not treat its lookalike as a high-confidence audience.", "The model inherits the source signal."),
            rule("Audience overlap makes test cells compete", "Consolidate, exclude, or redesign the test.", "Self-competition obscures learning and may inflate cost."),
            rule("The account has strong conversion signal and sufficient volume", "Test broader targeting before adding unnecessary constraints.", "Platform optimization may outperform manual audience assumptions."),
            rule("Frequency rises while response quality falls", "Refresh creative, widen or rotate the audience, and inspect saturation by segment.", "Repeated exposure without relevance produces fatigue."),
        ],
    },
    "Budget Compliance": {
        "outcome": "Actual platform budgets, dates, pacing, and changes remain within the approved commercial limits and are traceable to an authorized decision.",
        "steps": [
            "Record the approved total, daily or lifetime budget, channel allocation, campaign dates, currency, tax treatment, and change authority in the media plan.",
            "Translate the approved amount into platform-level campaign and ad-set budgets, accounting for start time, end time, time zone, minimums, and existing spend.",
            "Check account spending limits, billing health, automated rules, shared budgets, bid controls, and overlapping campaigns that affect actual pacing.",
            "Calculate expected daily pacing and checkpoint totals, then define alert thresholds for underdelivery, overspend, or sudden platform acceleration.",
            "Have a second owner compare the platform draft with the approved plan before activation, preserving screenshots of amount, dates, and currency.",
            "Monitor spend at the agreed early and recurring checkpoints and reconcile platform totals with the budget ledger.",
            "Document every material budget change with reason, supporting data, authorized owner, old value, new value, and effective timestamp.",
            "At close, stop or schedule the campaign as intended, reconcile final spend, explain variance, and update reporting with the authoritative amount.",
        ],
        "rules": [
            rule("Projected spend exceeds the approved amount", "Reduce, pause, or obtain explicit authorization before the breach.", "Platforms may continue pacing faster than manual review."),
            rule("A change would be large relative to recent delivery", "Stage it and monitor learning and quality rather than making an abrupt jump.", "Large changes can destabilize delivery."),
            rule("Platform, card, and reporting totals differ materially", "Reconcile timing, currency, taxes, attribution, and account scope before reporting.", "Different totals may measure different things."),
            rule("No authorized owner is available for an urgent increase", "Maintain the approved budget.", "Urgency does not create spending authority."),
        ],
    },
    "Campaign Architecture and Naming": {
        "outcome": "Campaign structure and names reveal objective, funnel stage, audience, offer, geography, creative, and version without opening every configuration screen.",
        "steps": [
            "Start from the media-plan objective, conversion event, offer, market, funnel stage, budget method, and test questions rather than copying a legacy structure blindly.",
            "Choose the smallest campaign and ad-set structure that preserves required budget control, audience separation, reporting, and valid experimentation.",
            "Define the naming pattern for campaign, ad set, ad, audience, creative, and tracking parameters using stable identifiers and human-readable segments.",
            "Create a naming legend with allowed values, abbreviations, date format, and examples; store it with the campaign brief.",
            "Map each test variable to the level where it belongs and keep other settings controlled when the test is intended to answer one question.",
            "Build the platform draft and verify objective, event, budget, bid, schedule, audience, placements, identity, destination, tracking, and creative lineage.",
            "Compare names with the reporting and CRM attribution conventions so records can be joined without manual interpretation.",
            "Have a second media owner review the architecture and capture the approved draft before launch; do not rename live entities casually.",
        ],
        "rules": [
            rule("Two cells differ in several variables", "Label the comparison exploratory or redesign it as controlled tests.", "The result cannot isolate a causal variable."),
            rule("Structure fragments a small budget or event volume", "Consolidate until each unit can gather meaningful delivery.", "Over-segmentation starves learning."),
            rule("A name is wrong after launch but reporting IDs are stable", "Document the correction path and assess learning/reporting impact before renaming.", "Live renames may disrupt workflows and lineage."),
            rule("A new platform feature conflicts with the standard structure", "Test it in a bounded unit and update the naming legend if adopted.", "Standards should evolve from evidence, not ad hoc exceptions."),
        ],
    },
    "Creative Brief and Asset Plan": {
        "outcome": "Creative production begins with approved concepts, required claims and proof, exact formats, shot or design requirements, ownership, and a delivery matrix.",
        "steps": [
            "Bring the audience, problem, outcome, mechanism, offer, proof, objections, voice, destination, and campaign hypothesis into one creative brief.",
            "Define each concept as an angle plus hook plus visual mechanism plus proof plus CTA; explain what response or belief it is designed to change.",
            "Build an asset matrix listing concept ID, format, placement, aspect ratio, duration, copy variant, speaker or source, due date, owner, and destination.",
            "Specify required footage, static elements, product views, demonstrations, testimonials, charts, captions, branding, and prohibited visual or claim treatments.",
            "Link approved source material and reference examples, stating what to borrow—structure, pacing, composition, or mechanism—and what not to copy.",
            "Create the production plan for script, shoot, design, edit, review, corrections, exports, naming, storage, and platform upload.",
            "Review the brief with copy, media, design or production, and the final approver; resolve unclear inputs before work begins.",
            "Track delivery against the matrix and reject unlabeled or incomplete assets that cannot be tied to a concept and placement.",
        ],
        "rules": [
            rule("A concept has no audience belief or test hypothesis", "Return it for strategy clarification.", "Aesthetic variation alone does not create useful learning."),
            rule("Proof cannot be verified or permission is unclear", "Exclude it until verification and usage approval exist.", "Creative speed does not override evidence rights."),
            rule("A required placement lacks the correct format", "Create the native format or explicitly exclude the placement.", "Automatic cropping can destroy message and composition."),
            rule("Production capacity cannot deliver the full matrix", "Prioritize concepts by learning value and channel importance.", "A smaller complete test is better than many unfinished assets."),
        ],
    },
    "Creative Testing System": {
        "outcome": "Creative tests answer named questions, preserve variant lineage, protect delivery, and use downstream quality to decide keep, iterate, or stop.",
        "steps": [
            "Review the current control, audience, offer, funnel, spend, event volume, and recent creative results before proposing a test.",
            "State one primary hypothesis and the observable result that would support, weaken, or fail it.",
            "Select the variable—angle, hook, visual, format, proof, CTA, or spokesperson—and hold other material variables as stable as practical.",
            "Define the cells, IDs, audience, budget, placement, launch time, minimum run conditions, primary metric, quality metric, and stopping conditions.",
            "Run pre-launch checks on every cell and confirm tracking can report the exact creative lineage through downstream outcomes.",
            "Launch under comparable conditions, avoid premature edits, and record any delivery imbalance or platform behavior that affects interpretation.",
            "Evaluate response, conversion, cost, lead or buyer quality, fatigue, and business outcome; distinguish directional learning from a conclusive result.",
            "Choose keep, iterate, retest, or stop, document the evidence and limits, and convert the learning into the next brief rather than declaring a permanent universal winner.",
        ],
        "rules": [
            rule("A cell receives too little delivery for the predefined minimum", "Extend, consolidate, or mark the result inconclusive.", "No result is better than a false conclusion."),
            rule("A variant wins clicks but loses qualified outcomes", "Do not scale it as the business winner.", "Upstream attention can hide downstream damage."),
            rule("Several variables changed", "Treat the result as a concept comparison and design a follow-up isolation test.", "The causal element remains unknown."),
            rule("Performance decays with rising frequency", "Assess fatigue and refresh while preserving the original result record.", "A past winner can stop working."),
        ],
    },
    "DM Ads Workflow": {
        "outcome": "Direct-message campaigns attract the intended conversation, route it to an owned response process, and measure quality through booked or purchased outcomes.",
        "steps": [
            "Define the target person, conversation promise, qualifying intent, offer path, platform, and final business outcome for the DM campaign.",
            "Choose direct or indirect message framing and document the hypothesis, expected objection, and CTA that opens the conversation.",
            "Write ad copy and creative that set accurate expectations about what happens after the message, avoiding bait or unsupported urgency.",
            "Configure the campaign objective, destination, message template, qualifying prompts, privacy notices, tracking, and audience exclusions.",
            "Build the response playbook with opening response, qualification questions, routing conditions, objection handling, handoff, booking, and stop conditions.",
            "Assign coverage hours, first-response expectation, owner, backup, CRM logging method, and escalation for sensitive or abusive conversations.",
            "Test the ad-to-message flow on representative devices, submit test responses, and verify ownership, notification, CRM record, and appointment path.",
            "Launch and review message starts, qualified conversations, response time, appointment rate, show rate, sales outcome, and opt-out or complaint signals.",
            "Update the ad and response script from verified conversation evidence while preserving privacy and version lineage.",
        ],
        "rules": [
            rule("The team cannot cover expected message volume", "Reduce spend or delay launch until coverage exists.", "Unanswered conversations waste intent and harm experience."),
            rule("Message starts rise but qualification falls", "Tighten the ad promise, qualifying prompt, or audience.", "Conversation volume is not the target outcome."),
            rule("A prospect requests no further contact", "Stop the conversation and apply the required suppression.", "Consent and platform rules control continued messaging."),
            rule("Sensitive information is sent in the DM", "Move the interaction to the approved secure channel and limit stored copies.", "Ordinary messaging is not a secure records system."),
        ],
    },
    "Launch QA": {
        "outcome": "Every paid campaign passes account, objective, budget, audience, creative, destination, tracking, policy, and monitoring checks before activation.",
        "steps": [
            "Freeze the media-plan version and platform draft, recording the campaign IDs, reviewer, timestamp, and intended launch window.",
            "Verify business, ad account, identity, billing, permissions, policy state, and any spending limit against the access record.",
            "Check objective, optimization event, attribution setting, bid strategy, budget, schedule, time zone, geography, language, placements, and device settings.",
            "Verify audience source, inclusion, exclusions, size, overlap, retargeting window, seed quality, and privacy or consent requirements.",
            "Open every ad and compare name, concept, copy, creative crop, captions, CTA, identity, destination, tracking parameters, and disclosures with the approved sources.",
            "Test every destination and conversion path, then verify platform event, analytics event, CRM record, attribution, notification, and downstream ownership.",
            "Review policy-risk claims, personal attributes, restricted categories, testimonial permission, and offer consistency before publishing.",
            "Record each check as pass, fail, not applicable, or approved exception, correct failures, and retest the affected path.",
            "Assign early monitoring and rollback ownership, then activate only the exact reviewed version after explicit launch approval.",
        ],
        "rules": [
            rule("The optimization event does not fire correctly", "Block launch and repair measurement.", "The platform will optimize toward the configured signal."),
            rule("A destination or CTA is broken", "Block the affected ad until the full path passes.", "Paid traffic must not enter a failed journey."),
            rule("A material platform edit occurs after QA", "Rerun every affected check.", "QA evidence belongs to a specific configuration."),
            rule("Policy status is uncertain", "Use platform guidance or authorized review before activation.", "A preventable rejection can endanger the account and timeline."),
        ],
    },
    "Media Readiness Gate": {
        "outcome": "Paid traffic is withheld until strategy, offer, assets, funnel, tracking, sales response, fulfillment, and approvals can support the expected demand.",
        "steps": [
            "Confirm the campaign objective, offer, audience, proof, destination, budget, dates, and success definition are approved and mutually consistent.",
            "Verify the creative matrix contains enough approved concepts and native formats to launch and learn without relying on one fragile asset.",
            "Walk the landing, form, calendar, checkout, confirmation, follow-up, and fulfillment path using labeled test records.",
            "Verify conversion events, attribution parameters, CRM fields, pipeline stages, lead owner, notifications, and reporting reconciliation.",
            "Confirm sales or response coverage, scripts, speed expectations, capacity, and feedback loop to media.",
            "Confirm delivery capacity, offer terms, payment path, customer support, and suppression or buyer exclusion are ready.",
            "Collect platform access, billing, policy, client, legal, creative, funnel, and tracking approvals in the readiness record.",
            "Review blockers and decide ready, conditionally ready, or blocked; name every approved exception and monitoring control.",
        ],
        "rules": [
            rule("Tracking is incomplete", "Do not launch performance media unless an authorized exception defines alternate measurement.", "Unmeasured delivery cannot be managed responsibly."),
            rule("Sales or fulfillment cannot handle projected volume", "Reduce budget or delay until capacity is aligned.", "Media should not create unmanaged demand."),
            rule("Only one creative is ready", "Launch only if the limited learning and fatigue risk are explicitly accepted.", "Single-asset launches have weak resilience."),
            rule("A nonblocking item remains", "Launch only with owner, correction date, and monitoring plan.", "Conditional readiness must be explicit."),
        ],
    },
    "Meta Account Retraining": {
        "outcome": "Meta receives cleaner qualified-conversion feedback so delivery shifts away from low-quality leads and toward the downstream behavior the business values.",
        "steps": [
            "Confirm the symptom with funnel data: compare lead volume, qualification, booked appointments, shows, sales, and customer acquisition cost before changing Meta.",
            "Verify the current optimization event, pixel or Conversions API events, event priority, deduplication, domains, and campaign objective; correct measurement defects first.",
            "Define the qualification rule using observable form or CRM fields and document which outcomes count as qualified, unqualified, duplicate, spam, or unknown.",
            "Place automated lead scoring between the initial form or booking entry and the next funnel destination so routing occurs immediately and consistently.",
            "Route unqualified submissions to an alternate thank-you path that does not fire the qualified optimization event; retain only required analytics and consent behavior.",
            "Route qualified submissions to the intended booking or qualified thank-you path and fire the verified event Meta should learn from, using test identifiers for validation.",
            "Submit multiple qualified and unqualified test records and verify page routing, browser and server events, deduplication, CRM values, attribution, notifications, and reports.",
            "Launch a controlled campaign or event transition without contaminating the signal with old low-quality rules; document start time and baseline.",
            "Monitor cost per lead, qualified rate, appointment rate, show rate, sales rate, and acquisition cost long enough to judge downstream movement, not just early CPL.",
            "Keep, adjust, or roll back from the complete funnel evidence and record the qualification logic for future campaigns.",
        ],
        "rules": [
            rule("The conversion event or routing is technically wrong", "Repair and retest before calling the problem account learning.", "Meta can only optimize toward the signal it receives."),
            rule("Qualification is subjective or inconsistently recorded", "Standardize the scoring fields before sending qualified events.", "Noisy labels train noisy delivery."),
            rule("Qualified volume is too low for stable learning", "Use the closest reliable higher-volume event while improving volume and preserve downstream reporting.", "An ideal signal with no volume may not optimize."),
            rule("CPL rises while qualified acquisition cost improves", "Evaluate against the business outcome before reversing the change.", "Cheaper raw leads may be more expensive customers."),
        ],
    },
    "Monitoring and Triage": {
        "outcome": "Campaign anomalies are detected early, classified correctly, contained proportionally, and routed to the owner who can resolve the underlying cause.",
        "steps": [
            "Set monitoring checkpoints and guardrails for delivery, spend, budget pacing, policy, links, conversion events, lead routing, quality, and business outcomes before launch.",
            "At each checkpoint, compare current performance with plan, recent baseline, platform diagnostics, and downstream systems using the same date range and attribution basis.",
            "When an anomaly appears, record first observed time, affected entities, magnitude, recent changes, current risk, and source screenshots or IDs.",
            "Classify the issue as delivery, budget, creative, audience, tracking, destination, CRM, sales, offer, fulfillment, policy, billing, or external change.",
            "Contain active loss with the smallest reversible action while preserving healthy units and evidence.",
            "Test likely causes from source to destination, disproving alternatives instead of making several simultaneous edits.",
            "Escalate with impact, evidence, options, recommendation, owner, and latest safe decision time; state what is paused and what continues.",
            "Implement the approved correction, retest the affected path, monitor recovery, and document the final cause and prevention control.",
        ],
        "rules": [
            rule("Spend or customer harm is actively increasing", "Contain the affected unit immediately and notify the accountable owner.", "Waiting for certainty can increase loss."),
            rule("Only reporting is broken but platform delivery is healthy", "Preserve delivery when safe and repair measurement urgently.", "A reporting incident is not automatically a campaign failure."),
            rule("A normal statistical fluctuation has no supporting anomaly", "Continue monitoring until the predefined condition is met.", "Overreaction resets learning and creates noise."),
            rule("Several systems fail at once after one change", "Investigate the shared dependency first.", "A common cause is more likely than simultaneous independent failures."),
        ],
    },
    "Optimization and Scaling": {
        "outcome": "Budget and configuration changes increase verified business outcomes while preserving signal quality, measurement, and controlled downside.",
        "steps": [
            "Confirm tracking, attribution, CRM outcomes, sales feedback, and reporting reconciliation before interpreting a campaign as a winner or loser.",
            "Identify the current constraint at delivery, attention, click, conversion, qualification, sales, value, or fulfillment rather than optimizing the easiest visible metric.",
            "Define the proposed change, expected mechanism, primary outcome, guardrail, minimum evidence, monitoring window, and rollback condition.",
            "Prioritize reversible changes that address the verified constraint and avoid simultaneous edits that destroy attribution of learning.",
            "Scale budget in controlled stages appropriate to recent spend, event volume, learning state, audience size, and business capacity.",
            "Expand creative, audience, placement, geography, or offer only with a named hypothesis and clean lineage from the existing control.",
            "Monitor downstream lead quality, appointments, sales, revenue, refunds, capacity, and customer signals alongside platform metrics.",
            "Keep, iterate, or reverse the change at the predefined checkpoint and record what was learned plus the limits of the evidence.",
        ],
        "rules": [
            rule("Tracking or sales data is unreliable", "Pause optimization decisions and reconcile first.", "Scaling an uncertain result magnifies risk."),
            rule("A campaign is profitable but near fulfillment capacity", "Coordinate capacity or cap spend before scaling.", "Operational failure can erase media gains."),
            rule("A budget increase destabilizes cost or quality", "Return to the last stable level and diagnose before another change.", "Scaling should be reversible."),
            rule("A platform metric improves while business outcome worsens", "Optimize to the downstream outcome and inspect incentive mismatch.", "The platform proxy is not the final objective."),
        ],
    },
    "Video Ad Production": {
        "outcome": "Each video ad moves from evidence-backed concept through script, shoot, edit, native exports, approval, and labeled testing without losing message intent.",
        "steps": [
            "Start with a concept brief naming audience, problem, angle, hook, mechanism, proof, offer, CTA, format, placement, and hypothesis.",
            "Write for spoken delivery using a clear opening, relevance, explanation, proof, action, and optional pattern interrupts; verify every material claim.",
            "Create a shot plan with speaker, location, framing, aspect ratios, wardrobe, props, demonstrations, B-roll, sound, lighting, and required releases.",
            "Record clean primary takes plus hook and CTA variations, leaving edit handles and preserving original files using the naming standard.",
            "Back up and organize footage by campaign, concept, speaker, date, take, and usage rights before editing.",
            "Edit for immediate comprehension, pacing, captions, proof visibility, brand consistency, safe zones, platform duration, and one clear CTA.",
            "Export native placement versions and review audio, crop, captions, spelling, claims, identity, destination continuity, and technical specifications.",
            "Apply unit and final corrections to identified versions, then store approved masters and upload-ready exports with concept IDs.",
            "Connect platform results to the exact script, take, edit, and format so future production uses real learning.",
        ],
        "rules": [
            rule("The first seconds do not identify relevance or earn attention", "Test a stronger hook or visual opening before polishing the full edit.", "Weak openings waste the rest of the message."),
            rule("A speaker claim lacks evidence", "Remove, qualify, or obtain support before approval.", "Spoken claims carry the same policy risk as written copy."),
            rule("Automatic reframing cuts critical text or action", "Create a native crop for that placement.", "Safe composition differs by aspect ratio."),
            rule("A video wins attention but loses conversion quality", "Review message qualification and destination continuity.", "Engagement alone is not the goal."),
        ],
    },
    "Weekly Advertising Report": {
        "outcome": "Stakeholders receive a reconciled weekly explanation of spend, delivery, funnel quality, business outcomes, tests, risks, and next decisions.",
        "steps": [
            "Lock the reporting period, time zone, attribution basis, currency, included accounts, and comparison period before pulling data.",
            "Export or record platform spend, delivery, reach, frequency, CPM, clicks, CTR, conversions, cost, and creative or audience breakdowns.",
            "Pull analytics, CRM, appointment, sales, payment, refund, and quality data for the same cohort and date logic.",
            "Reconcile totals and label platform-reported, modeled, estimated, and verified business metrics rather than blending them.",
            "Explain what changed, why the evidence suggests it changed, and what remains uncertain; separate observation from hypothesis.",
            "Report test status by hypothesis, cells, evidence, downstream quality, and decision rather than announcing isolated winners.",
            "Name risks, blockers, fatigue, tracking gaps, capacity constraints, and decisions needed with owner and deadline.",
            "Recommend the next week's keep, stop, iterate, scale, or investigate actions and state the expected outcome plus guardrails.",
            "Verify figures and links, send through the approved channel, and convert approvals or questions into recorded tasks and decisions.",
        ],
        "rules": [
            rule("Systems use different windows or attribution", "Normalize or label the difference before comparison.", "Apparent disagreement may be a definition problem."),
            rule("A metric is unavailable or untrusted", "State the gap and the repair plan; do not substitute a convenient proxy silently.", "Missing truth should remain visible."),
            rule("Platform efficiency improves but qualified outcomes fall", "Highlight the downstream decline and investigate signal quality.", "The report serves business outcomes."),
            rule("A recommendation lacks a named constraint and success check", "Rewrite it as a testable action.", "Vague optimization cannot be governed."),
        ],
    },
}
