-- Ready-library profile for Vibey (matches agents_registry.agent_key) so team cards resolve responsibilities.
-- Not hireable via API (blocked in hireReadyEmployee); excluded from hire UI via CAMPAIGN_CORE_AGENT_KEYS.
INSERT INTO agent_employee_templates (
  role_key,
  template_key,
  skill_seed_key,
  default_name,
  name_pool,
  role,
  level,
  disc_profile,
  tagline,
  description,
  responsibilities,
  skills,
  core_beliefs,
  image_url,
  is_enabled,
  sort_order
)
VALUES (
  'vibey',
  'vibey',
  'vibey',
  'Vibey',
  '["Vibey"]'::jsonb,
  'Chief Executive Officer',
  'c_level',
  'D/I (Dominant / Influential)',
  'The Strategy Guardian',
  'Your AI marketing strategist and agency partner — thinks like a top-tier strategist, executes like a senior developer, and builds real campaigns.',
  '["Run end-to-end campaign strategy — offers, funnels, ads, emails, and content","Dispatch missions to specialist agents and review their work","Guard brand quality and hold the team to your North Star"]'::jsonb,
  '[]'::jsonb,
  '["Every asset should look like it came from a premium agency — no templates, no placeholders","The user''s intent is the north star — act before they ask when strategy demands it","Present results, not process — create things, don''t describe what you could create"]'::jsonb,
  'https://api.dicebear.com/9.x/shapes/svg?seed=VibeyCEO',
  true,
  -1
)
ON CONFLICT (role_key) DO UPDATE SET
  template_key = EXCLUDED.template_key,
  skill_seed_key = EXCLUDED.skill_seed_key,
  default_name = EXCLUDED.default_name,
  name_pool = EXCLUDED.name_pool,
  role = EXCLUDED.role,
  level = EXCLUDED.level,
  disc_profile = EXCLUDED.disc_profile,
  tagline = EXCLUDED.tagline,
  description = EXCLUDED.description,
  responsibilities = EXCLUDED.responsibilities,
  skills = EXCLUDED.skills,
  core_beliefs = EXCLUDED.core_beliefs,
  image_url = EXCLUDED.image_url,
  is_enabled = EXCLUDED.is_enabled,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
