-- Seed ScrapeCreators integration_capabilities (embedding null until syncCapabilities runs with GEMINI).
insert into public.integration_capabilities (
  integration_id,
  action_slug,
  execution_mode,
  display_name,
  description,
  parameters,
  examples,
  metadata,
  domains,
  route_config,
  updated_at
)
values
  (
    'scrapecreators',
    'tiktok_profile',
    'legacy',
    'TikTok profile (ScrapeCreators)',
    'Use when you need TikTok public profile metadata (bio, stats, links). Do not use for transcripts—use tiktok_video_transcript. Only after native tools failed or user explicitly needs ScrapeCreators fields. Params: handle (no @).',
    '{"handle":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/tiktok/profile","query_params":{"handle":"handle"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'tiktok_video_transcript',
    'legacy',
    'TikTok video transcript (ScrapeCreators)',
    'Use when the user needs a TikTok video transcript and extract_url_transcript / yt-dlp already failed, timed out, or rate-limited. Pass the full TikTok video URL as url. Costs credits.',
    '{"url":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/tiktok/video/transcript","query_params":{"url":"url"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'instagram_profile',
    'legacy',
    'Instagram profile (ScrapeCreators)',
    'Use for Instagram public profile data when Caligraph/native paths are insufficient. Params: handle (username, no @). Not for transcripts—use instagram_media_transcript.',
    '{"handle":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/instagram/profile","query_params":{"handle":"handle"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'instagram_media_transcript',
    'legacy',
    'Instagram reel/post transcript (ScrapeCreators)',
    'Use when you need Instagram reel/post transcript and extract_url_transcript / yt-dlp already failed. Pass media or share URL as url. Costs credits.',
    '{"url":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/instagram/media/transcript","query_params":{"url":"url"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'youtube_video_transcript',
    'legacy',
    'YouTube video transcript (ScrapeCreators)',
    'Use only after YouTube captions + extract_url_transcript / yt-dlp failed for this video. Pass watch or youtu.be URL as url. Costs credits.',
    '{"url":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/youtube/video/transcript","query_params":{"url":"url"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'youtube_channel',
    'legacy',
    'YouTube channel details (ScrapeCreators)',
    'Use when you need channel metadata from a channel URL and other methods are insufficient. Pass channel URL as url.',
    '{"url":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/youtube/channel","query_params":{"url":"url"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'twitter_profile',
    'legacy',
    'X (Twitter) profile (ScrapeCreators)',
    'Use for X/Twitter public profile by handle when needed. Params: handle (no @). For tweet video/audio transcript use twitter_tweet_transcript.',
    '{"handle":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/twitter/profile","query_params":{"handle":"handle"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'twitter_tweet_transcript',
    'legacy',
    'X tweet transcript (ScrapeCreators)',
    'Use when you need transcript for an X post/video and extract_url_transcript / yt-dlp failed. Pass tweet URL as url. Costs credits.',
    '{"url":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/twitter/tweet/transcript","query_params":{"url":"url"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'facebook_profile',
    'legacy',
    'Facebook profile (ScrapeCreators)',
    'Use for Facebook profile metadata when the user gave a profile URL. Pass url. Not for post transcripts.',
    '{"url":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/facebook/profile","query_params":{"url":"url"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'facebook_post_transcript',
    'legacy',
    'Facebook post transcript (ScrapeCreators)',
    'Use when you need a Facebook video/post transcript and extract_url_transcript / yt-dlp failed. Pass post URL as url. Costs credits.',
    '{"url":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/facebook/post/transcript","query_params":{"url":"url"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'linkedin_profile',
    'legacy',
    'LinkedIn person profile (ScrapeCreators)',
    'Use for public LinkedIn person profile data when the user provides a profile URL. Pass url. Respect privacy; costs credits.',
    '{"url":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/linkedin/profile","query_params":{"url":"url"}}'::jsonb,
    now()
  ),
  (
    'scrapecreators',
    'linkedin_company',
    'legacy',
    'LinkedIn company page (ScrapeCreators)',
    'Use for LinkedIn company page data when the user provides a company page URL. Pass url.',
    '{"url":{"type":"string","required":true}}'::jsonb,
    '[]'::jsonb,
    '{"manual_capability_copy":true}'::jsonb,
    array['marketing']::text[],
    '{"method":"GET","path":"/api/integrations/scrapecreators/linkedin/company","query_params":{"url":"url"}}'::jsonb,
    now()
  )
on conflict (integration_id, action_slug) do update set
  display_name = excluded.display_name,
  description = excluded.description,
  parameters = excluded.parameters,
  metadata = excluded.metadata,
  domains = excluded.domains,
  route_config = excluded.route_config,
  updated_at = excluded.updated_at;
