-- Keep the production strategy router and the capability validator in sync.
-- Chat fails before provider execution when a routed model or requested context tier is absent here.
insert into public.token_providers_pricing (
  provider,
  model_name,
  unit_type,
  cost_per_unit,
  is_active,
  notes,
  service_type,
  currency,
  context_window_tokens,
  max_output_tokens
)
values
  ('anthropic', 'claude-opus-5', 'input_tokens_1k', 0.005000, true, '$5/MTok input, OpenRouter verified', 'llm', 'USD', 1000000, 128000),
  ('anthropic', 'claude-opus-5', 'output_tokens_1k', 0.025000, true, '$25/MTok output, OpenRouter verified', 'llm', 'USD', 1000000, 128000),
  ('anthropic', 'claude-opus-5', 'cache_read_1k', 0.000500, true, '$0.50/MTok cache read, OpenRouter verified', 'llm', 'USD', 1000000, 128000),
  ('anthropic', 'claude-opus-5', 'cache_write_1k', 0.006250, true, '$6.25/MTok cache write, OpenRouter verified', 'llm', 'USD', 1000000, 128000),
  ('anthropic', 'claude-sonnet-5', 'input_tokens_1k', 0.002000, true, '$2/MTok input, OpenRouter verified', 'llm', 'USD', 1000000, 128000),
  ('anthropic', 'claude-sonnet-5', 'output_tokens_1k', 0.010000, true, '$10/MTok output, OpenRouter verified', 'llm', 'USD', 1000000, 128000),
  ('anthropic', 'claude-sonnet-5', 'cache_read_1k', 0.000200, true, '$0.20/MTok cache read, OpenRouter verified', 'llm', 'USD', 1000000, 128000),
  ('anthropic', 'claude-sonnet-5', 'cache_write_1k', 0.002500, true, '$2.50/MTok cache write, OpenRouter verified', 'llm', 'USD', 1000000, 128000),
  ('openai', 'gpt-5.6-sol', 'input_tokens_1k', 0.005000, true, '$5/MTok input, OpenRouter verified', 'llm', 'USD', 1050000, 128000),
  ('openai', 'gpt-5.6-sol', 'output_tokens_1k', 0.030000, true, '$30/MTok output, OpenRouter verified', 'llm', 'USD', 1050000, 128000),
  ('openai', 'gpt-5.6-sol', 'cache_read_1k', 0.000500, true, '$0.50/MTok cache read, OpenRouter verified', 'llm', 'USD', 1050000, 128000),
  ('openai', 'gpt-5.6-sol', 'cache_write_1k', 0.006250, true, '$6.25/MTok cache write, OpenRouter verified', 'llm', 'USD', 1050000, 128000),
  ('openai', 'gpt-5.6-terra', 'input_tokens_1k', 0.002500, true, '$2.50/MTok input, OpenRouter verified', 'llm', 'USD', 1050000, 128000),
  ('openai', 'gpt-5.6-terra', 'output_tokens_1k', 0.015000, true, '$15/MTok output, OpenRouter verified', 'llm', 'USD', 1050000, 128000),
  ('openai', 'gpt-5.6-terra', 'cache_read_1k', 0.000250, true, '$0.25/MTok cache read, OpenRouter verified', 'llm', 'USD', 1050000, 128000),
  ('openai', 'gpt-5.6-terra', 'cache_write_1k', 0.003125, true, '$3.125/MTok cache write, OpenRouter verified', 'llm', 'USD', 1050000, 128000)
on conflict (provider, model_name, unit_type) do update
set cost_per_unit = excluded.cost_per_unit,
    is_active = excluded.is_active,
    notes = excluded.notes,
    service_type = excluded.service_type,
    currency = excluded.currency,
    context_window_tokens = excluded.context_window_tokens,
    max_output_tokens = excluded.max_output_tokens,
    updated_at = now();

insert into public.llm_model_capabilities (
  provider,
  model_name,
  display_name,
  is_active,
  is_selectable,
  source,
  context_window_tokens,
  max_output_tokens,
  input_modalities,
  output_modalities,
  supported_parameters,
  supports_images,
  capability_profile,
  raw_openrouter,
  synced_at
)
values
  (
    'anthropic',
    'claude-opus-5',
    'Claude Opus 5',
    true,
    true,
    'openrouter_verified',
    1000000,
    128000,
    array['text','image','file'],
    array['text'],
    array['include_reasoning','max_tokens','reasoning','response_format','stop','structured_outputs','tool_choice','tools','verbosity'],
    true,
    '{"reasoning":{"transport":"verbosity","levels":["low","medium","high","xhigh","max"]},"context":{"tiers":[{"tokens":300000,"label":"300K","pricingProfile":"standard"},{"tokens":1000000,"label":"1M","pricingProfile":"standard"}]},"speed":{"available":false}}'::jsonb,
    '{"id":"anthropic/claude-opus-5","canonical_slug":"anthropic/claude-opus-5","name":"Anthropic: Claude Opus 5"}'::jsonb,
    now()
  ),
  (
    'anthropic',
    'claude-sonnet-5',
    'Claude Sonnet 5',
    true,
    true,
    'openrouter_verified',
    1000000,
    128000,
    array['text','image','file'],
    array['text'],
    array['include_reasoning','max_tokens','reasoning','response_format','stop','structured_outputs','tool_choice','tools','verbosity'],
    true,
    '{"reasoning":{"transport":"verbosity","levels":["low","medium","high","xhigh","max"]},"context":{"tiers":[{"tokens":300000,"label":"300K","pricingProfile":"standard"},{"tokens":1000000,"label":"1M","pricingProfile":"standard"}]},"speed":{"available":false}}'::jsonb,
    '{"id":"anthropic/claude-sonnet-5","canonical_slug":"anthropic/claude-sonnet-5","name":"Anthropic: Claude Sonnet 5"}'::jsonb,
    now()
  ),
  (
    'openai',
    'gpt-5.6-sol',
    'GPT-5.6 Sol',
    true,
    true,
    'openrouter_verified',
    1050000,
    128000,
    array['text','image','file'],
    array['text'],
    array['include_reasoning','max_tokens','reasoning','response_format','stop','structured_outputs','tool_choice','tools'],
    true,
    '{"reasoning":{"transport":"reasoning.effort","levels":["none","low","medium","high","xhigh","max"]},"context":{"tiers":[{"tokens":272000,"label":"272K","pricingProfile":"standard"},{"tokens":1050000,"label":"1.05M","pricingProfile":"extended"}]},"speed":{"available":false}}'::jsonb,
    '{"id":"openai/gpt-5.6-sol","canonical_slug":"openai/gpt-5.6-sol","name":"OpenAI: GPT-5.6 Sol"}'::jsonb,
    now()
  ),
  (
    'openai',
    'gpt-5.6-terra',
    'GPT-5.6 Terra',
    true,
    true,
    'openrouter_verified',
    1050000,
    128000,
    array['text','image','file'],
    array['text'],
    array['include_reasoning','max_tokens','reasoning','response_format','stop','structured_outputs','tool_choice','tools'],
    true,
    '{"reasoning":{"transport":"reasoning.effort","levels":["none","low","medium","high","xhigh","max"]},"context":{"tiers":[{"tokens":272000,"label":"272K","pricingProfile":"standard"},{"tokens":1050000,"label":"1.05M","pricingProfile":"extended"}]},"speed":{"available":false}}'::jsonb,
    '{"id":"openai/gpt-5.6-terra","canonical_slug":"openai/gpt-5.6-terra","name":"OpenAI: GPT-5.6 Terra"}'::jsonb,
    now()
  )
on conflict (provider, model_name) do update
set display_name = excluded.display_name,
    is_active = excluded.is_active,
    is_selectable = excluded.is_selectable,
    source = excluded.source,
    context_window_tokens = excluded.context_window_tokens,
    max_output_tokens = excluded.max_output_tokens,
    input_modalities = excluded.input_modalities,
    output_modalities = excluded.output_modalities,
    supported_parameters = excluded.supported_parameters,
    supports_images = excluded.supports_images,
    capability_profile = excluded.capability_profile,
    raw_openrouter = excluded.raw_openrouter,
    synced_at = excluded.synced_at,
    updated_at = now();
