-- Advantage+ Campaign Budget fields on ad_campaigns
ALTER TABLE ad_campaigns
ADD COLUMN IF NOT EXISTS daily_budget INTEGER,
ADD COLUMN IF NOT EXISTS lifetime_budget INTEGER,
ADD COLUMN IF NOT EXISTS bid_strategy TEXT NOT NULL DEFAULT 'LOWEST_COST_WITHOUT_CAP'
  CHECK (bid_strategy IN ('LOWEST_COST_WITHOUT_CAP', 'COST_CAP', 'LOWEST_COST_WITH_BID_CAP', 'LOWEST_COST_WITH_MIN_ROAS'));
