-- =============================================================================
-- Performance advisors phase 1, Migration A: index hygiene
-- =============================================================================
-- 1. Add 162 indexes on unindexed FK columns (faster cascades + JOINs).
-- 2. Drop 4 confirmed-identical duplicate indexes (kept _id-suffixed canonical).
-- 3. Drop 235 unused plain-btree indexes (3+ months prod, idx_scan = 0,
--    none back unique/primary constraints). Preserved 10 specialized indexes
--    (HNSW vector / GIN array / IVFFlat / FTS) — these legitimately show
--    idx_scan=0 on small tables and become essential as data grows.

-- ----------------------------------------------------------------------------- 
-- 1. Cover FK columns with indexes
-- ----------------------------------------------------------------------------- 
CREATE INDEX IF NOT EXISTS idx_ad_campaigns_org_id_fk ON public.ad_campaigns (org_id);
CREATE INDEX IF NOT EXISTS idx_ads_image_asset_id_fk ON public.ads (image_asset_id);
CREATE INDEX IF NOT EXISTS idx_agent_awareness_points_campaign_id_fk ON public.agent_awareness_points (campaign_id);
CREATE INDEX IF NOT EXISTS idx_agent_awareness_points_org_id_fk ON public.agent_awareness_points (org_id);
CREATE INDEX IF NOT EXISTS idx_agent_awareness_sessions_org_id_fk ON public.agent_awareness_sessions (org_id);
CREATE INDEX IF NOT EXISTS idx_agent_checkpoints_summary_edited_by_fk ON public.agent_checkpoints (summary_edited_by);
CREATE INDEX IF NOT EXISTS idx_agent_delegations_message_id_fk ON public.agent_delegations (message_id);
CREATE INDEX IF NOT EXISTS idx_agent_delegations_mission_id_fk ON public.agent_delegations (mission_id);
CREATE INDEX IF NOT EXISTS idx_agent_delegations_org_id_fk ON public.agent_delegations (org_id);
CREATE INDEX IF NOT EXISTS idx_agent_signals_campaign_id_fk ON public.agent_signals (campaign_id);
CREATE INDEX IF NOT EXISTS idx_agent_tasks_campaign_id_fk ON public.agent_tasks (campaign_id);
CREATE INDEX IF NOT EXISTS idx_agent_tasks_conversation_id_fk ON public.agent_tasks (conversation_id);
CREATE INDEX IF NOT EXISTS idx_agent_team_members_added_by_fk ON public.agent_team_members (added_by);
CREATE INDEX IF NOT EXISTS idx_agent_workflows_org_id_fk ON public.agent_workflows (org_id);
CREATE INDEX IF NOT EXISTS idx_agents_registry_created_by_fk ON public.agents_registry (created_by);
CREATE INDEX IF NOT EXISTS idx_api_keys_org_id_fk ON public.api_keys (org_id);
CREATE INDEX IF NOT EXISTS idx_api_keys_user_id_fk ON public.api_keys (user_id);
CREATE INDEX IF NOT EXISTS idx_app_errors_user_id_fk ON public.app_errors (user_id);
CREATE INDEX IF NOT EXISTS idx_audiences_user_id_fk ON public.audiences (user_id);
CREATE INDEX IF NOT EXISTS idx_avatars_offer_id_fk ON public.avatars (offer_id);
CREATE INDEX IF NOT EXISTS idx_avatars_org_id_fk ON public.avatars (org_id);
CREATE INDEX IF NOT EXISTS idx_avatars_user_id_fk ON public.avatars (user_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_org_id_fk ON public.blog_posts (org_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_user_id_fk ON public.blog_posts (user_id);
CREATE INDEX IF NOT EXISTS idx_brain_connections_profile_id_fk ON public.brain_connections (profile_id);
CREATE INDEX IF NOT EXISTS idx_brain_cross_suggestions_target_campaign_id_fk ON public.brain_cross_suggestions (target_campaign_id);
CREATE INDEX IF NOT EXISTS idx_brain_import_jobs_org_id_fk ON public.brain_import_jobs (org_id);
CREATE INDEX IF NOT EXISTS idx_brains_owner_id_fk ON public.brains (owner_id);
CREATE INDEX IF NOT EXISTS idx_branding_themes_org_id_fk ON public.branding_themes (org_id);
CREATE INDEX IF NOT EXISTS idx_broadcast_email_sends_email_send_id_fk ON public.broadcast_email_sends (email_send_id);
CREATE INDEX IF NOT EXISTS idx_broadcast_email_sends_lead_id_fk ON public.broadcast_email_sends (lead_id);
CREATE INDEX IF NOT EXISTS idx_browser_sessions_org_id_fk ON public.browser_sessions (org_id);
CREATE INDEX IF NOT EXISTS idx_campaign_node_sources_node_id_fk ON public.campaign_node_sources (node_id);
CREATE INDEX IF NOT EXISTS idx_campaign_node_sources_user_id_fk ON public.campaign_node_sources (user_id);
CREATE INDEX IF NOT EXISTS idx_campaign_nodes_canonical_node_id_fk ON public.campaign_nodes (canonical_node_id);
CREATE INDEX IF NOT EXISTS idx_campaign_plans_campaign_id_fk ON public.campaign_plans (campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_user_state_campaign_id_fk ON public.campaign_user_state (campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_workflow_edges_user_id_fk ON public.campaign_workflow_edges (user_id);
CREATE INDEX IF NOT EXISTS idx_campaign_workflow_layouts_user_id_fk ON public.campaign_workflow_layouts (user_id);
CREATE INDEX IF NOT EXISTS idx_channel_members_org_id_fk ON public.channel_members (org_id);
CREATE INDEX IF NOT EXISTS idx_channel_memberships_added_by_fk ON public.channel_memberships (added_by);
CREATE INDEX IF NOT EXISTS idx_channel_messages_pinned_by_fk ON public.channel_messages (pinned_by);
CREATE INDEX IF NOT EXISTS idx_channel_messages_reply_to_id_fk ON public.channel_messages (reply_to_id);
CREATE INDEX IF NOT EXISTS idx_contact_activity_user_id_fk ON public.contact_activity (user_id);
CREATE INDEX IF NOT EXISTS idx_contact_campaign_memberships_source_funnel_id_fk ON public.contact_campaign_memberships (source_funnel_id);
CREATE INDEX IF NOT EXISTS idx_contact_custom_field_definitions_org_id_fk ON public.contact_custom_field_definitions (org_id);
CREATE INDEX IF NOT EXISTS idx_contact_notes_user_id_fk ON public.contact_notes (user_id);
CREATE INDEX IF NOT EXISTS idx_conversation_documents_campaign_id_fk ON public.conversation_documents (campaign_id);
CREATE INDEX IF NOT EXISTS idx_conversation_shares_created_by_fk ON public.conversation_shares (created_by);
CREATE INDEX IF NOT EXISTS idx_conversations_campaign_id_fk ON public.conversations (campaign_id);
CREATE INDEX IF NOT EXISTS idx_direct_invite_codes_created_by_fk ON public.direct_invite_codes (created_by);
CREATE INDEX IF NOT EXISTS idx_domains_funnel_id_fk ON public.domains (funnel_id);
CREATE INDEX IF NOT EXISTS idx_email_broadcast_schedules_domain_id_fk ON public.email_broadcast_schedules (domain_id);
CREATE INDEX IF NOT EXISTS idx_email_broadcast_schedules_sender_identity_id_fk ON public.email_broadcast_schedules (sender_identity_id);
CREATE INDEX IF NOT EXISTS idx_email_domains_org_id_fk ON public.email_domains (org_id);
CREATE INDEX IF NOT EXISTS idx_email_sender_identities_org_id_fk ON public.email_sender_identities (org_id);
CREATE INDEX IF NOT EXISTS idx_email_sends_domain_id_fk ON public.email_sends (domain_id);
CREATE INDEX IF NOT EXISTS idx_email_single_schedules_domain_id_fk ON public.email_single_schedules (domain_id);
CREATE INDEX IF NOT EXISTS idx_email_single_schedules_lead_id_fk ON public.email_single_schedules (lead_id);
CREATE INDEX IF NOT EXISTS idx_email_single_schedules_sender_identity_id_fk ON public.email_single_schedules (sender_identity_id);
CREATE INDEX IF NOT EXISTS idx_emails_created_by_fk ON public.emails (created_by);
CREATE INDEX IF NOT EXISTS idx_evaluation_drift_org_id_fk ON public.evaluation_drift (org_id);
CREATE INDEX IF NOT EXISTS idx_fast_track_purchases_invite_code_id_fk ON public.fast_track_purchases (invite_code_id);
CREATE INDEX IF NOT EXISTS idx_fast_track_purchases_redeemed_user_id_fk ON public.fast_track_purchases (redeemed_user_id);
CREATE INDEX IF NOT EXISTS idx_form_responses_space_item_id_fk ON public.form_responses (space_item_id);
CREATE INDEX IF NOT EXISTS idx_form_responses_submitter_user_id_fk ON public.form_responses (submitter_user_id);
CREATE INDEX IF NOT EXISTS idx_forms_user_id_fk ON public.forms (user_id);
CREATE INDEX IF NOT EXISTS idx_funnel_conversion_points_user_id_fk ON public.funnel_conversion_points (user_id);
CREATE INDEX IF NOT EXISTS idx_funnels_domain_id_fk ON public.funnels (domain_id);
CREATE INDEX IF NOT EXISTS idx_funnels_home_page_id_fk ON public.funnels (home_page_id);
CREATE INDEX IF NOT EXISTS idx_funnels_offer_id_fk ON public.funnels (offer_id);
CREATE INDEX IF NOT EXISTS idx_github_repos_org_id_fk ON public.github_repos (org_id);
CREATE INDEX IF NOT EXISTS idx_human_dm_messages_sender_id_fk ON public.human_dm_messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_human_dm_reads_user_id_fk ON public.human_dm_reads (user_id);
CREATE INDEX IF NOT EXISTS idx_leads_user_id_fk ON public.leads (user_id);
CREATE INDEX IF NOT EXISTS idx_machine_pool_claimed_by_fk ON public.machine_pool (claimed_by);
CREATE INDEX IF NOT EXISTS idx_media_generation_jobs_media_asset_id_fk ON public.media_generation_jobs (media_asset_id);
CREATE INDEX IF NOT EXISTS idx_memory_sessions_user_id_fk ON public.memory_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_mission_deliverables_org_id_fk ON public.mission_deliverables (org_id);
CREATE INDEX IF NOT EXISTS idx_mission_outbox_user_id_fk ON public.mission_outbox (user_id);
CREATE INDEX IF NOT EXISTS idx_mission_subtasks_deliverable_id_fk ON public.mission_subtasks (deliverable_id);
CREATE INDEX IF NOT EXISTS idx_missions_plan_id_fk ON public.missions (plan_id);
CREATE INDEX IF NOT EXISTS idx_missions_plans_org_id_fk ON public.missions_plans (org_id);
CREATE INDEX IF NOT EXISTS idx_ns_errors_user_id_fk ON public.ns_errors (user_id);
CREATE INDEX IF NOT EXISTS idx_ns_memories_contact_id_fk ON public.ns_memories (contact_id);
CREATE INDEX IF NOT EXISTS idx_ns_pending_captures_brain_id_fk ON public.ns_pending_captures (brain_id);
CREATE INDEX IF NOT EXISTS idx_ns_sk_evolution_source_id_fk ON public.ns_sk_evolution (source_id);
CREATE INDEX IF NOT EXISTS idx_ns_sk_gaps_filled_by_fk ON public.ns_sk_gaps (filled_by);
CREATE INDEX IF NOT EXISTS idx_offers_user_id_fk ON public.offers (user_id);
CREATE INDEX IF NOT EXISTS idx_org_addons_brain_id_fk ON public.org_addons (brain_id);
CREATE INDEX IF NOT EXISTS idx_org_addons_org_id_fk ON public.org_addons (org_id);
CREATE INDEX IF NOT EXISTS idx_org_brain_sharing_brain_id_fk ON public.org_brain_sharing (brain_id);
CREATE INDEX IF NOT EXISTS idx_org_brain_sharing_shared_by_fk ON public.org_brain_sharing (shared_by);
CREATE INDEX IF NOT EXISTS idx_org_campaign_permissions_granted_by_fk ON public.org_campaign_permissions (granted_by);
CREATE INDEX IF NOT EXISTS idx_org_credit_purchases_org_id_fk ON public.org_credit_purchases (org_id);
CREATE INDEX IF NOT EXISTS idx_org_credit_purchases_purchased_by_fk ON public.org_credit_purchases (purchased_by);
CREATE INDEX IF NOT EXISTS idx_org_invitations_invited_by_fk ON public.org_invitations (invited_by);
CREATE INDEX IF NOT EXISTS idx_org_member_credit_limits_member_id_fk ON public.org_member_credit_limits (member_id);
CREATE INDEX IF NOT EXISTS idx_org_members_invited_by_fk ON public.org_members (invited_by);
CREATE INDEX IF NOT EXISTS idx_org_subscriptions_plan_id_fk ON public.org_subscriptions (plan_id);
CREATE INDEX IF NOT EXISTS idx_platform_email_config_configured_by_fk ON public.platform_email_config (configured_by);
CREATE INDEX IF NOT EXISTS idx_presentations_domain_id_fk ON public.presentations (domain_id);
CREATE INDEX IF NOT EXISTS idx_presentations_offer_id_fk ON public.presentations (offer_id);
CREATE INDEX IF NOT EXISTS idx_presentations_org_id_fk ON public.presentations (org_id);
CREATE INDEX IF NOT EXISTS idx_presentations_theme_id_fk ON public.presentations (theme_id);
CREATE INDEX IF NOT EXISTS idx_presentations_user_id_fk ON public.presentations (user_id);
CREATE INDEX IF NOT EXISTS idx_project_mcp_servers_vault_secret_id_fk ON public.project_mcp_servers (vault_secret_id);
CREATE INDEX IF NOT EXISTS idx_project_repos_conversation_id_fk ON public.project_repos (conversation_id);
CREATE INDEX IF NOT EXISTS idx_project_repos_org_id_fk ON public.project_repos (org_id);
CREATE INDEX IF NOT EXISTS idx_project_repos_theme_id_fk ON public.project_repos (theme_id);
CREATE INDEX IF NOT EXISTS idx_segments_org_id_fk ON public.segments (org_id);
CREATE INDEX IF NOT EXISTS idx_segments_user_id_fk ON public.segments (user_id);
CREATE INDEX IF NOT EXISTS idx_sequence_email_sends_email_send_id_fk ON public.sequence_email_sends (email_send_id);
CREATE INDEX IF NOT EXISTS idx_sequence_email_sends_lead_id_fk ON public.sequence_email_sends (lead_id);
CREATE INDEX IF NOT EXISTS idx_sequence_email_sends_sequence_email_id_fk ON public.sequence_email_sends (sequence_email_id);
CREATE INDEX IF NOT EXISTS idx_sequence_emails_sequence_id_fk ON public.sequence_emails (sequence_id);
CREATE INDEX IF NOT EXISTS idx_sequences_org_id_fk ON public.sequences (org_id);
CREATE INDEX IF NOT EXISTS idx_sequences_user_id_fk ON public.sequences (user_id);
CREATE INDEX IF NOT EXISTS idx_slack_brain_mappings_target_brain_id_fk ON public.slack_brain_mappings (target_brain_id);
CREATE INDEX IF NOT EXISTS idx_slack_brain_mappings_target_campaign_id_fk ON public.slack_brain_mappings (target_campaign_id);
CREATE INDEX IF NOT EXISTS idx_social_posts_image_asset_id_fk ON public.social_posts (image_asset_id);
CREATE INDEX IF NOT EXISTS idx_social_posts_user_id_fk ON public.social_posts (user_id);
CREATE INDEX IF NOT EXISTS idx_social_posts_video_asset_id_fk ON public.social_posts (video_asset_id);
CREATE INDEX IF NOT EXISTS idx_space_automation_run_state_space_id_fk ON public.space_automation_run_state (space_id);
CREATE INDEX IF NOT EXISTS idx_space_automation_run_state_user_id_fk ON public.space_automation_run_state (user_id);
CREATE INDEX IF NOT EXISTS idx_space_automation_runs_linked_mission_id_fk ON public.space_automation_runs (linked_mission_id);
CREATE INDEX IF NOT EXISTS idx_space_automation_runs_user_id_fk ON public.space_automation_runs (user_id);
CREATE INDEX IF NOT EXISTS idx_space_drive_folder_mappings_root_space_item_id_fk ON public.space_drive_folder_mappings (root_space_item_id);
CREATE INDEX IF NOT EXISTS idx_space_drive_push_channels_space_id_fk ON public.space_drive_push_channels (space_id);
CREATE INDEX IF NOT EXISTS idx_space_drive_push_channels_user_id_fk ON public.space_drive_push_channels (user_id);
CREATE INDEX IF NOT EXISTS idx_space_external_automation_events_external_trigger_id_fk ON public.space_external_automation_events (external_trigger_id);
CREATE INDEX IF NOT EXISTS idx_space_external_automation_events_item_id_fk ON public.space_external_automation_events (item_id);
CREATE INDEX IF NOT EXISTS idx_space_external_automation_events_user_id_fk ON public.space_external_automation_events (user_id);
CREATE INDEX IF NOT EXISTS idx_space_external_automation_triggers_created_by_fk ON public.space_external_automation_triggers (created_by);
CREATE INDEX IF NOT EXISTS idx_space_external_automation_triggers_user_id_fk ON public.space_external_automation_triggers (user_id);
CREATE INDEX IF NOT EXISTS idx_space_item_activity_user_id_fk ON public.space_item_activity (user_id);
CREATE INDEX IF NOT EXISTS idx_space_item_deliverables_user_id_fk ON public.space_item_deliverables (user_id);
CREATE INDEX IF NOT EXISTS idx_space_item_shares_created_by_fk ON public.space_item_shares (created_by);
CREATE INDEX IF NOT EXISTS idx_space_items_user_id_fk ON public.space_items (user_id);
CREATE INDEX IF NOT EXISTS idx_space_shares_created_by_fk ON public.space_shares (created_by);
CREATE INDEX IF NOT EXISTS idx_space_view_overrides_user_id_fk ON public.space_view_overrides (user_id);
CREATE INDEX IF NOT EXISTS idx_space_view_shares_created_by_fk ON public.space_view_shares (created_by);
CREATE INDEX IF NOT EXISTS idx_team_brain_permissions_granted_by_fk ON public.team_brain_permissions (granted_by);
CREATE INDEX IF NOT EXISTS idx_team_campaign_permissions_granted_by_fk ON public.team_campaign_permissions (granted_by);
CREATE INDEX IF NOT EXISTS idx_team_invitations_invited_by_fk ON public.team_invitations (invited_by);
CREATE INDEX IF NOT EXISTS idx_team_member_credit_log_campaign_id_fk ON public.team_member_credit_log (campaign_id);
CREATE INDEX IF NOT EXISTS idx_template_skill_assignments_skill_key_fk ON public.template_skill_assignments (skill_key);
CREATE INDEX IF NOT EXISTS idx_user_addons_brain_id_fk ON public.user_addons (brain_id);
CREATE INDEX IF NOT EXISTS idx_user_agent_state_org_id_fk ON public.user_agent_state (org_id);
CREATE INDEX IF NOT EXISTS idx_user_integrations_integration_id_fk ON public.user_integrations (integration_id);
CREATE INDEX IF NOT EXISTS idx_user_notifications_mission_id_fk ON public.user_notifications (mission_id);
CREATE INDEX IF NOT EXISTS idx_user_notifications_org_id_fk ON public.user_notifications (org_id);
CREATE INDEX IF NOT EXISTS idx_user_object_records_object_type_id_fk ON public.user_object_records (object_type_id);
CREATE INDEX IF NOT EXISTS idx_user_object_records_org_id_fk ON public.user_object_records (org_id);
CREATE INDEX IF NOT EXISTS idx_user_object_types_org_id_fk ON public.user_object_types (org_id);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_plan_id_fk ON public.user_subscriptions (plan_id);
CREATE INDEX IF NOT EXISTS idx_user_workspaces_org_id_fk ON public.user_workspaces (org_id);
CREATE INDEX IF NOT EXISTS idx_vault_secrets_org_id_fk ON public.vault_secrets (org_id);
CREATE INDEX IF NOT EXISTS idx_vb_agent_traces_org_id_fk ON public.vb_agent_traces (org_id);
CREATE INDEX IF NOT EXISTS idx_vb_message_timeline_events_user_id_fk ON public.vb_message_timeline_events (user_id);
CREATE INDEX IF NOT EXISTS idx_visitors_page_views_funnel_page_id_fk ON public.visitors_page_views (funnel_page_id);
CREATE INDEX IF NOT EXISTS idx_waitlist_invites_sent_by_fk ON public.waitlist_invites (sent_by);

-- ----------------------------------------------------------------------------- 
-- 2. Drop 4 duplicate indexes (kept _id-suffixed canonical name in each pair)
-- ----------------------------------------------------------------------------- 
DROP INDEX IF EXISTS public.idx_agents_registry_org_unique;
DROP INDEX IF EXISTS public.idx_campaign_agents_campaign;
DROP INDEX IF EXISTS public.idx_campaigns_user;
DROP INDEX IF EXISTS public.idx_missions_campaign;

-- ----------------------------------------------------------------------------- 
-- 3. Drop 235 unused plain-btree indexes
-- ----------------------------------------------------------------------------- 
DROP INDEX IF EXISTS public.idx_ad_campaigns_created_at;
DROP INDEX IF EXISTS public.idx_ad_campaigns_meta_ad_account;
DROP INDEX IF EXISTS public.idx_ad_campaigns_meta_campaign_id;
DROP INDEX IF EXISTS public.idx_ad_campaigns_source;
DROP INDEX IF EXISTS public.idx_ad_campaigns_user_id;
DROP INDEX IF EXISTS public.idx_ad_sets_created_at;
DROP INDEX IF EXISTS public.idx_ad_sets_meta_adset_id;
DROP INDEX IF EXISTS public.idx_ad_sets_org;
DROP INDEX IF EXISTS public.idx_ad_sets_source;
DROP INDEX IF EXISTS public.idx_ad_sets_user_id;
DROP INDEX IF EXISTS public.idx_ads_created_at;
DROP INDEX IF EXISTS public.idx_ads_meta_ad_id;
DROP INDEX IF EXISTS public.idx_ads_source;
DROP INDEX IF EXISTS public.idx_ads_theme_id;
DROP INDEX IF EXISTS public.idx_awareness_points_session_id;
DROP INDEX IF EXISTS public.idx_awareness_sessions_user_id;
DROP INDEX IF EXISTS public.idx_agent_delegations_caller_status_updated;
DROP INDEX IF EXISTS public.idx_agent_delegations_target_status_updated;
DROP INDEX IF EXISTS public.idx_agent_delegations_user;
DROP INDEX IF EXISTS public.idx_agent_signals_org;
DROP INDEX IF EXISTS public.idx_agent_teams_parent;
DROP INDEX IF EXISTS public.idx_agent_workflows_user_agent;
DROP INDEX IF EXISTS public.idx_agents_registry_is_active;
DROP INDEX IF EXISTS public.idx_api_usage_created;
DROP INDEX IF EXISTS public.idx_api_usage_user;
DROP INDEX IF EXISTS public.idx_app_errors_app;
DROP INDEX IF EXISTS public.idx_avatar_discriminator_axes_org_status;
DROP INDEX IF EXISTS public.idx_billing_health_log_unresolved;
DROP INDEX IF EXISTS public.idx_blog_posts_funnel;
DROP INDEX IF EXISTS public.idx_brain_bp_status;
DROP INDEX IF EXISTS public.idx_brain_bp_strength;
DROP INDEX IF EXISTS public.idx_brain_bp_subject;
DROP INDEX IF EXISTS public.idx_brain_cross_suggestions_user_pending;
DROP INDEX IF EXISTS public.idx_brain_er_created;
DROP INDEX IF EXISTS public.idx_brain_er_emotion;
DROP INDEX IF EXISTS public.idx_brain_er_memory;
DROP INDEX IF EXISTS public.idx_brain_er_subject;
DROP INDEX IF EXISTS public.idx_brain_persp_status;
DROP INDEX IF EXISTS public.idx_brain_persp_subject;
DROP INDEX IF EXISTS public.idx_broadcast_email_sends_org;
DROP INDEX IF EXISTS public.idx_broadcast_email_sends_schedule;
DROP INDEX IF EXISTS public.idx_campaign_edges_from_node;
DROP INDEX IF EXISTS public.idx_campaign_edges_to_node;
DROP INDEX IF EXISTS public.idx_campaign_edges_type;
DROP INDEX IF EXISTS public.idx_campaign_edges_user_id;
DROP INDEX IF EXISTS public.idx_campaign_nodes_campaign_node_type_created;
DROP INDEX IF EXISTS public.idx_campaign_nodes_created_at;
DROP INDEX IF EXISTS public.idx_campaign_nodes_domain;
DROP INDEX IF EXISTS public.idx_campaign_nodes_source;
DROP INDEX IF EXISTS public.idx_campaign_nodes_type;
DROP INDEX IF EXISTS public.idx_campaign_strategy_nodes_user_id;
DROP INDEX IF EXISTS public.idx_campaign_tasks_status;
DROP INDEX IF EXISTS public.campaign_user_state_user_favorite_idx;
DROP INDEX IF EXISTS public.campaign_user_state_user_hidden_idx;
DROP INDEX IF EXISTS public.idx_campaign_workflow_edges_from;
DROP INDEX IF EXISTS public.idx_campaign_workflow_edges_to;
DROP INDEX IF EXISTS public.idx_campaigns_user_status_active_work;
DROP INDEX IF EXISTS public.idx_channel_messages_pinned;
DROP INDEX IF EXISTS public.idx_channels_name_lower;
DROP INDEX IF EXISTS public.idx_contact_campaign_memberships_offer;
DROP INDEX IF EXISTS public.idx_contact_identifiers_contact;
DROP INDEX IF EXISTS public.idx_contact_notes_org_id;
DROP INDEX IF EXISTS public.idx_contacts_email;
DROP INDEX IF EXISTS public.idx_contacts_user;
DROP INDEX IF EXISTS public.idx_conversation_documents_org;
DROP INDEX IF EXISTS public.idx_conversation_shares_org_id;
DROP INDEX IF EXISTS public.idx_credit_purchases_user_id;
DROP INDEX IF EXISTS public.idx_crm_sync_jobs_user_created;
DROP INDEX IF EXISTS public.idx_customer_avatars_brain;
DROP INDEX IF EXISTS public.idx_customer_avatars_declared;
DROP INDEX IF EXISTS public.idx_customer_avatars_status;
DROP INDEX IF EXISTS public.idx_direct_invite_codes_active;
DROP INDEX IF EXISTS public.idx_domains_domain_name;
DROP INDEX IF EXISTS public.idx_domains_domain_type;
DROP INDEX IF EXISTS public.idx_domains_cache_cached_at;
DROP INDEX IF EXISTS public.idx_domains_cache_user_id;
DROP INDEX IF EXISTS public.idx_email_broadcast_schedules_org;
DROP INDEX IF EXISTS public.idx_email_broadcast_schedules_status;
DROP INDEX IF EXISTS public.idx_email_broadcast_schedules_user_id;
DROP INDEX IF EXISTS public.idx_email_dns_provider_connections_user_id;
DROP INDEX IF EXISTS public.idx_email_domains_status;
DROP INDEX IF EXISTS public.idx_email_domains_user_id;
DROP INDEX IF EXISTS public.idx_email_events_sg_event_id;
DROP INDEX IF EXISTS public.idx_email_pending_sends_org;
DROP INDEX IF EXISTS public.idx_email_pending_sends_status;
DROP INDEX IF EXISTS public.idx_email_pending_sends_user_status;
DROP INDEX IF EXISTS public.idx_email_sender_identities_domain_id;
DROP INDEX IF EXISTS public.idx_email_sends_lead_id;
DROP INDEX IF EXISTS public.idx_email_sends_org;
DROP INDEX IF EXISTS public.idx_email_sends_sg_msg_id;
DROP INDEX IF EXISTS public.idx_email_sends_status;
DROP INDEX IF EXISTS public.idx_email_sends_user_id;
DROP INDEX IF EXISTS public.idx_email_single_schedules_user_id;
DROP INDEX IF EXISTS public.idx_email_suppressions_org;
DROP INDEX IF EXISTS public.idx_email_suppressions_user_email;
DROP INDEX IF EXISTS public.idx_emails_created_at;
DROP INDEX IF EXISTS public.idx_emails_org;
DROP INDEX IF EXISTS public.idx_emails_space;
DROP INDEX IF EXISTS public.idx_emails_user;
DROP INDEX IF EXISTS public.idx_enterprise_applications_created;
DROP INDEX IF EXISTS public.idx_enterprise_applications_status;
DROP INDEX IF EXISTS public.idx_enterprise_applications_user;
DROP INDEX IF EXISTS public.idx_eval_drift_drift_magnitude;
DROP INDEX IF EXISTS public.idx_eval_drift_user_id;
DROP INDEX IF EXISTS public.idx_fast_track_purchases_email;
DROP INDEX IF EXISTS public.idx_fast_track_purchases_session;
DROP INDEX IF EXISTS public.idx_form_responses_org;
DROP INDEX IF EXISTS public.idx_forms_copied_from;
DROP INDEX IF EXISTS public.idx_forms_space;
DROP INDEX IF EXISTS public.idx_forms_space_status;
DROP INDEX IF EXISTS public.idx_funnel_block_assets_block_id;
DROP INDEX IF EXISTS public.idx_funnel_blocks_created_by;
DROP INDEX IF EXISTS public.idx_funnel_blocks_org_id;
DROP INDEX IF EXISTS public.idx_funnel_pages_org;
DROP INDEX IF EXISTS public.idx_funnels_theme_id;
DROP INDEX IF EXISTS public.idx_github_repos_installation_id;
DROP INDEX IF EXISTS public.idx_human_dm_conv_user_high;
DROP INDEX IF EXISTS public.idx_human_dm_conv_user_low;
DROP INDEX IF EXISTS public.idx_leads_ad_campaign_id;
DROP INDEX IF EXISTS public.idx_leads_ad_id;
DROP INDEX IF EXISTS public.idx_leads_ad_set_id;
DROP INDEX IF EXISTS public.idx_machine_pool_provisioning;
DROP INDEX IF EXISTS public.idx_media_assets_asset_type;
DROP INDEX IF EXISTS public.idx_media_generation_jobs_status;
DROP INDEX IF EXISTS public.idx_memories_content_hash;
DROP INDEX IF EXISTS public.idx_memories_created_at;
DROP INDEX IF EXISTS public.idx_memories_emotional_intensity;
DROP INDEX IF EXISTS public.idx_memories_memory_type;
DROP INDEX IF EXISTS public.idx_memories_significance;
DROP INDEX IF EXISTS public.idx_memories_source_emotion;
DROP INDEX IF EXISTS public.idx_memories_source_type;
DROP INDEX IF EXISTS public.idx_mc_source;
DROP INDEX IF EXISTS public.idx_mc_target;
DROP INDEX IF EXISTS public.idx_mv_memory_id;
DROP INDEX IF EXISTS public.idx_mission_deliverables_entity;
DROP INDEX IF EXISTS public.idx_mission_deliverables_generation_job_id;
DROP INDEX IF EXISTS public.idx_mission_deliverables_source_action;
DROP INDEX IF EXISTS public.idx_mission_deliverables_user;
DROP INDEX IF EXISTS public.idx_missions_completed_at;
DROP INDEX IF EXISTS public.idx_missions_scheduled;
DROP INDEX IF EXISTS public.idx_missions_logs_correlation;
DROP INDEX IF EXISTS public.idx_ns_created_at;
DROP INDEX IF EXISTS public.idx_ns_type;
DROP INDEX IF EXISTS public.idx_ns_user_id;
DROP INDEX IF EXISTS public.idx_ns_api_usage_created;
DROP INDEX IF EXISTS public.idx_ns_api_usage_profile;
DROP INDEX IF EXISTS public.idx_ns_connections_profile;
DROP INDEX IF EXISTS public.idx_ns_er_created;
DROP INDEX IF EXISTS public.idx_ns_er_memory;
DROP INDEX IF EXISTS public.idx_ns_er_subject;
DROP INDEX IF EXISTS public.idx_ns_errors_created;
DROP INDEX IF EXISTS public.idx_ns_errors_feature;
DROP INDEX IF EXISTS public.idx_ns_jobs_profile;
DROP INDEX IF EXISTS public.idx_ns_meeting_imports_connection;
DROP INDEX IF EXISTS public.idx_ns_memories_brain_contact;
DROP INDEX IF EXISTS public.idx_ns_memories_surprise;
DROP INDEX IF EXISTS public.idx_ns_mv_memory;
DROP INDEX IF EXISTS public.idx_ns_np_status;
DROP INDEX IF EXISTS public.idx_pending_profile_status;
DROP INDEX IF EXISTS public.idx_ns_sk_curriculum_domain;
DROP INDEX IF EXISTS public.idx_ns_sk_entries_domain;
DROP INDEX IF EXISTS public.idx_ns_sk_evolution_created;
DROP INDEX IF EXISTS public.idx_ns_sk_evolution_type;
DROP INDEX IF EXISTS public.idx_ns_sk_gaps_domain;
DROP INDEX IF EXISTS public.idx_ns_sk_gaps_status;
DROP INDEX IF EXISTS public.idx_ns_sk_sources_domain;
DROP INDEX IF EXISTS public.idx_ns_sk_sources_status;
DROP INDEX IF EXISTS public.idx_ns_sk_sources_type;
DROP INDEX IF EXISTS public.idx_ns_edges_type;
DROP INDEX IF EXISTS public.idx_ns_snapshots_agent_id;
DROP INDEX IF EXISTS public.idx_ns_usage_created;
DROP INDEX IF EXISTS public.idx_ns_usage_profile;
DROP INDEX IF EXISTS public.idx_ns_usage_profile_month;
DROP INDEX IF EXISTS public.idx_org_invitations_email;
DROP INDEX IF EXISTS public.idx_org_members_org;
DROP INDEX IF EXISTS public.idx_org_shared_skills_owner;
DROP INDEX IF EXISTS public.idx_project_repos_publish_status;
DROP INDEX IF EXISTS public.idx_project_repos_slug;
DROP INDEX IF EXISTS public.idx_project_repos_vercel_project;
DROP INDEX IF EXISTS public.idx_project_repos_workspace;
DROP INDEX IF EXISTS public.idx_promo_codes_code;
DROP INDEX IF EXISTS public.idx_promo_redemptions_code;
DROP INDEX IF EXISTS public.idx_sequence_email_sends_org;
DROP INDEX IF EXISTS public.idx_sequence_email_sends_user_id;
DROP INDEX IF EXISTS public.idx_sequence_emails_org;
DROP INDEX IF EXISTS public.idx_slack_brain_mappings_due;
DROP INDEX IF EXISTS public.idx_slack_brain_mappings_org_created;
DROP INDEX IF EXISTS public.idx_slack_brain_mappings_user_created;
DROP INDEX IF EXISTS public.idx_snapshots_brain;
DROP INDEX IF EXISTS public.idx_snapshots_type;
DROP INDEX IF EXISTS public.social_post_insights_campaign_idx;
DROP INDEX IF EXISTS public.social_post_insights_fetched_at_idx;
DROP INDEX IF EXISTS public.social_post_insights_org_idx;
DROP INDEX IF EXISTS public.social_post_insights_platform_idx;
DROP INDEX IF EXISTS public.social_post_insights_user_idx;
DROP INDEX IF EXISTS public.idx_spt_platform_category;
DROP INDEX IF EXISTS public.space_automations_org_id_idx;
DROP INDEX IF EXISTS public.space_automations_schedule_due_idx;
DROP INDEX IF EXISTS public.space_automations_space_id_idx;
DROP INDEX IF EXISTS public.idx_space_drive_folder_mappings_mapping_lookup;
DROP INDEX IF EXISTS public.idx_space_external_automation_events_status;
DROP INDEX IF EXISTS public.idx_space_external_automation_events_trigger;
DROP INDEX IF EXISTS public.idx_space_item_shares_invited_email;
DROP INDEX IF EXISTS public.idx_space_items_agent_execution;
DROP INDEX IF EXISTS public.idx_space_items_form_id;
DROP INDEX IF EXISTS public.idx_space_view_shares_org_id;
DROP INDEX IF EXISTS public.idx_space_view_shares_space_id;
DROP INDEX IF EXISTS public.idx_team_brain_perms_member;
DROP INDEX IF EXISTS public.idx_team_invitations_email_status;
DROP INDEX IF EXISTS public.idx_team_invitations_owner_id;
DROP INDEX IF EXISTS public.idx_team_invitations_token_pending;
DROP INDEX IF EXISTS public.idx_team_credit_limits_member;
DROP INDEX IF EXISTS public.idx_team_credit_log_member_created;
DROP INDEX IF EXISTS public.idx_team_credit_log_owner_created;
DROP INDEX IF EXISTS public.idx_team_members_last_active;
DROP INDEX IF EXISTS public.idx_team_members_owner_id;
DROP INDEX IF EXISTS public.idx_themes_org;
DROP INDEX IF EXISTS public.idx_user_addons_agent;
DROP INDEX IF EXISTS public.idx_user_addons_org;
DROP INDEX IF EXISTS public.idx_user_addons_user;
DROP INDEX IF EXISTS public.idx_user_credit_auto_recharge_enabled;
DROP INDEX IF EXISTS public.idx_user_object_records_campaign;
DROP INDEX IF EXISTS public.idx_user_object_records_user_type_updated;
DROP INDEX IF EXISTS public.idx_user_subscriptions_stripe_cust;
DROP INDEX IF EXISTS public.idx_user_widget_folders_org;
DROP INDEX IF EXISTS public.idx_user_widget_folders_user;
DROP INDEX IF EXISTS public.idx_user_widgets_definition_v2;
DROP INDEX IF EXISTS public.idx_user_widgets_folder;
DROP INDEX IF EXISTS public.idx_user_widgets_folder_id;
DROP INDEX IF EXISTS public.idx_vault_secrets_provider;
DROP INDEX IF EXISTS public.idx_vault_secrets_user_id;
DROP INDEX IF EXISTS public.visitors_page_views_visitor_hash_idx;
DROP INDEX IF EXISTS public.idx_waitlist_entries_created;
DROP INDEX IF EXISTS public.idx_waitlist_entries_status;
DROP INDEX IF EXISTS public.idx_waitlist_invites_code_hash;
