export const ARTIFACT_TYPE_TABLES: Record<string, string> = {
  presentation: 'presentations',
  presentation_file: 'presentation_files',
  presentation_asset: 'presentation_assets',
  funnel: 'funnels',
  website: 'funnels',
  funnel_page: 'funnel_pages',
  website_page: 'funnel_pages',
  form: 'forms',
  media: 'media_assets',
  media_asset: 'media_assets',
  image: 'media_assets',
  video: 'media_assets',
  document: 'conversation_documents',
  pdf: 'conversation_documents',
  docx: 'conversation_documents',
  space_item: 'space_items',
  task: 'space_items',
  social_post: 'social_posts',
  blog_post: 'blog_posts',
  mission: 'missions',
  agent_skill: 'agent_skills',
  skill_resource: 'agent_skill_resources',
}

export const ID_FIELD_TABLES: Record<string, string> = {
  presentation_id: 'presentations',
  presentation_file_id: 'presentation_files',
  presentation_asset_id: 'presentation_assets',
  funnel_id: 'funnels',
  website_id: 'funnels',
  funnel_page_id: 'funnel_pages',
  website_page_id: 'funnel_pages',
  form_id: 'forms',
  media_asset_id: 'media_assets',
  mediaAssetId: 'media_assets',
  document_id: 'conversation_documents',
  space_item_id: 'space_items',
  spaceItemId: 'space_items',
  task_id: 'space_items',
  social_post_id: 'social_posts',
  blog_post_id: 'blog_posts',
  mission_id: 'missions',
  agent_skill_id: 'agent_skills',
  skill_id: 'agent_skills',
  skill_resource_id: 'agent_skill_resources',
  memory_id: 'ns_memories',
  memoryId: 'ns_memories',
  company_signal_id: 'company_cortex_signals',
  company_object_id: 'company_cortex_objects',
}

export const ACTION_RESULT_ID_TABLES: Record<string, string> = {
  create_presentation: 'presentations',
  update_presentation: 'presentations',
  patch_presentation: 'presentations',
  create_funnel: 'funnels',
  create_website: 'funnels',
  set_website_layout: 'funnels',
  create_form: 'forms',
  update_form: 'forms',
  publish_form: 'forms',
  unpublish_form: 'forms',
  save_document: 'conversation_documents',
  create_pdf: 'conversation_documents',
  create_docx: 'conversation_documents',
  update_document: 'conversation_documents',
  create_social_post: 'social_posts',
  update_social_post: 'social_posts',
  schedule_social_post: 'social_posts',
  publish_social_post: 'social_posts',
  create_blog_post: 'blog_posts',
  update_blog_post: 'blog_posts',
  create_mission: 'missions',
  update_mission: 'missions',
  create_agent_skill: 'agent_skills',
  update_agent_skill: 'agent_skills',
  create_agent_skill_resource: 'agent_skill_resources',
  update_agent_skill_resource: 'agent_skill_resources',
  copy_skill_resource: 'agent_skill_resources',
  upload_skill_asset: 'agent_skill_resources',
}

export const ACTION_RESULT_OBJECT_ID_TABLES: Record<string, Record<string, string>> = {
  log_brain_event: { entry: 'ns_brain_log' },
  create_brain_belief_pattern: { pattern: 'ns_belief_patterns' },
  update_brain_belief_pattern: { pattern: 'ns_belief_patterns' },
}
