import type { ActionParamType, ActionSchema } from './artifact-action-schemas'

const strings = (keys: string[]): Partial<Record<string, ActionParamType>> =>
  Object.fromEntries(keys.map((key) => [key, 'string'])) as Partial<Record<string, ActionParamType>>
const schema = (
  required: Array<string | string[]> = [],
  optional: string[] = [],
  types: Partial<Record<string, ActionParamType>> = {},
): ActionSchema => ({ required, optional, types })

export const PROMPTMODE_META_ACTION_SCHEMAS: Record<string, ActionSchema> = {
  create_ad: schema(
    [],
    [
      'ad_set_id',
      'adSetId',
      'campaign_id',
      'campaignId',
      'headline',
      'primary_text',
      'description',
      'image_url',
      'image_asset_id',
      'generated_tsx',
      'destination_url',
    ],
    strings(['ad_id', 'adId', 'ad_set_id', 'adSetId', 'campaign_id', 'campaignId']),
  ),
  list_ads: schema(
    [],
    ['ad_id', 'adId', 'ad_set_id', 'adSetId', 'campaign_id', 'campaignId', 'limit', 'offset'],
    {
      ...strings(['ad_id', 'adId', 'ad_set_id', 'adSetId', 'campaign_id', 'campaignId']),
      limit: 'number',
      offset: 'number',
    },
  ),
  create_ad_campaign: schema(
    [],
    [
      'name',
      'objective',
      'budget_type',
      'daily_budget',
      'lifetime_budget',
      'campaign_id',
      'campaignId',
      'space_id',
      'scope_override',
    ],
    {
      ...strings([
        'name',
        'objective',
        'budget_type',
        'campaign_id',
        'campaignId',
        'space_id',
        'scope_override',
      ]),
      daily_budget: 'number',
      lifetime_budget: 'number',
    },
  ),
  create_ad_set: schema(
    [['ad_campaign_id', 'adCampaignId']],
    [
      'ad_campaign_id',
      'adCampaignId',
      'name',
      'daily_budget',
      'lifetime_budget',
      'optimization_goal',
      'billing_event',
      'targeting',
      'campaign_id',
      'campaignId',
      'space_id',
      'scope_override',
    ],
    {
      ...strings([
        'ad_campaign_id',
        'adCampaignId',
        'name',
        'optimization_goal',
        'billing_event',
        'campaign_id',
        'campaignId',
        'space_id',
        'scope_override',
      ]),
      daily_budget: 'number',
      lifetime_budget: 'number',
      targeting: 'object',
    },
  ),
  get_ad_campaign: schema(
    [['ad_campaign_id', 'adCampaignId']],
    ['ad_campaign_id', 'adCampaignId'],
    strings(['ad_campaign_id', 'adCampaignId']),
  ),
  get_ad_set: schema(
    [['ad_set_id', 'adSetId']],
    ['ad_set_id', 'adSetId'],
    strings(['ad_set_id', 'adSetId']),
  ),
  update_ad_campaign: schema(
    [['ad_campaign_id', 'adCampaignId']],
    ['ad_campaign_id', 'adCampaignId', 'name', 'objective', 'status'],
    strings(['ad_campaign_id', 'adCampaignId', 'name', 'objective', 'status']),
  ),
  update_ad_set: schema(
    [['ad_set_id', 'adSetId']],
    ['ad_set_id', 'adSetId', 'name', 'status', 'budget', 'targeting'],
    {
      ...strings(['ad_set_id', 'adSetId', 'name', 'status']),
      budget: 'number',
      targeting: 'object',
    },
  ),
  check_meta_connection: schema(),
  list_meta_ad_accounts: schema(),
  list_meta_pages: schema(),
  publish_ad_to_meta: schema(
    [['ad_id', 'campaign_id']],
    [
      'ad_id',
      'campaign_id',
      'ad_account_id',
      'page_id',
      'instagram_user_id',
      'campaign_name',
      'campaign_objective',
      'adset_name',
      'daily_budget',
      'lifetime_budget',
      'budget_type',
      'bid_strategy',
      'targeting',
      'pixel_id',
      'custom_event_type',
      'start_time',
      'end_time',
    ],
    {
      ...strings([
        'ad_id',
        'campaign_id',
        'ad_account_id',
        'page_id',
        'instagram_user_id',
        'campaign_name',
        'campaign_objective',
        'adset_name',
        'budget_type',
        'bid_strategy',
        'pixel_id',
        'custom_event_type',
        'start_time',
        'end_time',
      ]),
      daily_budget: 'number',
      lifetime_budget: 'number',
      targeting: 'object',
    },
  ),
  save_meta_defaults: schema(
    [['campaign_id', 'ad_campaign_id', 'adCampaignId']],
    [
      'campaign_id',
      'ad_campaign_id',
      'adCampaignId',
      'ad_account_id',
      'page_id',
      'instagram_user_id',
      'pixel_id',
    ],
    strings([
      'campaign_id',
      'ad_campaign_id',
      'adCampaignId',
      'ad_account_id',
      'page_id',
      'instagram_user_id',
      'pixel_id',
    ]),
  ),
  get_meta_ad_status: schema(['meta_ad_id'], ['meta_ad_id'], strings(['meta_ad_id'])),
  get_meta_ads_insights: schema(
    [['campaign_id', 'campaignId']],
    [
      'campaign_id',
      'campaignId',
      'level',
      'ad_campaign_id',
      'adCampaignId',
      'ad_set_id',
      'adSetId',
      'start_date',
      'startDate',
      'end_date',
      'endDate',
      'date_preset',
      'datePreset',
    ],
    strings([
      'campaign_id',
      'campaignId',
      'level',
      'ad_campaign_id',
      'adCampaignId',
      'ad_set_id',
      'adSetId',
      'start_date',
      'startDate',
      'end_date',
      'endDate',
      'date_preset',
      'datePreset',
    ]),
  ),
  get_delivery_estimate: schema([], ['ad_account_id', 'targeting', 'optimization_goal'], {
    ad_account_id: 'string',
    targeting: 'object',
    optimization_goal: 'string',
  }),
  list_meta_audiences: schema([], ['ad_account_id'], strings(['ad_account_id'])),
  create_meta_custom_audience: schema(
    ['name'],
    ['name', 'description', 'ad_account_id'],
    strings(['name', 'description', 'ad_account_id']),
  ),
  create_meta_lookalike_audience: schema(
    ['source_audience_id'],
    ['source_audience_id', 'name', 'country'],
    strings(['source_audience_id', 'name', 'country']),
  ),
  list_meta_pixel_events: schema([], ['pixel_id'], strings(['pixel_id'])),
  create_meta_pixel_event: schema(['event_name'], ['event_name', 'pixel_id', 'payload'], {
    event_name: 'string',
    pixel_id: 'string',
    payload: 'object',
  }),
}
