import { describe, expect, it, vi } from 'vitest'
import { ArtifactDocxService } from './artifact-docx.service'
import { ArtifactPdfService } from './artifact-pdf.service'

const USER_ID = 'user-1'
const CONVERSATION_ID = '11111111-1111-1111-1111-111111111111'
const MISSION_ID = '22222222-2222-2222-2222-222222222222'
const SUBTASK_ID = '33333333-3333-3333-3333-333333333333'

function makeConversationClient(inserted: Array<Record<string, unknown>>) {
  return {
    from: vi.fn((table: string) => {
      if (table === 'conversations') {
        const chain: any = {
          select: vi.fn(() => chain),
          eq: vi.fn(() => chain),
          maybeSingle: vi.fn(async () => ({ data: { id: CONVERSATION_ID }, error: null })),
        }
        return chain
      }
      if (table === 'conversation_documents') {
        const chain: any = {
          insert: vi.fn((payload: Record<string, unknown>) => {
            inserted.push(payload)
            return chain
          }),
          select: vi.fn(() => chain),
          single: vi.fn(async () => ({
            data: {
          id: `doc-${inserted.length}`,
          ...inserted[inserted.length - 1],
        },
            error: null,
          })),
        }
        return chain
      }
      if (table === 'spaces') {
        const chain: any = {
          select: vi.fn(() => chain),
          eq: vi.fn(() => chain),
          order: vi.fn(() => chain),
          limit: vi.fn(async () => ({ data: [], error: null })),
        }
        return chain
      }
      return {}
    }),
  }
}

function makeStorageClient(uploaded: Array<Record<string, unknown>>) {
  const bucket = {
    upload: vi.fn(async (path: string, bytes: Buffer, options: Record<string, unknown>) => {
      uploaded.push({ path, bytes, options })
      return { error: null }
    }),
    createSignedUrl: vi.fn(async (path: string) => ({
      data: { signedUrl: `https://cdn.example/${path}` },
      error: null,
    })),
  }
  return {
    storage: {
      from: vi.fn((bucketName: string) => {
        expect(bucketName).toBe('media')
        return bucket
      }),
    },
  }
}

function makeDocumentTarget(input: {
  supabase: Record<string, unknown>
  serviceClient: Record<string, unknown>
}) {
  return {
    generateDocxBytes: vi.fn(async () => new Uint8Array([1, 2, 3])),
    generateStyledPdfBytes: vi.fn(async () => new Uint8Array([4, 5, 6])),
    getUserClient: vi.fn(async () => input.supabase),
    isMissionSessionKey: vi.fn(() => false),
    logger: { warn: vi.fn(), log: vi.fn() },
    parseConversationId: vi.fn(() => CONVERSATION_ID),
    resolveCampaignId: vi.fn(async () => 'campaign-1'),
    resolveUserId: vi.fn(() => USER_ID),
    serviceClient: input.serviceClient,
  }
}

describe('artifact document file services', () => {
  it('creates a DOCX conversation document after uploading generated bytes', async () => {
    const inserted: Array<Record<string, unknown>> = []
    const uploaded: Array<Record<string, unknown>> = []
    const supabase = makeConversationClient(inserted)
    const target = makeDocumentTarget({
      supabase,
      serviceClient: makeStorageClient(uploaded),
    })
    const handler = new ArtifactDocxService().getHandlers(target).create_docx

    const result = await handler(
      {
        title: ' Launch Plan ',
        content: '<h1>Launch</h1><p>Ship it</p>',
        content_format: 'markdown',
        document_type: 'brief',
      },
      'agent:vibey:session',
    )

    expect(result).toMatchObject({
      asset_ref: {
        kind: 'storage_asset',
        bucket_name: 'media',
        file_path: expect.stringMatching(/^user-1\/documents\/\d+-launch-plan\.docx$/),
        url: expect.stringContaining('launch-plan.docx'),
        mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        asset_type: 'document',
        name: 'launch-plan.docx',
        original_filename: 'launch-plan.docx',
        file_size: 3,
        user_id: 'user-1',
        source_surface: 'agent_generated_document',
      },
      success: true,
      file_name: 'launch-plan.docx',
      document: {
        campaign_id: 'campaign-1',
        conversation_id: CONVERSATION_ID,
        document_type: 'brief',
        title: 'Launch Plan',
      },
    })
    expect(uploaded[0]).toMatchObject({
      options: {
        contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        upsert: false,
      },
    })
    expect(String(uploaded[0]?.path)).toMatch(/^user-1\/documents\/\d+-launch-plan\.docx$/)
    expect(inserted[0]).toMatchObject({
      campaign_id: 'campaign-1',
      conversation_id: CONVERSATION_ID,
      document_type: 'brief',
      title: 'Launch Plan',
      content: {
        file_name: 'launch-plan.docx',
        asset_ref: expect.objectContaining({
          kind: 'storage_asset',
          file_path: expect.stringContaining('launch-plan.docx'),
        }),
        source_content: '<h1>Launch</h1><p>Ship it</p>',
        source_format: 'html',
        type: 'docx',
      },
    })
  })

  it('creates a PDF conversation document after uploading generated bytes', async () => {
    const inserted: Array<Record<string, unknown>> = []
    const uploaded: Array<Record<string, unknown>> = []
    const supabase = makeConversationClient(inserted)
    const target = makeDocumentTarget({
      supabase,
      serviceClient: makeStorageClient(uploaded),
    })
    const handler = new ArtifactPdfService().getHandlers(target).create_pdf

    const result = await handler(
      {
        title: 'Offer Memo',
        content: '# Offer\n\nBody',
        content_format: 'markdown',
      },
      'agent:vibey:session',
    )

    expect(result).toMatchObject({
      asset_ref: {
        kind: 'storage_asset',
        bucket_name: 'media',
        file_path: expect.stringMatching(/^user-1\/documents\/\d+-offer-memo\.pdf$/),
        url: expect.stringContaining('offer-memo.pdf'),
        mime_type: 'application/pdf',
        asset_type: 'document',
        name: 'offer-memo.pdf',
        original_filename: 'offer-memo.pdf',
        file_size: 3,
        user_id: 'user-1',
        source_surface: 'agent_generated_document',
      },
      success: true,
      file_name: 'offer-memo.pdf',
      document: {
        campaign_id: 'campaign-1',
        conversation_id: CONVERSATION_ID,
        document_type: 'offer',
        title: 'Offer Memo',
      },
    })
    expect(uploaded[0]).toMatchObject({
      options: { contentType: 'application/pdf', upsert: false },
    })
    expect(String(uploaded[0]?.path)).toMatch(/^user-1\/documents\/\d+-offer-memo\.pdf$/)
    expect(inserted[0]).toMatchObject({
      campaign_id: 'campaign-1',
      conversation_id: CONVERSATION_ID,
      document_type: 'offer',
      title: 'Offer Memo',
      content: {
        file_name: 'offer-memo.pdf',
        asset_ref: expect.objectContaining({
          kind: 'storage_asset',
          file_path: expect.stringContaining('offer-memo.pdf'),
        }),
        source_content: '# Offer\n\nBody',
        source_format: 'markdown',
        type: 'pdf',
      },
    })
  })

  it('persists a PDF mission subtask deliverable and appends the execution receipt', async () => {
    const deliverables: Array<Record<string, unknown>> = []
    const subtaskUpdates: Array<Record<string, unknown>> = []
    const serviceClient = {
      from: vi.fn((table: string) => {
        if (table === 'mission_subtasks') {
          const chain: any = {
            select: vi.fn(() => chain),
            update: vi.fn((payload: Record<string, unknown>) => {
              subtaskUpdates.push(payload)
              return chain
            }),
            eq: vi.fn(() => chain),
            maybeSingle: vi.fn(async () => ({
              data: {
                id: SUBTASK_ID,
                mission_id: MISSION_ID,
                user_id: USER_ID,
                execution_state: { completed_actions: [] },
              },
              error: null,
            })),
          }
          return chain
        }
        if (table === 'missions') {
          const chain: any = {
            select: vi.fn(() => chain),
            eq: vi.fn(() => chain),
            maybeSingle: vi.fn(async () => ({
              data: {
                id: MISSION_ID,
                campaign_id: 'campaign-1',
                org_id: 'org-1',
                user_id: USER_ID,
              },
              error: null,
            })),
          }
          return chain
        }
        if (table === 'mission_deliverables') {
          const chain: any = {
            insert: vi.fn((payload: Record<string, unknown>) => {
              deliverables.push(payload)
              return chain
            }),
            upsert: vi.fn((payload: Record<string, unknown>) => {
              deliverables.push(payload)
              return chain
            }),
            select: vi.fn(() => chain),
            single: vi.fn(async () => ({
              data: {
                id: 'deliverable-1',
                type: 'pdf',
                title: deliverables[0]?.title,
                file_url: deliverables[0]?.file_url,
                file_name: deliverables[0]?.file_name,
                metadata: deliverables[0]?.metadata,
              },
              error: null,
            })),
          }
          return chain
        }
        return {}
      }),
    }
    const target = {
      generateStyledPdfBytes: vi.fn(async () => new Uint8Array([7, 8, 9])),
      getUserClient: vi.fn(async () => makeConversationClient([])),
      isMissionSessionKey: vi.fn(() => true),
      logger: { log: vi.fn(), warn: vi.fn() },
      parseAgentIdFromSessionKey: vi.fn(() => 'vibey'),
      parseConversationId: vi.fn(() => null),
      resolveUserId: vi.fn(() => USER_ID),
      serviceClient: {
        ...serviceClient,
        storage: makeStorageClient([]).storage,
      },
    }
    const handler = new ArtifactPdfService().getHandlers(target).create_pdf

    const result = await handler(
      {
        title: 'Mission PDF',
        content: 'Mission body',
        document_type: 'report',
      },
      `agent:gateway:subtask:vibey:${USER_ID}:${SUBTASK_ID}`,
    )

    expect(result).toMatchObject({
      asset_ref: {
        kind: 'storage_asset',
        bucket_name: 'media',
        file_path: expect.stringContaining('mission-pdf.pdf'),
        url: expect.stringContaining('mission-pdf.pdf'),
        mime_type: 'application/pdf',
        asset_type: 'document',
        name: 'mission-pdf.pdf',
        original_filename: 'mission-pdf.pdf',
        file_size: 3,
        user_id: 'user-1',
        org_id: 'org-1',
        source_surface: 'agent_generated_document',
      },
      success: true,
      deliverable_id: 'deliverable-1',
      file_name: 'mission-pdf.pdf',
      file_url: expect.stringContaining('mission-pdf.pdf'),
      title: 'Mission PDF',
      type: 'pdf',
    })
    expect(deliverables[0]).toMatchObject({
      agent_key: 'vibey',
      campaign_id: 'campaign-1',
      content: 'Mission body',
      file_name: 'mission-pdf.pdf',
      file_size: 3,
      idempotency_key: expect.stringContaining(
        `mission:${MISSION_ID}:subtask:${SUBTASK_ID}:agent:vibey:action:create_pdf`,
      ),
      mime_type: 'application/pdf',
      mission_id: MISSION_ID,
      org_id: 'org-1',
      source_action: 'create_pdf',
      type: 'pdf',
      user_id: USER_ID,
      metadata: expect.objectContaining({
        asset_ref: expect.objectContaining({
          kind: 'storage_asset',
          file_path: expect.stringContaining('mission-pdf.pdf'),
        }),
      }),
    })
    expect(subtaskUpdates[0]).toMatchObject({
      execution_state: {
        completed_actions: [
          expect.objectContaining({
            action: 'create_pdf',
            deliverable_id: 'deliverable-1',
            file_name: 'mission-pdf.pdf',
          }),
        ],
      },
    })
  })
})
